// Code generated by ent, DO NOT EDIT.

package softwareassignment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/open-uem/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldLTE(FieldID, id))
}

// TargetID applies equality check predicate on the "target_id" field. It's identical to TargetIDEQ.
func TargetID(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEQ(FieldTargetID, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEQ(FieldPriority, v))
}

// ConditionPredicate applies equality check predicate on the "condition_predicate" field. It's identical to ConditionPredicateEQ.
func ConditionPredicate(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEQ(FieldConditionPredicate, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEQ(FieldActive, v))
}

// Created applies equality check predicate on the "created" field. It's identical to CreatedEQ.
func Created(v time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEQ(FieldCreated, v))
}

// Modified applies equality check predicate on the "modified" field. It's identical to ModifiedEQ.
func Modified(v time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEQ(FieldModified, v))
}

// AssignmentTypeEQ applies the EQ predicate on the "assignment_type" field.
func AssignmentTypeEQ(v AssignmentType) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEQ(FieldAssignmentType, v))
}

// AssignmentTypeNEQ applies the NEQ predicate on the "assignment_type" field.
func AssignmentTypeNEQ(v AssignmentType) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNEQ(FieldAssignmentType, v))
}

// AssignmentTypeIn applies the In predicate on the "assignment_type" field.
func AssignmentTypeIn(vs ...AssignmentType) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldIn(FieldAssignmentType, vs...))
}

// AssignmentTypeNotIn applies the NotIn predicate on the "assignment_type" field.
func AssignmentTypeNotIn(vs ...AssignmentType) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNotIn(FieldAssignmentType, vs...))
}

// TargetTypeEQ applies the EQ predicate on the "target_type" field.
func TargetTypeEQ(v TargetType) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEQ(FieldTargetType, v))
}

// TargetTypeNEQ applies the NEQ predicate on the "target_type" field.
func TargetTypeNEQ(v TargetType) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNEQ(FieldTargetType, v))
}

// TargetTypeIn applies the In predicate on the "target_type" field.
func TargetTypeIn(vs ...TargetType) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldIn(FieldTargetType, vs...))
}

// TargetTypeNotIn applies the NotIn predicate on the "target_type" field.
func TargetTypeNotIn(vs ...TargetType) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNotIn(FieldTargetType, vs...))
}

// TargetIDEQ applies the EQ predicate on the "target_id" field.
func TargetIDEQ(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEQ(FieldTargetID, v))
}

// TargetIDNEQ applies the NEQ predicate on the "target_id" field.
func TargetIDNEQ(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNEQ(FieldTargetID, v))
}

// TargetIDIn applies the In predicate on the "target_id" field.
func TargetIDIn(vs ...string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldIn(FieldTargetID, vs...))
}

// TargetIDNotIn applies the NotIn predicate on the "target_id" field.
func TargetIDNotIn(vs ...string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNotIn(FieldTargetID, vs...))
}

// TargetIDGT applies the GT predicate on the "target_id" field.
func TargetIDGT(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldGT(FieldTargetID, v))
}

// TargetIDGTE applies the GTE predicate on the "target_id" field.
func TargetIDGTE(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldGTE(FieldTargetID, v))
}

// TargetIDLT applies the LT predicate on the "target_id" field.
func TargetIDLT(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldLT(FieldTargetID, v))
}

// TargetIDLTE applies the LTE predicate on the "target_id" field.
func TargetIDLTE(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldLTE(FieldTargetID, v))
}

// TargetIDContains applies the Contains predicate on the "target_id" field.
func TargetIDContains(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldContains(FieldTargetID, v))
}

// TargetIDHasPrefix applies the HasPrefix predicate on the "target_id" field.
func TargetIDHasPrefix(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldHasPrefix(FieldTargetID, v))
}

// TargetIDHasSuffix applies the HasSuffix predicate on the "target_id" field.
func TargetIDHasSuffix(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldHasSuffix(FieldTargetID, v))
}

// TargetIDEqualFold applies the EqualFold predicate on the "target_id" field.
func TargetIDEqualFold(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEqualFold(FieldTargetID, v))
}

// TargetIDContainsFold applies the ContainsFold predicate on the "target_id" field.
func TargetIDContainsFold(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldContainsFold(FieldTargetID, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldLTE(FieldPriority, v))
}

// PriorityIsNil applies the IsNil predicate on the "priority" field.
func PriorityIsNil() predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldIsNull(FieldPriority))
}

// PriorityNotNil applies the NotNil predicate on the "priority" field.
func PriorityNotNil() predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNotNull(FieldPriority))
}

// ConditionPredicateEQ applies the EQ predicate on the "condition_predicate" field.
func ConditionPredicateEQ(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEQ(FieldConditionPredicate, v))
}

// ConditionPredicateNEQ applies the NEQ predicate on the "condition_predicate" field.
func ConditionPredicateNEQ(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNEQ(FieldConditionPredicate, v))
}

// ConditionPredicateIn applies the In predicate on the "condition_predicate" field.
func ConditionPredicateIn(vs ...string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldIn(FieldConditionPredicate, vs...))
}

// ConditionPredicateNotIn applies the NotIn predicate on the "condition_predicate" field.
func ConditionPredicateNotIn(vs ...string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNotIn(FieldConditionPredicate, vs...))
}

// ConditionPredicateGT applies the GT predicate on the "condition_predicate" field.
func ConditionPredicateGT(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldGT(FieldConditionPredicate, v))
}

// ConditionPredicateGTE applies the GTE predicate on the "condition_predicate" field.
func ConditionPredicateGTE(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldGTE(FieldConditionPredicate, v))
}

// ConditionPredicateLT applies the LT predicate on the "condition_predicate" field.
func ConditionPredicateLT(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldLT(FieldConditionPredicate, v))
}

// ConditionPredicateLTE applies the LTE predicate on the "condition_predicate" field.
func ConditionPredicateLTE(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldLTE(FieldConditionPredicate, v))
}

// ConditionPredicateContains applies the Contains predicate on the "condition_predicate" field.
func ConditionPredicateContains(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldContains(FieldConditionPredicate, v))
}

// ConditionPredicateHasPrefix applies the HasPrefix predicate on the "condition_predicate" field.
func ConditionPredicateHasPrefix(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldHasPrefix(FieldConditionPredicate, v))
}

// ConditionPredicateHasSuffix applies the HasSuffix predicate on the "condition_predicate" field.
func ConditionPredicateHasSuffix(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldHasSuffix(FieldConditionPredicate, v))
}

// ConditionPredicateIsNil applies the IsNil predicate on the "condition_predicate" field.
func ConditionPredicateIsNil() predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldIsNull(FieldConditionPredicate))
}

// ConditionPredicateNotNil applies the NotNil predicate on the "condition_predicate" field.
func ConditionPredicateNotNil() predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNotNull(FieldConditionPredicate))
}

// ConditionPredicateEqualFold applies the EqualFold predicate on the "condition_predicate" field.
func ConditionPredicateEqualFold(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEqualFold(FieldConditionPredicate, v))
}

// ConditionPredicateContainsFold applies the ContainsFold predicate on the "condition_predicate" field.
func ConditionPredicateContainsFold(v string) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldContainsFold(FieldConditionPredicate, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNEQ(FieldActive, v))
}

// ActiveIsNil applies the IsNil predicate on the "active" field.
func ActiveIsNil() predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldIsNull(FieldActive))
}

// ActiveNotNil applies the NotNil predicate on the "active" field.
func ActiveNotNil() predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNotNull(FieldActive))
}

// CreatedEQ applies the EQ predicate on the "created" field.
func CreatedEQ(v time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEQ(FieldCreated, v))
}

// CreatedNEQ applies the NEQ predicate on the "created" field.
func CreatedNEQ(v time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNEQ(FieldCreated, v))
}

// CreatedIn applies the In predicate on the "created" field.
func CreatedIn(vs ...time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldIn(FieldCreated, vs...))
}

// CreatedNotIn applies the NotIn predicate on the "created" field.
func CreatedNotIn(vs ...time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNotIn(FieldCreated, vs...))
}

// CreatedGT applies the GT predicate on the "created" field.
func CreatedGT(v time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldGT(FieldCreated, v))
}

// CreatedGTE applies the GTE predicate on the "created" field.
func CreatedGTE(v time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldGTE(FieldCreated, v))
}

// CreatedLT applies the LT predicate on the "created" field.
func CreatedLT(v time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldLT(FieldCreated, v))
}

// CreatedLTE applies the LTE predicate on the "created" field.
func CreatedLTE(v time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldLTE(FieldCreated, v))
}

// CreatedIsNil applies the IsNil predicate on the "created" field.
func CreatedIsNil() predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldIsNull(FieldCreated))
}

// CreatedNotNil applies the NotNil predicate on the "created" field.
func CreatedNotNil() predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNotNull(FieldCreated))
}

// ModifiedEQ applies the EQ predicate on the "modified" field.
func ModifiedEQ(v time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldEQ(FieldModified, v))
}

// ModifiedNEQ applies the NEQ predicate on the "modified" field.
func ModifiedNEQ(v time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNEQ(FieldModified, v))
}

// ModifiedIn applies the In predicate on the "modified" field.
func ModifiedIn(vs ...time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldIn(FieldModified, vs...))
}

// ModifiedNotIn applies the NotIn predicate on the "modified" field.
func ModifiedNotIn(vs ...time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNotIn(FieldModified, vs...))
}

// ModifiedGT applies the GT predicate on the "modified" field.
func ModifiedGT(v time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldGT(FieldModified, v))
}

// ModifiedGTE applies the GTE predicate on the "modified" field.
func ModifiedGTE(v time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldGTE(FieldModified, v))
}

// ModifiedLT applies the LT predicate on the "modified" field.
func ModifiedLT(v time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldLT(FieldModified, v))
}

// ModifiedLTE applies the LTE predicate on the "modified" field.
func ModifiedLTE(v time.Time) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldLTE(FieldModified, v))
}

// ModifiedIsNil applies the IsNil predicate on the "modified" field.
func ModifiedIsNil() predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldIsNull(FieldModified))
}

// ModifiedNotNil applies the NotNil predicate on the "modified" field.
func ModifiedNotNil() predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.FieldNotNull(FieldModified))
}

// HasPackage applies the HasEdge predicate on the "package" edge.
func HasPackage() predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PackageTable, PackageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPackageWith applies the HasEdge predicate on the "package" edge with a given conditions (other predicates).
func HasPackageWith(preds ...predicate.SoftwarePackage) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(func(s *sql.Selector) {
		step := newPackageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SoftwareAssignment) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SoftwareAssignment) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SoftwareAssignment) predicate.SoftwareAssignment {
	return predicate.SoftwareAssignment(sql.NotPredicates(p))
}
