// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/EigerCode/ent/branding"
	"github.com/EigerCode/ent/predicate"
)

// BrandingUpdate is the builder for updating Branding entities.
type BrandingUpdate struct {
	config
	hooks     []Hook
	mutation  *BrandingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the BrandingUpdate builder.
func (bu *BrandingUpdate) Where(ps ...predicate.Branding) *BrandingUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetLogoLight sets the "logo_light" field.
func (bu *BrandingUpdate) SetLogoLight(s string) *BrandingUpdate {
	bu.mutation.SetLogoLight(s)
	return bu
}

// SetNillableLogoLight sets the "logo_light" field if the given value is not nil.
func (bu *BrandingUpdate) SetNillableLogoLight(s *string) *BrandingUpdate {
	if s != nil {
		bu.SetLogoLight(*s)
	}
	return bu
}

// ClearLogoLight clears the value of the "logo_light" field.
func (bu *BrandingUpdate) ClearLogoLight() *BrandingUpdate {
	bu.mutation.ClearLogoLight()
	return bu
}

// SetLogoSmall sets the "logo_small" field.
func (bu *BrandingUpdate) SetLogoSmall(s string) *BrandingUpdate {
	bu.mutation.SetLogoSmall(s)
	return bu
}

// SetNillableLogoSmall sets the "logo_small" field if the given value is not nil.
func (bu *BrandingUpdate) SetNillableLogoSmall(s *string) *BrandingUpdate {
	if s != nil {
		bu.SetLogoSmall(*s)
	}
	return bu
}

// ClearLogoSmall clears the value of the "logo_small" field.
func (bu *BrandingUpdate) ClearLogoSmall() *BrandingUpdate {
	bu.mutation.ClearLogoSmall()
	return bu
}

// SetPrimaryColor sets the "primary_color" field.
func (bu *BrandingUpdate) SetPrimaryColor(s string) *BrandingUpdate {
	bu.mutation.SetPrimaryColor(s)
	return bu
}

// SetNillablePrimaryColor sets the "primary_color" field if the given value is not nil.
func (bu *BrandingUpdate) SetNillablePrimaryColor(s *string) *BrandingUpdate {
	if s != nil {
		bu.SetPrimaryColor(*s)
	}
	return bu
}

// ClearPrimaryColor clears the value of the "primary_color" field.
func (bu *BrandingUpdate) ClearPrimaryColor() *BrandingUpdate {
	bu.mutation.ClearPrimaryColor()
	return bu
}

// SetProductName sets the "product_name" field.
func (bu *BrandingUpdate) SetProductName(s string) *BrandingUpdate {
	bu.mutation.SetProductName(s)
	return bu
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (bu *BrandingUpdate) SetNillableProductName(s *string) *BrandingUpdate {
	if s != nil {
		bu.SetProductName(*s)
	}
	return bu
}

// ClearProductName clears the value of the "product_name" field.
func (bu *BrandingUpdate) ClearProductName() *BrandingUpdate {
	bu.mutation.ClearProductName()
	return bu
}

// Mutation returns the BrandingMutation object of the builder.
func (bu *BrandingUpdate) Mutation() *BrandingMutation {
	return bu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BrandingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BrandingUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BrandingUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BrandingUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (bu *BrandingUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BrandingUpdate {
	bu.modifiers = append(bu.modifiers, modifiers...)
	return bu
}

func (bu *BrandingUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(branding.Table, branding.Columns, sqlgraph.NewFieldSpec(branding.FieldID, field.TypeInt))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.LogoLight(); ok {
		_spec.SetField(branding.FieldLogoLight, field.TypeString, value)
	}
	if bu.mutation.LogoLightCleared() {
		_spec.ClearField(branding.FieldLogoLight, field.TypeString)
	}
	if value, ok := bu.mutation.LogoSmall(); ok {
		_spec.SetField(branding.FieldLogoSmall, field.TypeString, value)
	}
	if bu.mutation.LogoSmallCleared() {
		_spec.ClearField(branding.FieldLogoSmall, field.TypeString)
	}
	if value, ok := bu.mutation.PrimaryColor(); ok {
		_spec.SetField(branding.FieldPrimaryColor, field.TypeString, value)
	}
	if bu.mutation.PrimaryColorCleared() {
		_spec.ClearField(branding.FieldPrimaryColor, field.TypeString)
	}
	if value, ok := bu.mutation.ProductName(); ok {
		_spec.SetField(branding.FieldProductName, field.TypeString, value)
	}
	if bu.mutation.ProductNameCleared() {
		_spec.ClearField(branding.FieldProductName, field.TypeString)
	}
	_spec.AddModifiers(bu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{branding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BrandingUpdateOne is the builder for updating a single Branding entity.
type BrandingUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *BrandingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetLogoLight sets the "logo_light" field.
func (buo *BrandingUpdateOne) SetLogoLight(s string) *BrandingUpdateOne {
	buo.mutation.SetLogoLight(s)
	return buo
}

// SetNillableLogoLight sets the "logo_light" field if the given value is not nil.
func (buo *BrandingUpdateOne) SetNillableLogoLight(s *string) *BrandingUpdateOne {
	if s != nil {
		buo.SetLogoLight(*s)
	}
	return buo
}

// ClearLogoLight clears the value of the "logo_light" field.
func (buo *BrandingUpdateOne) ClearLogoLight() *BrandingUpdateOne {
	buo.mutation.ClearLogoLight()
	return buo
}

// SetLogoSmall sets the "logo_small" field.
func (buo *BrandingUpdateOne) SetLogoSmall(s string) *BrandingUpdateOne {
	buo.mutation.SetLogoSmall(s)
	return buo
}

// SetNillableLogoSmall sets the "logo_small" field if the given value is not nil.
func (buo *BrandingUpdateOne) SetNillableLogoSmall(s *string) *BrandingUpdateOne {
	if s != nil {
		buo.SetLogoSmall(*s)
	}
	return buo
}

// ClearLogoSmall clears the value of the "logo_small" field.
func (buo *BrandingUpdateOne) ClearLogoSmall() *BrandingUpdateOne {
	buo.mutation.ClearLogoSmall()
	return buo
}

// SetPrimaryColor sets the "primary_color" field.
func (buo *BrandingUpdateOne) SetPrimaryColor(s string) *BrandingUpdateOne {
	buo.mutation.SetPrimaryColor(s)
	return buo
}

// SetNillablePrimaryColor sets the "primary_color" field if the given value is not nil.
func (buo *BrandingUpdateOne) SetNillablePrimaryColor(s *string) *BrandingUpdateOne {
	if s != nil {
		buo.SetPrimaryColor(*s)
	}
	return buo
}

// ClearPrimaryColor clears the value of the "primary_color" field.
func (buo *BrandingUpdateOne) ClearPrimaryColor() *BrandingUpdateOne {
	buo.mutation.ClearPrimaryColor()
	return buo
}

// SetProductName sets the "product_name" field.
func (buo *BrandingUpdateOne) SetProductName(s string) *BrandingUpdateOne {
	buo.mutation.SetProductName(s)
	return buo
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (buo *BrandingUpdateOne) SetNillableProductName(s *string) *BrandingUpdateOne {
	if s != nil {
		buo.SetProductName(*s)
	}
	return buo
}

// ClearProductName clears the value of the "product_name" field.
func (buo *BrandingUpdateOne) ClearProductName() *BrandingUpdateOne {
	buo.mutation.ClearProductName()
	return buo
}

// Mutation returns the BrandingMutation object of the builder.
func (buo *BrandingUpdateOne) Mutation() *BrandingMutation {
	return buo.mutation
}

// Where appends a list predicates to the BrandingUpdate builder.
func (buo *BrandingUpdateOne) Where(ps ...predicate.Branding) *BrandingUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BrandingUpdateOne) Select(field string, fields ...string) *BrandingUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Branding entity.
func (buo *BrandingUpdateOne) Save(ctx context.Context) (*Branding, error) {
	return withHooks(ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BrandingUpdateOne) SaveX(ctx context.Context) *Branding {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BrandingUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BrandingUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (buo *BrandingUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BrandingUpdateOne {
	buo.modifiers = append(buo.modifiers, modifiers...)
	return buo
}

func (buo *BrandingUpdateOne) sqlSave(ctx context.Context) (_node *Branding, err error) {
	_spec := sqlgraph.NewUpdateSpec(branding.Table, branding.Columns, sqlgraph.NewFieldSpec(branding.FieldID, field.TypeInt))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Branding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, branding.FieldID)
		for _, f := range fields {
			if !branding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != branding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.LogoLight(); ok {
		_spec.SetField(branding.FieldLogoLight, field.TypeString, value)
	}
	if buo.mutation.LogoLightCleared() {
		_spec.ClearField(branding.FieldLogoLight, field.TypeString)
	}
	if value, ok := buo.mutation.LogoSmall(); ok {
		_spec.SetField(branding.FieldLogoSmall, field.TypeString, value)
	}
	if buo.mutation.LogoSmallCleared() {
		_spec.ClearField(branding.FieldLogoSmall, field.TypeString)
	}
	if value, ok := buo.mutation.PrimaryColor(); ok {
		_spec.SetField(branding.FieldPrimaryColor, field.TypeString, value)
	}
	if buo.mutation.PrimaryColorCleared() {
		_spec.ClearField(branding.FieldPrimaryColor, field.TypeString)
	}
	if value, ok := buo.mutation.ProductName(); ok {
		_spec.SetField(branding.FieldProductName, field.TypeString, value)
	}
	if buo.mutation.ProductNameCleared() {
		_spec.ClearField(branding.FieldProductName, field.TypeString)
	}
	_spec.AddModifiers(buo.modifiers...)
	_node = &Branding{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{branding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
