// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/EigerCode/ent/managedpackage"
	"github.com/EigerCode/ent/predicate"
	"github.com/EigerCode/ent/softwarecatalog"
	"github.com/EigerCode/ent/softwareinstalllog"
	"github.com/EigerCode/ent/softwarerepo"
	"github.com/EigerCode/ent/tenant"
)

// ManagedPackageQuery is the builder for querying ManagedPackage entities.
type ManagedPackageQuery struct {
	config
	ctx             *QueryContext
	order           []managedpackage.OrderOption
	inters          []Interceptor
	predicates      []predicate.ManagedPackage
	withRepo        *SoftwareRepoQuery
	withCatalogs    *SoftwareCatalogQuery
	withTenant      *TenantQuery
	withInstallLogs *SoftwareInstallLogQuery
	withRequires    *ManagedPackageQuery
	withUpdateFor   *ManagedPackageQuery
	withGlobalRef   *ManagedPackageQuery
	withSubscribers *ManagedPackageQuery
	withFKs         bool
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ManagedPackageQuery builder.
func (mpq *ManagedPackageQuery) Where(ps ...predicate.ManagedPackage) *ManagedPackageQuery {
	mpq.predicates = append(mpq.predicates, ps...)
	return mpq
}

// Limit the number of records to be returned by this query.
func (mpq *ManagedPackageQuery) Limit(limit int) *ManagedPackageQuery {
	mpq.ctx.Limit = &limit
	return mpq
}

// Offset to start from.
func (mpq *ManagedPackageQuery) Offset(offset int) *ManagedPackageQuery {
	mpq.ctx.Offset = &offset
	return mpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mpq *ManagedPackageQuery) Unique(unique bool) *ManagedPackageQuery {
	mpq.ctx.Unique = &unique
	return mpq
}

// Order specifies how the records should be ordered.
func (mpq *ManagedPackageQuery) Order(o ...managedpackage.OrderOption) *ManagedPackageQuery {
	mpq.order = append(mpq.order, o...)
	return mpq
}

// QueryRepo chains the current query on the "repo" edge.
func (mpq *ManagedPackageQuery) QueryRepo() *SoftwareRepoQuery {
	query := (&SoftwareRepoClient{config: mpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(managedpackage.Table, managedpackage.FieldID, selector),
			sqlgraph.To(softwarerepo.Table, softwarerepo.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, managedpackage.RepoTable, managedpackage.RepoColumn),
		)
		fromU = sqlgraph.SetNeighbors(mpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCatalogs chains the current query on the "catalogs" edge.
func (mpq *ManagedPackageQuery) QueryCatalogs() *SoftwareCatalogQuery {
	query := (&SoftwareCatalogClient{config: mpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(managedpackage.Table, managedpackage.FieldID, selector),
			sqlgraph.To(softwarecatalog.Table, softwarecatalog.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, managedpackage.CatalogsTable, managedpackage.CatalogsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(mpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTenant chains the current query on the "tenant" edge.
func (mpq *ManagedPackageQuery) QueryTenant() *TenantQuery {
	query := (&TenantClient{config: mpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(managedpackage.Table, managedpackage.FieldID, selector),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, managedpackage.TenantTable, managedpackage.TenantColumn),
		)
		fromU = sqlgraph.SetNeighbors(mpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryInstallLogs chains the current query on the "install_logs" edge.
func (mpq *ManagedPackageQuery) QueryInstallLogs() *SoftwareInstallLogQuery {
	query := (&SoftwareInstallLogClient{config: mpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(managedpackage.Table, managedpackage.FieldID, selector),
			sqlgraph.To(softwareinstalllog.Table, softwareinstalllog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, managedpackage.InstallLogsTable, managedpackage.InstallLogsColumn),
		)
		fromU = sqlgraph.SetNeighbors(mpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRequires chains the current query on the "requires" edge.
func (mpq *ManagedPackageQuery) QueryRequires() *ManagedPackageQuery {
	query := (&ManagedPackageClient{config: mpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(managedpackage.Table, managedpackage.FieldID, selector),
			sqlgraph.To(managedpackage.Table, managedpackage.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, managedpackage.RequiresTable, managedpackage.RequiresPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(mpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUpdateFor chains the current query on the "update_for" edge.
func (mpq *ManagedPackageQuery) QueryUpdateFor() *ManagedPackageQuery {
	query := (&ManagedPackageClient{config: mpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(managedpackage.Table, managedpackage.FieldID, selector),
			sqlgraph.To(managedpackage.Table, managedpackage.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, managedpackage.UpdateForTable, managedpackage.UpdateForPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(mpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGlobalRef chains the current query on the "global_ref" edge.
func (mpq *ManagedPackageQuery) QueryGlobalRef() *ManagedPackageQuery {
	query := (&ManagedPackageClient{config: mpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(managedpackage.Table, managedpackage.FieldID, selector),
			sqlgraph.To(managedpackage.Table, managedpackage.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, managedpackage.GlobalRefTable, managedpackage.GlobalRefColumn),
		)
		fromU = sqlgraph.SetNeighbors(mpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySubscribers chains the current query on the "subscribers" edge.
func (mpq *ManagedPackageQuery) QuerySubscribers() *ManagedPackageQuery {
	query := (&ManagedPackageClient{config: mpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(managedpackage.Table, managedpackage.FieldID, selector),
			sqlgraph.To(managedpackage.Table, managedpackage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, managedpackage.SubscribersTable, managedpackage.SubscribersColumn),
		)
		fromU = sqlgraph.SetNeighbors(mpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ManagedPackage entity from the query.
// Returns a *NotFoundError when no ManagedPackage was found.
func (mpq *ManagedPackageQuery) First(ctx context.Context) (*ManagedPackage, error) {
	nodes, err := mpq.Limit(1).All(setContextOp(ctx, mpq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{managedpackage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mpq *ManagedPackageQuery) FirstX(ctx context.Context) *ManagedPackage {
	node, err := mpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ManagedPackage ID from the query.
// Returns a *NotFoundError when no ManagedPackage ID was found.
func (mpq *ManagedPackageQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mpq.Limit(1).IDs(setContextOp(ctx, mpq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{managedpackage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mpq *ManagedPackageQuery) FirstIDX(ctx context.Context) int {
	id, err := mpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ManagedPackage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ManagedPackage entity is found.
// Returns a *NotFoundError when no ManagedPackage entities are found.
func (mpq *ManagedPackageQuery) Only(ctx context.Context) (*ManagedPackage, error) {
	nodes, err := mpq.Limit(2).All(setContextOp(ctx, mpq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{managedpackage.Label}
	default:
		return nil, &NotSingularError{managedpackage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mpq *ManagedPackageQuery) OnlyX(ctx context.Context) *ManagedPackage {
	node, err := mpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ManagedPackage ID in the query.
// Returns a *NotSingularError when more than one ManagedPackage ID is found.
// Returns a *NotFoundError when no entities are found.
func (mpq *ManagedPackageQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mpq.Limit(2).IDs(setContextOp(ctx, mpq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{managedpackage.Label}
	default:
		err = &NotSingularError{managedpackage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mpq *ManagedPackageQuery) OnlyIDX(ctx context.Context) int {
	id, err := mpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ManagedPackages.
func (mpq *ManagedPackageQuery) All(ctx context.Context) ([]*ManagedPackage, error) {
	ctx = setContextOp(ctx, mpq.ctx, ent.OpQueryAll)
	if err := mpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ManagedPackage, *ManagedPackageQuery]()
	return withInterceptors[[]*ManagedPackage](ctx, mpq, qr, mpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mpq *ManagedPackageQuery) AllX(ctx context.Context) []*ManagedPackage {
	nodes, err := mpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ManagedPackage IDs.
func (mpq *ManagedPackageQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mpq.ctx.Unique == nil && mpq.path != nil {
		mpq.Unique(true)
	}
	ctx = setContextOp(ctx, mpq.ctx, ent.OpQueryIDs)
	if err = mpq.Select(managedpackage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mpq *ManagedPackageQuery) IDsX(ctx context.Context) []int {
	ids, err := mpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mpq *ManagedPackageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mpq.ctx, ent.OpQueryCount)
	if err := mpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mpq, querierCount[*ManagedPackageQuery](), mpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mpq *ManagedPackageQuery) CountX(ctx context.Context) int {
	count, err := mpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mpq *ManagedPackageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mpq.ctx, ent.OpQueryExist)
	switch _, err := mpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mpq *ManagedPackageQuery) ExistX(ctx context.Context) bool {
	exist, err := mpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ManagedPackageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mpq *ManagedPackageQuery) Clone() *ManagedPackageQuery {
	if mpq == nil {
		return nil
	}
	return &ManagedPackageQuery{
		config:          mpq.config,
		ctx:             mpq.ctx.Clone(),
		order:           append([]managedpackage.OrderOption{}, mpq.order...),
		inters:          append([]Interceptor{}, mpq.inters...),
		predicates:      append([]predicate.ManagedPackage{}, mpq.predicates...),
		withRepo:        mpq.withRepo.Clone(),
		withCatalogs:    mpq.withCatalogs.Clone(),
		withTenant:      mpq.withTenant.Clone(),
		withInstallLogs: mpq.withInstallLogs.Clone(),
		withRequires:    mpq.withRequires.Clone(),
		withUpdateFor:   mpq.withUpdateFor.Clone(),
		withGlobalRef:   mpq.withGlobalRef.Clone(),
		withSubscribers: mpq.withSubscribers.Clone(),
		// clone intermediate query.
		sql:       mpq.sql.Clone(),
		path:      mpq.path,
		modifiers: append([]func(*sql.Selector){}, mpq.modifiers...),
	}
}

// WithRepo tells the query-builder to eager-load the nodes that are connected to
// the "repo" edge. The optional arguments are used to configure the query builder of the edge.
func (mpq *ManagedPackageQuery) WithRepo(opts ...func(*SoftwareRepoQuery)) *ManagedPackageQuery {
	query := (&SoftwareRepoClient{config: mpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mpq.withRepo = query
	return mpq
}

// WithCatalogs tells the query-builder to eager-load the nodes that are connected to
// the "catalogs" edge. The optional arguments are used to configure the query builder of the edge.
func (mpq *ManagedPackageQuery) WithCatalogs(opts ...func(*SoftwareCatalogQuery)) *ManagedPackageQuery {
	query := (&SoftwareCatalogClient{config: mpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mpq.withCatalogs = query
	return mpq
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (mpq *ManagedPackageQuery) WithTenant(opts ...func(*TenantQuery)) *ManagedPackageQuery {
	query := (&TenantClient{config: mpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mpq.withTenant = query
	return mpq
}

// WithInstallLogs tells the query-builder to eager-load the nodes that are connected to
// the "install_logs" edge. The optional arguments are used to configure the query builder of the edge.
func (mpq *ManagedPackageQuery) WithInstallLogs(opts ...func(*SoftwareInstallLogQuery)) *ManagedPackageQuery {
	query := (&SoftwareInstallLogClient{config: mpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mpq.withInstallLogs = query
	return mpq
}

// WithRequires tells the query-builder to eager-load the nodes that are connected to
// the "requires" edge. The optional arguments are used to configure the query builder of the edge.
func (mpq *ManagedPackageQuery) WithRequires(opts ...func(*ManagedPackageQuery)) *ManagedPackageQuery {
	query := (&ManagedPackageClient{config: mpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mpq.withRequires = query
	return mpq
}

// WithUpdateFor tells the query-builder to eager-load the nodes that are connected to
// the "update_for" edge. The optional arguments are used to configure the query builder of the edge.
func (mpq *ManagedPackageQuery) WithUpdateFor(opts ...func(*ManagedPackageQuery)) *ManagedPackageQuery {
	query := (&ManagedPackageClient{config: mpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mpq.withUpdateFor = query
	return mpq
}

// WithGlobalRef tells the query-builder to eager-load the nodes that are connected to
// the "global_ref" edge. The optional arguments are used to configure the query builder of the edge.
func (mpq *ManagedPackageQuery) WithGlobalRef(opts ...func(*ManagedPackageQuery)) *ManagedPackageQuery {
	query := (&ManagedPackageClient{config: mpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mpq.withGlobalRef = query
	return mpq
}

// WithSubscribers tells the query-builder to eager-load the nodes that are connected to
// the "subscribers" edge. The optional arguments are used to configure the query builder of the edge.
func (mpq *ManagedPackageQuery) WithSubscribers(opts ...func(*ManagedPackageQuery)) *ManagedPackageQuery {
	query := (&ManagedPackageClient{config: mpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mpq.withSubscribers = query
	return mpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ManagedPackage.Query().
//		GroupBy(managedpackage.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mpq *ManagedPackageQuery) GroupBy(field string, fields ...string) *ManagedPackageGroupBy {
	mpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ManagedPackageGroupBy{build: mpq}
	grbuild.flds = &mpq.ctx.Fields
	grbuild.label = managedpackage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ManagedPackage.Query().
//		Select(managedpackage.FieldName).
//		Scan(ctx, &v)
func (mpq *ManagedPackageQuery) Select(fields ...string) *ManagedPackageSelect {
	mpq.ctx.Fields = append(mpq.ctx.Fields, fields...)
	sbuild := &ManagedPackageSelect{ManagedPackageQuery: mpq}
	sbuild.label = managedpackage.Label
	sbuild.flds, sbuild.scan = &mpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ManagedPackageSelect configured with the given aggregations.
func (mpq *ManagedPackageQuery) Aggregate(fns ...AggregateFunc) *ManagedPackageSelect {
	return mpq.Select().Aggregate(fns...)
}

func (mpq *ManagedPackageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mpq); err != nil {
				return err
			}
		}
	}
	for _, f := range mpq.ctx.Fields {
		if !managedpackage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mpq.path != nil {
		prev, err := mpq.path(ctx)
		if err != nil {
			return err
		}
		mpq.sql = prev
	}
	return nil
}

func (mpq *ManagedPackageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ManagedPackage, error) {
	var (
		nodes       = []*ManagedPackage{}
		withFKs     = mpq.withFKs
		_spec       = mpq.querySpec()
		loadedTypes = [8]bool{
			mpq.withRepo != nil,
			mpq.withCatalogs != nil,
			mpq.withTenant != nil,
			mpq.withInstallLogs != nil,
			mpq.withRequires != nil,
			mpq.withUpdateFor != nil,
			mpq.withGlobalRef != nil,
			mpq.withSubscribers != nil,
		}
	)
	if mpq.withRepo != nil || mpq.withTenant != nil || mpq.withGlobalRef != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, managedpackage.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ManagedPackage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ManagedPackage{config: mpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(mpq.modifiers) > 0 {
		_spec.Modifiers = mpq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mpq.withRepo; query != nil {
		if err := mpq.loadRepo(ctx, query, nodes, nil,
			func(n *ManagedPackage, e *SoftwareRepo) { n.Edges.Repo = e }); err != nil {
			return nil, err
		}
	}
	if query := mpq.withCatalogs; query != nil {
		if err := mpq.loadCatalogs(ctx, query, nodes,
			func(n *ManagedPackage) { n.Edges.Catalogs = []*SoftwareCatalog{} },
			func(n *ManagedPackage, e *SoftwareCatalog) { n.Edges.Catalogs = append(n.Edges.Catalogs, e) }); err != nil {
			return nil, err
		}
	}
	if query := mpq.withTenant; query != nil {
		if err := mpq.loadTenant(ctx, query, nodes, nil,
			func(n *ManagedPackage, e *Tenant) { n.Edges.Tenant = e }); err != nil {
			return nil, err
		}
	}
	if query := mpq.withInstallLogs; query != nil {
		if err := mpq.loadInstallLogs(ctx, query, nodes,
			func(n *ManagedPackage) { n.Edges.InstallLogs = []*SoftwareInstallLog{} },
			func(n *ManagedPackage, e *SoftwareInstallLog) { n.Edges.InstallLogs = append(n.Edges.InstallLogs, e) }); err != nil {
			return nil, err
		}
	}
	if query := mpq.withRequires; query != nil {
		if err := mpq.loadRequires(ctx, query, nodes,
			func(n *ManagedPackage) { n.Edges.Requires = []*ManagedPackage{} },
			func(n *ManagedPackage, e *ManagedPackage) { n.Edges.Requires = append(n.Edges.Requires, e) }); err != nil {
			return nil, err
		}
	}
	if query := mpq.withUpdateFor; query != nil {
		if err := mpq.loadUpdateFor(ctx, query, nodes,
			func(n *ManagedPackage) { n.Edges.UpdateFor = []*ManagedPackage{} },
			func(n *ManagedPackage, e *ManagedPackage) { n.Edges.UpdateFor = append(n.Edges.UpdateFor, e) }); err != nil {
			return nil, err
		}
	}
	if query := mpq.withGlobalRef; query != nil {
		if err := mpq.loadGlobalRef(ctx, query, nodes, nil,
			func(n *ManagedPackage, e *ManagedPackage) { n.Edges.GlobalRef = e }); err != nil {
			return nil, err
		}
	}
	if query := mpq.withSubscribers; query != nil {
		if err := mpq.loadSubscribers(ctx, query, nodes,
			func(n *ManagedPackage) { n.Edges.Subscribers = []*ManagedPackage{} },
			func(n *ManagedPackage, e *ManagedPackage) { n.Edges.Subscribers = append(n.Edges.Subscribers, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mpq *ManagedPackageQuery) loadRepo(ctx context.Context, query *SoftwareRepoQuery, nodes []*ManagedPackage, init func(*ManagedPackage), assign func(*ManagedPackage, *SoftwareRepo)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ManagedPackage)
	for i := range nodes {
		if nodes[i].software_repo_packages == nil {
			continue
		}
		fk := *nodes[i].software_repo_packages
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(softwarerepo.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "software_repo_packages" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (mpq *ManagedPackageQuery) loadCatalogs(ctx context.Context, query *SoftwareCatalogQuery, nodes []*ManagedPackage, init func(*ManagedPackage), assign func(*ManagedPackage, *SoftwareCatalog)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*ManagedPackage)
	nids := make(map[int]map[*ManagedPackage]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(managedpackage.CatalogsTable)
		s.Join(joinT).On(s.C(softwarecatalog.FieldID), joinT.C(managedpackage.CatalogsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(managedpackage.CatalogsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(managedpackage.CatalogsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*ManagedPackage]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*SoftwareCatalog](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "catalogs" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (mpq *ManagedPackageQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*ManagedPackage, init func(*ManagedPackage), assign func(*ManagedPackage, *Tenant)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ManagedPackage)
	for i := range nodes {
		if nodes[i].tenant_software_packages == nil {
			continue
		}
		fk := *nodes[i].tenant_software_packages
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tenant.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tenant_software_packages" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (mpq *ManagedPackageQuery) loadInstallLogs(ctx context.Context, query *SoftwareInstallLogQuery, nodes []*ManagedPackage, init func(*ManagedPackage), assign func(*ManagedPackage, *SoftwareInstallLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ManagedPackage)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.SoftwareInstallLog(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(managedpackage.InstallLogsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.managed_package_install_logs
		if fk == nil {
			return fmt.Errorf(`foreign-key "managed_package_install_logs" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "managed_package_install_logs" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (mpq *ManagedPackageQuery) loadRequires(ctx context.Context, query *ManagedPackageQuery, nodes []*ManagedPackage, init func(*ManagedPackage), assign func(*ManagedPackage, *ManagedPackage)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*ManagedPackage)
	nids := make(map[int]map[*ManagedPackage]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(managedpackage.RequiresTable)
		s.Join(joinT).On(s.C(managedpackage.FieldID), joinT.C(managedpackage.RequiresPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(managedpackage.RequiresPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(managedpackage.RequiresPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*ManagedPackage]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*ManagedPackage](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "requires" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (mpq *ManagedPackageQuery) loadUpdateFor(ctx context.Context, query *ManagedPackageQuery, nodes []*ManagedPackage, init func(*ManagedPackage), assign func(*ManagedPackage, *ManagedPackage)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*ManagedPackage)
	nids := make(map[int]map[*ManagedPackage]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(managedpackage.UpdateForTable)
		s.Join(joinT).On(s.C(managedpackage.FieldID), joinT.C(managedpackage.UpdateForPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(managedpackage.UpdateForPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(managedpackage.UpdateForPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*ManagedPackage]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*ManagedPackage](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "update_for" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (mpq *ManagedPackageQuery) loadGlobalRef(ctx context.Context, query *ManagedPackageQuery, nodes []*ManagedPackage, init func(*ManagedPackage), assign func(*ManagedPackage, *ManagedPackage)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ManagedPackage)
	for i := range nodes {
		if nodes[i].managed_package_subscribers == nil {
			continue
		}
		fk := *nodes[i].managed_package_subscribers
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(managedpackage.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "managed_package_subscribers" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (mpq *ManagedPackageQuery) loadSubscribers(ctx context.Context, query *ManagedPackageQuery, nodes []*ManagedPackage, init func(*ManagedPackage), assign func(*ManagedPackage, *ManagedPackage)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ManagedPackage)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ManagedPackage(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(managedpackage.SubscribersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.managed_package_subscribers
		if fk == nil {
			return fmt.Errorf(`foreign-key "managed_package_subscribers" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "managed_package_subscribers" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (mpq *ManagedPackageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mpq.querySpec()
	if len(mpq.modifiers) > 0 {
		_spec.Modifiers = mpq.modifiers
	}
	_spec.Node.Columns = mpq.ctx.Fields
	if len(mpq.ctx.Fields) > 0 {
		_spec.Unique = mpq.ctx.Unique != nil && *mpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mpq.driver, _spec)
}

func (mpq *ManagedPackageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(managedpackage.Table, managedpackage.Columns, sqlgraph.NewFieldSpec(managedpackage.FieldID, field.TypeInt))
	_spec.From = mpq.sql
	if unique := mpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mpq.path != nil {
		_spec.Unique = true
	}
	if fields := mpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, managedpackage.FieldID)
		for i := range fields {
			if fields[i] != managedpackage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mpq *ManagedPackageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mpq.driver.Dialect())
	t1 := builder.Table(managedpackage.Table)
	columns := mpq.ctx.Fields
	if len(columns) == 0 {
		columns = managedpackage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mpq.sql != nil {
		selector = mpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mpq.ctx.Unique != nil && *mpq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range mpq.modifiers {
		m(selector)
	}
	for _, p := range mpq.predicates {
		p(selector)
	}
	for _, p := range mpq.order {
		p(selector)
	}
	if offset := mpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (mpq *ManagedPackageQuery) Modify(modifiers ...func(s *sql.Selector)) *ManagedPackageSelect {
	mpq.modifiers = append(mpq.modifiers, modifiers...)
	return mpq.Select()
}

// ManagedPackageGroupBy is the group-by builder for ManagedPackage entities.
type ManagedPackageGroupBy struct {
	selector
	build *ManagedPackageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mpgb *ManagedPackageGroupBy) Aggregate(fns ...AggregateFunc) *ManagedPackageGroupBy {
	mpgb.fns = append(mpgb.fns, fns...)
	return mpgb
}

// Scan applies the selector query and scans the result into the given value.
func (mpgb *ManagedPackageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mpgb.build.ctx, ent.OpQueryGroupBy)
	if err := mpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ManagedPackageQuery, *ManagedPackageGroupBy](ctx, mpgb.build, mpgb, mpgb.build.inters, v)
}

func (mpgb *ManagedPackageGroupBy) sqlScan(ctx context.Context, root *ManagedPackageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mpgb.fns))
	for _, fn := range mpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mpgb.flds)+len(mpgb.fns))
		for _, f := range *mpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ManagedPackageSelect is the builder for selecting fields of ManagedPackage entities.
type ManagedPackageSelect struct {
	*ManagedPackageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mps *ManagedPackageSelect) Aggregate(fns ...AggregateFunc) *ManagedPackageSelect {
	mps.fns = append(mps.fns, fns...)
	return mps
}

// Scan applies the selector query and scans the result into the given value.
func (mps *ManagedPackageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mps.ctx, ent.OpQuerySelect)
	if err := mps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ManagedPackageQuery, *ManagedPackageSelect](ctx, mps.ManagedPackageQuery, mps, mps.inters, v)
}

func (mps *ManagedPackageSelect) sqlScan(ctx context.Context, root *ManagedPackageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mps.fns))
	for _, fn := range mps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (mps *ManagedPackageSelect) Modify(modifiers ...func(s *sql.Selector)) *ManagedPackageSelect {
	mps.modifiers = append(mps.modifiers, modifiers...)
	return mps
}
