// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/EigerCode/ent/managedpackage"
	"github.com/EigerCode/ent/softwarecatalog"
	"github.com/EigerCode/ent/softwareinstalllog"
	"github.com/EigerCode/ent/softwarerepo"
	"github.com/EigerCode/ent/tenant"
)

// ManagedPackageCreate is the builder for creating a ManagedPackage entity.
type ManagedPackageCreate struct {
	config
	mutation *ManagedPackageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (mpc *ManagedPackageCreate) SetName(s string) *ManagedPackageCreate {
	mpc.mutation.SetName(s)
	return mpc
}

// SetDisplayName sets the "display_name" field.
func (mpc *ManagedPackageCreate) SetDisplayName(s string) *ManagedPackageCreate {
	mpc.mutation.SetDisplayName(s)
	return mpc
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableDisplayName(s *string) *ManagedPackageCreate {
	if s != nil {
		mpc.SetDisplayName(*s)
	}
	return mpc
}

// SetVersion sets the "version" field.
func (mpc *ManagedPackageCreate) SetVersion(s string) *ManagedPackageCreate {
	mpc.mutation.SetVersion(s)
	return mpc
}

// SetPlatform sets the "platform" field.
func (mpc *ManagedPackageCreate) SetPlatform(m managedpackage.Platform) *ManagedPackageCreate {
	mpc.mutation.SetPlatform(m)
	return mpc
}

// SetInstallerPath sets the "installer_path" field.
func (mpc *ManagedPackageCreate) SetInstallerPath(s string) *ManagedPackageCreate {
	mpc.mutation.SetInstallerPath(s)
	return mpc
}

// SetChecksumSha256 sets the "checksum_sha256" field.
func (mpc *ManagedPackageCreate) SetChecksumSha256(s string) *ManagedPackageCreate {
	mpc.mutation.SetChecksumSha256(s)
	return mpc
}

// SetNillableChecksumSha256 sets the "checksum_sha256" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableChecksumSha256(s *string) *ManagedPackageCreate {
	if s != nil {
		mpc.SetChecksumSha256(*s)
	}
	return mpc
}

// SetSizeBytes sets the "size_bytes" field.
func (mpc *ManagedPackageCreate) SetSizeBytes(i int64) *ManagedPackageCreate {
	mpc.mutation.SetSizeBytes(i)
	return mpc
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableSizeBytes(i *int64) *ManagedPackageCreate {
	if i != nil {
		mpc.SetSizeBytes(*i)
	}
	return mpc
}

// SetIconName sets the "icon_name" field.
func (mpc *ManagedPackageCreate) SetIconName(s string) *ManagedPackageCreate {
	mpc.mutation.SetIconName(s)
	return mpc
}

// SetNillableIconName sets the "icon_name" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableIconName(s *string) *ManagedPackageCreate {
	if s != nil {
		mpc.SetIconName(*s)
	}
	return mpc
}

// SetDescription sets the "description" field.
func (mpc *ManagedPackageCreate) SetDescription(s string) *ManagedPackageCreate {
	mpc.mutation.SetDescription(s)
	return mpc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableDescription(s *string) *ManagedPackageCreate {
	if s != nil {
		mpc.SetDescription(*s)
	}
	return mpc
}

// SetCategory sets the "category" field.
func (mpc *ManagedPackageCreate) SetCategory(s string) *ManagedPackageCreate {
	mpc.mutation.SetCategory(s)
	return mpc
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableCategory(s *string) *ManagedPackageCreate {
	if s != nil {
		mpc.SetCategory(*s)
	}
	return mpc
}

// SetDeveloper sets the "developer" field.
func (mpc *ManagedPackageCreate) SetDeveloper(s string) *ManagedPackageCreate {
	mpc.mutation.SetDeveloper(s)
	return mpc
}

// SetNillableDeveloper sets the "developer" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableDeveloper(s *string) *ManagedPackageCreate {
	if s != nil {
		mpc.SetDeveloper(*s)
	}
	return mpc
}

// SetPkginfoData sets the "pkginfo_data" field.
func (mpc *ManagedPackageCreate) SetPkginfoData(s string) *ManagedPackageCreate {
	mpc.mutation.SetPkginfoData(s)
	return mpc
}

// SetNillablePkginfoData sets the "pkginfo_data" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillablePkginfoData(s *string) *ManagedPackageCreate {
	if s != nil {
		mpc.SetPkginfoData(*s)
	}
	return mpc
}

// SetPreInstallScript sets the "pre_install_script" field.
func (mpc *ManagedPackageCreate) SetPreInstallScript(s string) *ManagedPackageCreate {
	mpc.mutation.SetPreInstallScript(s)
	return mpc
}

// SetNillablePreInstallScript sets the "pre_install_script" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillablePreInstallScript(s *string) *ManagedPackageCreate {
	if s != nil {
		mpc.SetPreInstallScript(*s)
	}
	return mpc
}

// SetPostInstallScript sets the "post_install_script" field.
func (mpc *ManagedPackageCreate) SetPostInstallScript(s string) *ManagedPackageCreate {
	mpc.mutation.SetPostInstallScript(s)
	return mpc
}

// SetNillablePostInstallScript sets the "post_install_script" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillablePostInstallScript(s *string) *ManagedPackageCreate {
	if s != nil {
		mpc.SetPostInstallScript(*s)
	}
	return mpc
}

// SetUninstallMethod sets the "uninstall_method" field.
func (mpc *ManagedPackageCreate) SetUninstallMethod(s string) *ManagedPackageCreate {
	mpc.mutation.SetUninstallMethod(s)
	return mpc
}

// SetNillableUninstallMethod sets the "uninstall_method" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableUninstallMethod(s *string) *ManagedPackageCreate {
	if s != nil {
		mpc.SetUninstallMethod(*s)
	}
	return mpc
}

// SetInstallsItems sets the "installs_items" field.
func (mpc *ManagedPackageCreate) SetInstallsItems(s string) *ManagedPackageCreate {
	mpc.mutation.SetInstallsItems(s)
	return mpc
}

// SetNillableInstallsItems sets the "installs_items" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableInstallsItems(s *string) *ManagedPackageCreate {
	if s != nil {
		mpc.SetInstallsItems(*s)
	}
	return mpc
}

// SetReceipts sets the "receipts" field.
func (mpc *ManagedPackageCreate) SetReceipts(s string) *ManagedPackageCreate {
	mpc.mutation.SetReceipts(s)
	return mpc
}

// SetNillableReceipts sets the "receipts" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableReceipts(s *string) *ManagedPackageCreate {
	if s != nil {
		mpc.SetReceipts(*s)
	}
	return mpc
}

// SetBlockingApps sets the "blocking_apps" field.
func (mpc *ManagedPackageCreate) SetBlockingApps(s string) *ManagedPackageCreate {
	mpc.mutation.SetBlockingApps(s)
	return mpc
}

// SetNillableBlockingApps sets the "blocking_apps" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableBlockingApps(s *string) *ManagedPackageCreate {
	if s != nil {
		mpc.SetBlockingApps(*s)
	}
	return mpc
}

// SetRestartAction sets the "restart_action" field.
func (mpc *ManagedPackageCreate) SetRestartAction(ma managedpackage.RestartAction) *ManagedPackageCreate {
	mpc.mutation.SetRestartAction(ma)
	return mpc
}

// SetNillableRestartAction sets the "restart_action" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableRestartAction(ma *managedpackage.RestartAction) *ManagedPackageCreate {
	if ma != nil {
		mpc.SetRestartAction(*ma)
	}
	return mpc
}

// SetMinOsVersion sets the "min_os_version" field.
func (mpc *ManagedPackageCreate) SetMinOsVersion(s string) *ManagedPackageCreate {
	mpc.mutation.SetMinOsVersion(s)
	return mpc
}

// SetNillableMinOsVersion sets the "min_os_version" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableMinOsVersion(s *string) *ManagedPackageCreate {
	if s != nil {
		mpc.SetMinOsVersion(*s)
	}
	return mpc
}

// SetMaxOsVersion sets the "max_os_version" field.
func (mpc *ManagedPackageCreate) SetMaxOsVersion(s string) *ManagedPackageCreate {
	mpc.mutation.SetMaxOsVersion(s)
	return mpc
}

// SetNillableMaxOsVersion sets the "max_os_version" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableMaxOsVersion(s *string) *ManagedPackageCreate {
	if s != nil {
		mpc.SetMaxOsVersion(*s)
	}
	return mpc
}

// SetSupportedArchitectures sets the "supported_architectures" field.
func (mpc *ManagedPackageCreate) SetSupportedArchitectures(s string) *ManagedPackageCreate {
	mpc.mutation.SetSupportedArchitectures(s)
	return mpc
}

// SetNillableSupportedArchitectures sets the "supported_architectures" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableSupportedArchitectures(s *string) *ManagedPackageCreate {
	if s != nil {
		mpc.SetSupportedArchitectures(*s)
	}
	return mpc
}

// SetForceInstallDate sets the "force_install_date" field.
func (mpc *ManagedPackageCreate) SetForceInstallDate(t time.Time) *ManagedPackageCreate {
	mpc.mutation.SetForceInstallDate(t)
	return mpc
}

// SetNillableForceInstallDate sets the "force_install_date" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableForceInstallDate(t *time.Time) *ManagedPackageCreate {
	if t != nil {
		mpc.SetForceInstallDate(*t)
	}
	return mpc
}

// SetUnattendedInstall sets the "unattended_install" field.
func (mpc *ManagedPackageCreate) SetUnattendedInstall(b bool) *ManagedPackageCreate {
	mpc.mutation.SetUnattendedInstall(b)
	return mpc
}

// SetNillableUnattendedInstall sets the "unattended_install" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableUnattendedInstall(b *bool) *ManagedPackageCreate {
	if b != nil {
		mpc.SetUnattendedInstall(*b)
	}
	return mpc
}

// SetUnattendedUninstall sets the "unattended_uninstall" field.
func (mpc *ManagedPackageCreate) SetUnattendedUninstall(b bool) *ManagedPackageCreate {
	mpc.mutation.SetUnattendedUninstall(b)
	return mpc
}

// SetNillableUnattendedUninstall sets the "unattended_uninstall" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableUnattendedUninstall(b *bool) *ManagedPackageCreate {
	if b != nil {
		mpc.SetUnattendedUninstall(*b)
	}
	return mpc
}

// SetStatus sets the "status" field.
func (mpc *ManagedPackageCreate) SetStatus(m managedpackage.Status) *ManagedPackageCreate {
	mpc.mutation.SetStatus(m)
	return mpc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableStatus(m *managedpackage.Status) *ManagedPackageCreate {
	if m != nil {
		mpc.SetStatus(*m)
	}
	return mpc
}

// SetSource sets the "source" field.
func (mpc *ManagedPackageCreate) SetSource(m managedpackage.Source) *ManagedPackageCreate {
	mpc.mutation.SetSource(m)
	return mpc
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableSource(m *managedpackage.Source) *ManagedPackageCreate {
	if m != nil {
		mpc.SetSource(*m)
	}
	return mpc
}

// SetCreated sets the "created" field.
func (mpc *ManagedPackageCreate) SetCreated(t time.Time) *ManagedPackageCreate {
	mpc.mutation.SetCreated(t)
	return mpc
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableCreated(t *time.Time) *ManagedPackageCreate {
	if t != nil {
		mpc.SetCreated(*t)
	}
	return mpc
}

// SetModified sets the "modified" field.
func (mpc *ManagedPackageCreate) SetModified(t time.Time) *ManagedPackageCreate {
	mpc.mutation.SetModified(t)
	return mpc
}

// SetNillableModified sets the "modified" field if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableModified(t *time.Time) *ManagedPackageCreate {
	if t != nil {
		mpc.SetModified(*t)
	}
	return mpc
}

// SetRepoID sets the "repo" edge to the SoftwareRepo entity by ID.
func (mpc *ManagedPackageCreate) SetRepoID(id int) *ManagedPackageCreate {
	mpc.mutation.SetRepoID(id)
	return mpc
}

// SetNillableRepoID sets the "repo" edge to the SoftwareRepo entity by ID if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableRepoID(id *int) *ManagedPackageCreate {
	if id != nil {
		mpc = mpc.SetRepoID(*id)
	}
	return mpc
}

// SetRepo sets the "repo" edge to the SoftwareRepo entity.
func (mpc *ManagedPackageCreate) SetRepo(s *SoftwareRepo) *ManagedPackageCreate {
	return mpc.SetRepoID(s.ID)
}

// AddCatalogIDs adds the "catalogs" edge to the SoftwareCatalog entity by IDs.
func (mpc *ManagedPackageCreate) AddCatalogIDs(ids ...int) *ManagedPackageCreate {
	mpc.mutation.AddCatalogIDs(ids...)
	return mpc
}

// AddCatalogs adds the "catalogs" edges to the SoftwareCatalog entity.
func (mpc *ManagedPackageCreate) AddCatalogs(s ...*SoftwareCatalog) *ManagedPackageCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return mpc.AddCatalogIDs(ids...)
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (mpc *ManagedPackageCreate) SetTenantID(id int) *ManagedPackageCreate {
	mpc.mutation.SetTenantID(id)
	return mpc
}

// SetNillableTenantID sets the "tenant" edge to the Tenant entity by ID if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableTenantID(id *int) *ManagedPackageCreate {
	if id != nil {
		mpc = mpc.SetTenantID(*id)
	}
	return mpc
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (mpc *ManagedPackageCreate) SetTenant(t *Tenant) *ManagedPackageCreate {
	return mpc.SetTenantID(t.ID)
}

// AddInstallLogIDs adds the "install_logs" edge to the SoftwareInstallLog entity by IDs.
func (mpc *ManagedPackageCreate) AddInstallLogIDs(ids ...int) *ManagedPackageCreate {
	mpc.mutation.AddInstallLogIDs(ids...)
	return mpc
}

// AddInstallLogs adds the "install_logs" edges to the SoftwareInstallLog entity.
func (mpc *ManagedPackageCreate) AddInstallLogs(s ...*SoftwareInstallLog) *ManagedPackageCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return mpc.AddInstallLogIDs(ids...)
}

// AddRequireIDs adds the "requires" edge to the ManagedPackage entity by IDs.
func (mpc *ManagedPackageCreate) AddRequireIDs(ids ...int) *ManagedPackageCreate {
	mpc.mutation.AddRequireIDs(ids...)
	return mpc
}

// AddRequires adds the "requires" edges to the ManagedPackage entity.
func (mpc *ManagedPackageCreate) AddRequires(m ...*ManagedPackage) *ManagedPackageCreate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mpc.AddRequireIDs(ids...)
}

// AddUpdateForIDs adds the "update_for" edge to the ManagedPackage entity by IDs.
func (mpc *ManagedPackageCreate) AddUpdateForIDs(ids ...int) *ManagedPackageCreate {
	mpc.mutation.AddUpdateForIDs(ids...)
	return mpc
}

// AddUpdateFor adds the "update_for" edges to the ManagedPackage entity.
func (mpc *ManagedPackageCreate) AddUpdateFor(m ...*ManagedPackage) *ManagedPackageCreate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mpc.AddUpdateForIDs(ids...)
}

// SetGlobalRefID sets the "global_ref" edge to the ManagedPackage entity by ID.
func (mpc *ManagedPackageCreate) SetGlobalRefID(id int) *ManagedPackageCreate {
	mpc.mutation.SetGlobalRefID(id)
	return mpc
}

// SetNillableGlobalRefID sets the "global_ref" edge to the ManagedPackage entity by ID if the given value is not nil.
func (mpc *ManagedPackageCreate) SetNillableGlobalRefID(id *int) *ManagedPackageCreate {
	if id != nil {
		mpc = mpc.SetGlobalRefID(*id)
	}
	return mpc
}

// SetGlobalRef sets the "global_ref" edge to the ManagedPackage entity.
func (mpc *ManagedPackageCreate) SetGlobalRef(m *ManagedPackage) *ManagedPackageCreate {
	return mpc.SetGlobalRefID(m.ID)
}

// AddSubscriberIDs adds the "subscribers" edge to the ManagedPackage entity by IDs.
func (mpc *ManagedPackageCreate) AddSubscriberIDs(ids ...int) *ManagedPackageCreate {
	mpc.mutation.AddSubscriberIDs(ids...)
	return mpc
}

// AddSubscribers adds the "subscribers" edges to the ManagedPackage entity.
func (mpc *ManagedPackageCreate) AddSubscribers(m ...*ManagedPackage) *ManagedPackageCreate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mpc.AddSubscriberIDs(ids...)
}

// Mutation returns the ManagedPackageMutation object of the builder.
func (mpc *ManagedPackageCreate) Mutation() *ManagedPackageMutation {
	return mpc.mutation
}

// Save creates the ManagedPackage in the database.
func (mpc *ManagedPackageCreate) Save(ctx context.Context) (*ManagedPackage, error) {
	mpc.defaults()
	return withHooks(ctx, mpc.sqlSave, mpc.mutation, mpc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mpc *ManagedPackageCreate) SaveX(ctx context.Context) *ManagedPackage {
	v, err := mpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mpc *ManagedPackageCreate) Exec(ctx context.Context) error {
	_, err := mpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpc *ManagedPackageCreate) ExecX(ctx context.Context) {
	if err := mpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mpc *ManagedPackageCreate) defaults() {
	if _, ok := mpc.mutation.DisplayName(); !ok {
		v := managedpackage.DefaultDisplayName
		mpc.mutation.SetDisplayName(v)
	}
	if _, ok := mpc.mutation.ChecksumSha256(); !ok {
		v := managedpackage.DefaultChecksumSha256
		mpc.mutation.SetChecksumSha256(v)
	}
	if _, ok := mpc.mutation.SizeBytes(); !ok {
		v := managedpackage.DefaultSizeBytes
		mpc.mutation.SetSizeBytes(v)
	}
	if _, ok := mpc.mutation.IconName(); !ok {
		v := managedpackage.DefaultIconName
		mpc.mutation.SetIconName(v)
	}
	if _, ok := mpc.mutation.Description(); !ok {
		v := managedpackage.DefaultDescription
		mpc.mutation.SetDescription(v)
	}
	if _, ok := mpc.mutation.Category(); !ok {
		v := managedpackage.DefaultCategory
		mpc.mutation.SetCategory(v)
	}
	if _, ok := mpc.mutation.Developer(); !ok {
		v := managedpackage.DefaultDeveloper
		mpc.mutation.SetDeveloper(v)
	}
	if _, ok := mpc.mutation.PkginfoData(); !ok {
		v := managedpackage.DefaultPkginfoData
		mpc.mutation.SetPkginfoData(v)
	}
	if _, ok := mpc.mutation.PreInstallScript(); !ok {
		v := managedpackage.DefaultPreInstallScript
		mpc.mutation.SetPreInstallScript(v)
	}
	if _, ok := mpc.mutation.PostInstallScript(); !ok {
		v := managedpackage.DefaultPostInstallScript
		mpc.mutation.SetPostInstallScript(v)
	}
	if _, ok := mpc.mutation.UninstallMethod(); !ok {
		v := managedpackage.DefaultUninstallMethod
		mpc.mutation.SetUninstallMethod(v)
	}
	if _, ok := mpc.mutation.InstallsItems(); !ok {
		v := managedpackage.DefaultInstallsItems
		mpc.mutation.SetInstallsItems(v)
	}
	if _, ok := mpc.mutation.Receipts(); !ok {
		v := managedpackage.DefaultReceipts
		mpc.mutation.SetReceipts(v)
	}
	if _, ok := mpc.mutation.BlockingApps(); !ok {
		v := managedpackage.DefaultBlockingApps
		mpc.mutation.SetBlockingApps(v)
	}
	if _, ok := mpc.mutation.RestartAction(); !ok {
		v := managedpackage.DefaultRestartAction
		mpc.mutation.SetRestartAction(v)
	}
	if _, ok := mpc.mutation.MinOsVersion(); !ok {
		v := managedpackage.DefaultMinOsVersion
		mpc.mutation.SetMinOsVersion(v)
	}
	if _, ok := mpc.mutation.MaxOsVersion(); !ok {
		v := managedpackage.DefaultMaxOsVersion
		mpc.mutation.SetMaxOsVersion(v)
	}
	if _, ok := mpc.mutation.SupportedArchitectures(); !ok {
		v := managedpackage.DefaultSupportedArchitectures
		mpc.mutation.SetSupportedArchitectures(v)
	}
	if _, ok := mpc.mutation.UnattendedInstall(); !ok {
		v := managedpackage.DefaultUnattendedInstall
		mpc.mutation.SetUnattendedInstall(v)
	}
	if _, ok := mpc.mutation.UnattendedUninstall(); !ok {
		v := managedpackage.DefaultUnattendedUninstall
		mpc.mutation.SetUnattendedUninstall(v)
	}
	if _, ok := mpc.mutation.Status(); !ok {
		v := managedpackage.DefaultStatus
		mpc.mutation.SetStatus(v)
	}
	if _, ok := mpc.mutation.Source(); !ok {
		v := managedpackage.DefaultSource
		mpc.mutation.SetSource(v)
	}
	if _, ok := mpc.mutation.Created(); !ok {
		v := managedpackage.DefaultCreated()
		mpc.mutation.SetCreated(v)
	}
	if _, ok := mpc.mutation.Modified(); !ok {
		v := managedpackage.DefaultModified()
		mpc.mutation.SetModified(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mpc *ManagedPackageCreate) check() error {
	if _, ok := mpc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ManagedPackage.name"`)}
	}
	if v, ok := mpc.mutation.Name(); ok {
		if err := managedpackage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ManagedPackage.name": %w`, err)}
		}
	}
	if _, ok := mpc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ManagedPackage.version"`)}
	}
	if v, ok := mpc.mutation.Version(); ok {
		if err := managedpackage.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ManagedPackage.version": %w`, err)}
		}
	}
	if _, ok := mpc.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "ManagedPackage.platform"`)}
	}
	if v, ok := mpc.mutation.Platform(); ok {
		if err := managedpackage.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ManagedPackage.platform": %w`, err)}
		}
	}
	if _, ok := mpc.mutation.InstallerPath(); !ok {
		return &ValidationError{Name: "installer_path", err: errors.New(`ent: missing required field "ManagedPackage.installer_path"`)}
	}
	if v, ok := mpc.mutation.InstallerPath(); ok {
		if err := managedpackage.InstallerPathValidator(v); err != nil {
			return &ValidationError{Name: "installer_path", err: fmt.Errorf(`ent: validator failed for field "ManagedPackage.installer_path": %w`, err)}
		}
	}
	if v, ok := mpc.mutation.RestartAction(); ok {
		if err := managedpackage.RestartActionValidator(v); err != nil {
			return &ValidationError{Name: "restart_action", err: fmt.Errorf(`ent: validator failed for field "ManagedPackage.restart_action": %w`, err)}
		}
	}
	if v, ok := mpc.mutation.Status(); ok {
		if err := managedpackage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ManagedPackage.status": %w`, err)}
		}
	}
	if v, ok := mpc.mutation.Source(); ok {
		if err := managedpackage.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ManagedPackage.source": %w`, err)}
		}
	}
	return nil
}

func (mpc *ManagedPackageCreate) sqlSave(ctx context.Context) (*ManagedPackage, error) {
	if err := mpc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mpc.mutation.id = &_node.ID
	mpc.mutation.done = true
	return _node, nil
}

func (mpc *ManagedPackageCreate) createSpec() (*ManagedPackage, *sqlgraph.CreateSpec) {
	var (
		_node = &ManagedPackage{config: mpc.config}
		_spec = sqlgraph.NewCreateSpec(managedpackage.Table, sqlgraph.NewFieldSpec(managedpackage.FieldID, field.TypeInt))
	)
	_spec.OnConflict = mpc.conflict
	if value, ok := mpc.mutation.Name(); ok {
		_spec.SetField(managedpackage.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := mpc.mutation.DisplayName(); ok {
		_spec.SetField(managedpackage.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := mpc.mutation.Version(); ok {
		_spec.SetField(managedpackage.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := mpc.mutation.Platform(); ok {
		_spec.SetField(managedpackage.FieldPlatform, field.TypeEnum, value)
		_node.Platform = value
	}
	if value, ok := mpc.mutation.InstallerPath(); ok {
		_spec.SetField(managedpackage.FieldInstallerPath, field.TypeString, value)
		_node.InstallerPath = value
	}
	if value, ok := mpc.mutation.ChecksumSha256(); ok {
		_spec.SetField(managedpackage.FieldChecksumSha256, field.TypeString, value)
		_node.ChecksumSha256 = value
	}
	if value, ok := mpc.mutation.SizeBytes(); ok {
		_spec.SetField(managedpackage.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := mpc.mutation.IconName(); ok {
		_spec.SetField(managedpackage.FieldIconName, field.TypeString, value)
		_node.IconName = value
	}
	if value, ok := mpc.mutation.Description(); ok {
		_spec.SetField(managedpackage.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := mpc.mutation.Category(); ok {
		_spec.SetField(managedpackage.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := mpc.mutation.Developer(); ok {
		_spec.SetField(managedpackage.FieldDeveloper, field.TypeString, value)
		_node.Developer = value
	}
	if value, ok := mpc.mutation.PkginfoData(); ok {
		_spec.SetField(managedpackage.FieldPkginfoData, field.TypeString, value)
		_node.PkginfoData = value
	}
	if value, ok := mpc.mutation.PreInstallScript(); ok {
		_spec.SetField(managedpackage.FieldPreInstallScript, field.TypeString, value)
		_node.PreInstallScript = value
	}
	if value, ok := mpc.mutation.PostInstallScript(); ok {
		_spec.SetField(managedpackage.FieldPostInstallScript, field.TypeString, value)
		_node.PostInstallScript = value
	}
	if value, ok := mpc.mutation.UninstallMethod(); ok {
		_spec.SetField(managedpackage.FieldUninstallMethod, field.TypeString, value)
		_node.UninstallMethod = value
	}
	if value, ok := mpc.mutation.InstallsItems(); ok {
		_spec.SetField(managedpackage.FieldInstallsItems, field.TypeString, value)
		_node.InstallsItems = value
	}
	if value, ok := mpc.mutation.Receipts(); ok {
		_spec.SetField(managedpackage.FieldReceipts, field.TypeString, value)
		_node.Receipts = value
	}
	if value, ok := mpc.mutation.BlockingApps(); ok {
		_spec.SetField(managedpackage.FieldBlockingApps, field.TypeString, value)
		_node.BlockingApps = value
	}
	if value, ok := mpc.mutation.RestartAction(); ok {
		_spec.SetField(managedpackage.FieldRestartAction, field.TypeEnum, value)
		_node.RestartAction = value
	}
	if value, ok := mpc.mutation.MinOsVersion(); ok {
		_spec.SetField(managedpackage.FieldMinOsVersion, field.TypeString, value)
		_node.MinOsVersion = value
	}
	if value, ok := mpc.mutation.MaxOsVersion(); ok {
		_spec.SetField(managedpackage.FieldMaxOsVersion, field.TypeString, value)
		_node.MaxOsVersion = value
	}
	if value, ok := mpc.mutation.SupportedArchitectures(); ok {
		_spec.SetField(managedpackage.FieldSupportedArchitectures, field.TypeString, value)
		_node.SupportedArchitectures = value
	}
	if value, ok := mpc.mutation.ForceInstallDate(); ok {
		_spec.SetField(managedpackage.FieldForceInstallDate, field.TypeTime, value)
		_node.ForceInstallDate = &value
	}
	if value, ok := mpc.mutation.UnattendedInstall(); ok {
		_spec.SetField(managedpackage.FieldUnattendedInstall, field.TypeBool, value)
		_node.UnattendedInstall = value
	}
	if value, ok := mpc.mutation.UnattendedUninstall(); ok {
		_spec.SetField(managedpackage.FieldUnattendedUninstall, field.TypeBool, value)
		_node.UnattendedUninstall = value
	}
	if value, ok := mpc.mutation.Status(); ok {
		_spec.SetField(managedpackage.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := mpc.mutation.Source(); ok {
		_spec.SetField(managedpackage.FieldSource, field.TypeEnum, value)
		_node.Source = value
	}
	if value, ok := mpc.mutation.Created(); ok {
		_spec.SetField(managedpackage.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := mpc.mutation.Modified(); ok {
		_spec.SetField(managedpackage.FieldModified, field.TypeTime, value)
		_node.Modified = value
	}
	if nodes := mpc.mutation.RepoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   managedpackage.RepoTable,
			Columns: []string{managedpackage.RepoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(softwarerepo.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.software_repo_packages = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mpc.mutation.CatalogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   managedpackage.CatalogsTable,
			Columns: managedpackage.CatalogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(softwarecatalog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mpc.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   managedpackage.TenantTable,
			Columns: []string{managedpackage.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tenant_software_packages = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mpc.mutation.InstallLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   managedpackage.InstallLogsTable,
			Columns: []string{managedpackage.InstallLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(softwareinstalllog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mpc.mutation.RequiresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   managedpackage.RequiresTable,
			Columns: managedpackage.RequiresPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(managedpackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mpc.mutation.UpdateForIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   managedpackage.UpdateForTable,
			Columns: managedpackage.UpdateForPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(managedpackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mpc.mutation.GlobalRefIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   managedpackage.GlobalRefTable,
			Columns: []string{managedpackage.GlobalRefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(managedpackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.managed_package_subscribers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mpc.mutation.SubscribersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   managedpackage.SubscribersTable,
			Columns: []string{managedpackage.SubscribersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(managedpackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ManagedPackage.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ManagedPackageUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (mpc *ManagedPackageCreate) OnConflict(opts ...sql.ConflictOption) *ManagedPackageUpsertOne {
	mpc.conflict = opts
	return &ManagedPackageUpsertOne{
		create: mpc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ManagedPackage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mpc *ManagedPackageCreate) OnConflictColumns(columns ...string) *ManagedPackageUpsertOne {
	mpc.conflict = append(mpc.conflict, sql.ConflictColumns(columns...))
	return &ManagedPackageUpsertOne{
		create: mpc,
	}
}

type (
	// ManagedPackageUpsertOne is the builder for "upsert"-ing
	//  one ManagedPackage node.
	ManagedPackageUpsertOne struct {
		create *ManagedPackageCreate
	}

	// ManagedPackageUpsert is the "OnConflict" setter.
	ManagedPackageUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *ManagedPackageUpsert) SetName(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateName() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldName)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *ManagedPackageUpsert) SetDisplayName(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateDisplayName() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldDisplayName)
	return u
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *ManagedPackageUpsert) ClearDisplayName() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldDisplayName)
	return u
}

// SetVersion sets the "version" field.
func (u *ManagedPackageUpsert) SetVersion(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateVersion() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldVersion)
	return u
}

// SetPlatform sets the "platform" field.
func (u *ManagedPackageUpsert) SetPlatform(v managedpackage.Platform) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdatePlatform() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldPlatform)
	return u
}

// SetInstallerPath sets the "installer_path" field.
func (u *ManagedPackageUpsert) SetInstallerPath(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldInstallerPath, v)
	return u
}

// UpdateInstallerPath sets the "installer_path" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateInstallerPath() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldInstallerPath)
	return u
}

// SetChecksumSha256 sets the "checksum_sha256" field.
func (u *ManagedPackageUpsert) SetChecksumSha256(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldChecksumSha256, v)
	return u
}

// UpdateChecksumSha256 sets the "checksum_sha256" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateChecksumSha256() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldChecksumSha256)
	return u
}

// ClearChecksumSha256 clears the value of the "checksum_sha256" field.
func (u *ManagedPackageUpsert) ClearChecksumSha256() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldChecksumSha256)
	return u
}

// SetSizeBytes sets the "size_bytes" field.
func (u *ManagedPackageUpsert) SetSizeBytes(v int64) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldSizeBytes, v)
	return u
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateSizeBytes() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldSizeBytes)
	return u
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *ManagedPackageUpsert) AddSizeBytes(v int64) *ManagedPackageUpsert {
	u.Add(managedpackage.FieldSizeBytes, v)
	return u
}

// ClearSizeBytes clears the value of the "size_bytes" field.
func (u *ManagedPackageUpsert) ClearSizeBytes() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldSizeBytes)
	return u
}

// SetIconName sets the "icon_name" field.
func (u *ManagedPackageUpsert) SetIconName(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldIconName, v)
	return u
}

// UpdateIconName sets the "icon_name" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateIconName() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldIconName)
	return u
}

// ClearIconName clears the value of the "icon_name" field.
func (u *ManagedPackageUpsert) ClearIconName() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldIconName)
	return u
}

// SetDescription sets the "description" field.
func (u *ManagedPackageUpsert) SetDescription(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateDescription() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *ManagedPackageUpsert) ClearDescription() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldDescription)
	return u
}

// SetCategory sets the "category" field.
func (u *ManagedPackageUpsert) SetCategory(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateCategory() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldCategory)
	return u
}

// ClearCategory clears the value of the "category" field.
func (u *ManagedPackageUpsert) ClearCategory() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldCategory)
	return u
}

// SetDeveloper sets the "developer" field.
func (u *ManagedPackageUpsert) SetDeveloper(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldDeveloper, v)
	return u
}

// UpdateDeveloper sets the "developer" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateDeveloper() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldDeveloper)
	return u
}

// ClearDeveloper clears the value of the "developer" field.
func (u *ManagedPackageUpsert) ClearDeveloper() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldDeveloper)
	return u
}

// SetPkginfoData sets the "pkginfo_data" field.
func (u *ManagedPackageUpsert) SetPkginfoData(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldPkginfoData, v)
	return u
}

// UpdatePkginfoData sets the "pkginfo_data" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdatePkginfoData() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldPkginfoData)
	return u
}

// ClearPkginfoData clears the value of the "pkginfo_data" field.
func (u *ManagedPackageUpsert) ClearPkginfoData() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldPkginfoData)
	return u
}

// SetPreInstallScript sets the "pre_install_script" field.
func (u *ManagedPackageUpsert) SetPreInstallScript(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldPreInstallScript, v)
	return u
}

// UpdatePreInstallScript sets the "pre_install_script" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdatePreInstallScript() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldPreInstallScript)
	return u
}

// ClearPreInstallScript clears the value of the "pre_install_script" field.
func (u *ManagedPackageUpsert) ClearPreInstallScript() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldPreInstallScript)
	return u
}

// SetPostInstallScript sets the "post_install_script" field.
func (u *ManagedPackageUpsert) SetPostInstallScript(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldPostInstallScript, v)
	return u
}

// UpdatePostInstallScript sets the "post_install_script" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdatePostInstallScript() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldPostInstallScript)
	return u
}

// ClearPostInstallScript clears the value of the "post_install_script" field.
func (u *ManagedPackageUpsert) ClearPostInstallScript() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldPostInstallScript)
	return u
}

// SetUninstallMethod sets the "uninstall_method" field.
func (u *ManagedPackageUpsert) SetUninstallMethod(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldUninstallMethod, v)
	return u
}

// UpdateUninstallMethod sets the "uninstall_method" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateUninstallMethod() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldUninstallMethod)
	return u
}

// ClearUninstallMethod clears the value of the "uninstall_method" field.
func (u *ManagedPackageUpsert) ClearUninstallMethod() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldUninstallMethod)
	return u
}

// SetInstallsItems sets the "installs_items" field.
func (u *ManagedPackageUpsert) SetInstallsItems(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldInstallsItems, v)
	return u
}

// UpdateInstallsItems sets the "installs_items" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateInstallsItems() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldInstallsItems)
	return u
}

// ClearInstallsItems clears the value of the "installs_items" field.
func (u *ManagedPackageUpsert) ClearInstallsItems() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldInstallsItems)
	return u
}

// SetReceipts sets the "receipts" field.
func (u *ManagedPackageUpsert) SetReceipts(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldReceipts, v)
	return u
}

// UpdateReceipts sets the "receipts" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateReceipts() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldReceipts)
	return u
}

// ClearReceipts clears the value of the "receipts" field.
func (u *ManagedPackageUpsert) ClearReceipts() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldReceipts)
	return u
}

// SetBlockingApps sets the "blocking_apps" field.
func (u *ManagedPackageUpsert) SetBlockingApps(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldBlockingApps, v)
	return u
}

// UpdateBlockingApps sets the "blocking_apps" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateBlockingApps() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldBlockingApps)
	return u
}

// ClearBlockingApps clears the value of the "blocking_apps" field.
func (u *ManagedPackageUpsert) ClearBlockingApps() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldBlockingApps)
	return u
}

// SetRestartAction sets the "restart_action" field.
func (u *ManagedPackageUpsert) SetRestartAction(v managedpackage.RestartAction) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldRestartAction, v)
	return u
}

// UpdateRestartAction sets the "restart_action" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateRestartAction() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldRestartAction)
	return u
}

// ClearRestartAction clears the value of the "restart_action" field.
func (u *ManagedPackageUpsert) ClearRestartAction() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldRestartAction)
	return u
}

// SetMinOsVersion sets the "min_os_version" field.
func (u *ManagedPackageUpsert) SetMinOsVersion(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldMinOsVersion, v)
	return u
}

// UpdateMinOsVersion sets the "min_os_version" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateMinOsVersion() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldMinOsVersion)
	return u
}

// ClearMinOsVersion clears the value of the "min_os_version" field.
func (u *ManagedPackageUpsert) ClearMinOsVersion() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldMinOsVersion)
	return u
}

// SetMaxOsVersion sets the "max_os_version" field.
func (u *ManagedPackageUpsert) SetMaxOsVersion(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldMaxOsVersion, v)
	return u
}

// UpdateMaxOsVersion sets the "max_os_version" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateMaxOsVersion() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldMaxOsVersion)
	return u
}

// ClearMaxOsVersion clears the value of the "max_os_version" field.
func (u *ManagedPackageUpsert) ClearMaxOsVersion() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldMaxOsVersion)
	return u
}

// SetSupportedArchitectures sets the "supported_architectures" field.
func (u *ManagedPackageUpsert) SetSupportedArchitectures(v string) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldSupportedArchitectures, v)
	return u
}

// UpdateSupportedArchitectures sets the "supported_architectures" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateSupportedArchitectures() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldSupportedArchitectures)
	return u
}

// ClearSupportedArchitectures clears the value of the "supported_architectures" field.
func (u *ManagedPackageUpsert) ClearSupportedArchitectures() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldSupportedArchitectures)
	return u
}

// SetForceInstallDate sets the "force_install_date" field.
func (u *ManagedPackageUpsert) SetForceInstallDate(v time.Time) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldForceInstallDate, v)
	return u
}

// UpdateForceInstallDate sets the "force_install_date" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateForceInstallDate() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldForceInstallDate)
	return u
}

// ClearForceInstallDate clears the value of the "force_install_date" field.
func (u *ManagedPackageUpsert) ClearForceInstallDate() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldForceInstallDate)
	return u
}

// SetUnattendedInstall sets the "unattended_install" field.
func (u *ManagedPackageUpsert) SetUnattendedInstall(v bool) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldUnattendedInstall, v)
	return u
}

// UpdateUnattendedInstall sets the "unattended_install" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateUnattendedInstall() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldUnattendedInstall)
	return u
}

// ClearUnattendedInstall clears the value of the "unattended_install" field.
func (u *ManagedPackageUpsert) ClearUnattendedInstall() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldUnattendedInstall)
	return u
}

// SetUnattendedUninstall sets the "unattended_uninstall" field.
func (u *ManagedPackageUpsert) SetUnattendedUninstall(v bool) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldUnattendedUninstall, v)
	return u
}

// UpdateUnattendedUninstall sets the "unattended_uninstall" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateUnattendedUninstall() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldUnattendedUninstall)
	return u
}

// ClearUnattendedUninstall clears the value of the "unattended_uninstall" field.
func (u *ManagedPackageUpsert) ClearUnattendedUninstall() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldUnattendedUninstall)
	return u
}

// SetStatus sets the "status" field.
func (u *ManagedPackageUpsert) SetStatus(v managedpackage.Status) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateStatus() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldStatus)
	return u
}

// ClearStatus clears the value of the "status" field.
func (u *ManagedPackageUpsert) ClearStatus() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldStatus)
	return u
}

// SetSource sets the "source" field.
func (u *ManagedPackageUpsert) SetSource(v managedpackage.Source) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateSource() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldSource)
	return u
}

// ClearSource clears the value of the "source" field.
func (u *ManagedPackageUpsert) ClearSource() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldSource)
	return u
}

// SetCreated sets the "created" field.
func (u *ManagedPackageUpsert) SetCreated(v time.Time) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldCreated, v)
	return u
}

// UpdateCreated sets the "created" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateCreated() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldCreated)
	return u
}

// ClearCreated clears the value of the "created" field.
func (u *ManagedPackageUpsert) ClearCreated() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldCreated)
	return u
}

// SetModified sets the "modified" field.
func (u *ManagedPackageUpsert) SetModified(v time.Time) *ManagedPackageUpsert {
	u.Set(managedpackage.FieldModified, v)
	return u
}

// UpdateModified sets the "modified" field to the value that was provided on create.
func (u *ManagedPackageUpsert) UpdateModified() *ManagedPackageUpsert {
	u.SetExcluded(managedpackage.FieldModified)
	return u
}

// ClearModified clears the value of the "modified" field.
func (u *ManagedPackageUpsert) ClearModified() *ManagedPackageUpsert {
	u.SetNull(managedpackage.FieldModified)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ManagedPackage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ManagedPackageUpsertOne) UpdateNewValues() *ManagedPackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ManagedPackage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ManagedPackageUpsertOne) Ignore() *ManagedPackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ManagedPackageUpsertOne) DoNothing() *ManagedPackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ManagedPackageCreate.OnConflict
// documentation for more info.
func (u *ManagedPackageUpsertOne) Update(set func(*ManagedPackageUpsert)) *ManagedPackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ManagedPackageUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ManagedPackageUpsertOne) SetName(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateName() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateName()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *ManagedPackageUpsertOne) SetDisplayName(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateDisplayName() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateDisplayName()
	})
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *ManagedPackageUpsertOne) ClearDisplayName() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearDisplayName()
	})
}

// SetVersion sets the "version" field.
func (u *ManagedPackageUpsertOne) SetVersion(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateVersion() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateVersion()
	})
}

// SetPlatform sets the "platform" field.
func (u *ManagedPackageUpsertOne) SetPlatform(v managedpackage.Platform) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdatePlatform() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdatePlatform()
	})
}

// SetInstallerPath sets the "installer_path" field.
func (u *ManagedPackageUpsertOne) SetInstallerPath(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetInstallerPath(v)
	})
}

// UpdateInstallerPath sets the "installer_path" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateInstallerPath() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateInstallerPath()
	})
}

// SetChecksumSha256 sets the "checksum_sha256" field.
func (u *ManagedPackageUpsertOne) SetChecksumSha256(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetChecksumSha256(v)
	})
}

// UpdateChecksumSha256 sets the "checksum_sha256" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateChecksumSha256() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateChecksumSha256()
	})
}

// ClearChecksumSha256 clears the value of the "checksum_sha256" field.
func (u *ManagedPackageUpsertOne) ClearChecksumSha256() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearChecksumSha256()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *ManagedPackageUpsertOne) SetSizeBytes(v int64) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *ManagedPackageUpsertOne) AddSizeBytes(v int64) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateSizeBytes() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateSizeBytes()
	})
}

// ClearSizeBytes clears the value of the "size_bytes" field.
func (u *ManagedPackageUpsertOne) ClearSizeBytes() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearSizeBytes()
	})
}

// SetIconName sets the "icon_name" field.
func (u *ManagedPackageUpsertOne) SetIconName(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetIconName(v)
	})
}

// UpdateIconName sets the "icon_name" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateIconName() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateIconName()
	})
}

// ClearIconName clears the value of the "icon_name" field.
func (u *ManagedPackageUpsertOne) ClearIconName() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearIconName()
	})
}

// SetDescription sets the "description" field.
func (u *ManagedPackageUpsertOne) SetDescription(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateDescription() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ManagedPackageUpsertOne) ClearDescription() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearDescription()
	})
}

// SetCategory sets the "category" field.
func (u *ManagedPackageUpsertOne) SetCategory(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateCategory() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateCategory()
	})
}

// ClearCategory clears the value of the "category" field.
func (u *ManagedPackageUpsertOne) ClearCategory() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearCategory()
	})
}

// SetDeveloper sets the "developer" field.
func (u *ManagedPackageUpsertOne) SetDeveloper(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetDeveloper(v)
	})
}

// UpdateDeveloper sets the "developer" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateDeveloper() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateDeveloper()
	})
}

// ClearDeveloper clears the value of the "developer" field.
func (u *ManagedPackageUpsertOne) ClearDeveloper() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearDeveloper()
	})
}

// SetPkginfoData sets the "pkginfo_data" field.
func (u *ManagedPackageUpsertOne) SetPkginfoData(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetPkginfoData(v)
	})
}

// UpdatePkginfoData sets the "pkginfo_data" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdatePkginfoData() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdatePkginfoData()
	})
}

// ClearPkginfoData clears the value of the "pkginfo_data" field.
func (u *ManagedPackageUpsertOne) ClearPkginfoData() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearPkginfoData()
	})
}

// SetPreInstallScript sets the "pre_install_script" field.
func (u *ManagedPackageUpsertOne) SetPreInstallScript(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetPreInstallScript(v)
	})
}

// UpdatePreInstallScript sets the "pre_install_script" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdatePreInstallScript() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdatePreInstallScript()
	})
}

// ClearPreInstallScript clears the value of the "pre_install_script" field.
func (u *ManagedPackageUpsertOne) ClearPreInstallScript() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearPreInstallScript()
	})
}

// SetPostInstallScript sets the "post_install_script" field.
func (u *ManagedPackageUpsertOne) SetPostInstallScript(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetPostInstallScript(v)
	})
}

// UpdatePostInstallScript sets the "post_install_script" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdatePostInstallScript() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdatePostInstallScript()
	})
}

// ClearPostInstallScript clears the value of the "post_install_script" field.
func (u *ManagedPackageUpsertOne) ClearPostInstallScript() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearPostInstallScript()
	})
}

// SetUninstallMethod sets the "uninstall_method" field.
func (u *ManagedPackageUpsertOne) SetUninstallMethod(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetUninstallMethod(v)
	})
}

// UpdateUninstallMethod sets the "uninstall_method" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateUninstallMethod() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateUninstallMethod()
	})
}

// ClearUninstallMethod clears the value of the "uninstall_method" field.
func (u *ManagedPackageUpsertOne) ClearUninstallMethod() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearUninstallMethod()
	})
}

// SetInstallsItems sets the "installs_items" field.
func (u *ManagedPackageUpsertOne) SetInstallsItems(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetInstallsItems(v)
	})
}

// UpdateInstallsItems sets the "installs_items" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateInstallsItems() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateInstallsItems()
	})
}

// ClearInstallsItems clears the value of the "installs_items" field.
func (u *ManagedPackageUpsertOne) ClearInstallsItems() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearInstallsItems()
	})
}

// SetReceipts sets the "receipts" field.
func (u *ManagedPackageUpsertOne) SetReceipts(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetReceipts(v)
	})
}

// UpdateReceipts sets the "receipts" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateReceipts() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateReceipts()
	})
}

// ClearReceipts clears the value of the "receipts" field.
func (u *ManagedPackageUpsertOne) ClearReceipts() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearReceipts()
	})
}

// SetBlockingApps sets the "blocking_apps" field.
func (u *ManagedPackageUpsertOne) SetBlockingApps(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetBlockingApps(v)
	})
}

// UpdateBlockingApps sets the "blocking_apps" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateBlockingApps() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateBlockingApps()
	})
}

// ClearBlockingApps clears the value of the "blocking_apps" field.
func (u *ManagedPackageUpsertOne) ClearBlockingApps() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearBlockingApps()
	})
}

// SetRestartAction sets the "restart_action" field.
func (u *ManagedPackageUpsertOne) SetRestartAction(v managedpackage.RestartAction) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetRestartAction(v)
	})
}

// UpdateRestartAction sets the "restart_action" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateRestartAction() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateRestartAction()
	})
}

// ClearRestartAction clears the value of the "restart_action" field.
func (u *ManagedPackageUpsertOne) ClearRestartAction() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearRestartAction()
	})
}

// SetMinOsVersion sets the "min_os_version" field.
func (u *ManagedPackageUpsertOne) SetMinOsVersion(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetMinOsVersion(v)
	})
}

// UpdateMinOsVersion sets the "min_os_version" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateMinOsVersion() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateMinOsVersion()
	})
}

// ClearMinOsVersion clears the value of the "min_os_version" field.
func (u *ManagedPackageUpsertOne) ClearMinOsVersion() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearMinOsVersion()
	})
}

// SetMaxOsVersion sets the "max_os_version" field.
func (u *ManagedPackageUpsertOne) SetMaxOsVersion(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetMaxOsVersion(v)
	})
}

// UpdateMaxOsVersion sets the "max_os_version" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateMaxOsVersion() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateMaxOsVersion()
	})
}

// ClearMaxOsVersion clears the value of the "max_os_version" field.
func (u *ManagedPackageUpsertOne) ClearMaxOsVersion() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearMaxOsVersion()
	})
}

// SetSupportedArchitectures sets the "supported_architectures" field.
func (u *ManagedPackageUpsertOne) SetSupportedArchitectures(v string) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetSupportedArchitectures(v)
	})
}

// UpdateSupportedArchitectures sets the "supported_architectures" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateSupportedArchitectures() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateSupportedArchitectures()
	})
}

// ClearSupportedArchitectures clears the value of the "supported_architectures" field.
func (u *ManagedPackageUpsertOne) ClearSupportedArchitectures() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearSupportedArchitectures()
	})
}

// SetForceInstallDate sets the "force_install_date" field.
func (u *ManagedPackageUpsertOne) SetForceInstallDate(v time.Time) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetForceInstallDate(v)
	})
}

// UpdateForceInstallDate sets the "force_install_date" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateForceInstallDate() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateForceInstallDate()
	})
}

// ClearForceInstallDate clears the value of the "force_install_date" field.
func (u *ManagedPackageUpsertOne) ClearForceInstallDate() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearForceInstallDate()
	})
}

// SetUnattendedInstall sets the "unattended_install" field.
func (u *ManagedPackageUpsertOne) SetUnattendedInstall(v bool) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetUnattendedInstall(v)
	})
}

// UpdateUnattendedInstall sets the "unattended_install" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateUnattendedInstall() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateUnattendedInstall()
	})
}

// ClearUnattendedInstall clears the value of the "unattended_install" field.
func (u *ManagedPackageUpsertOne) ClearUnattendedInstall() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearUnattendedInstall()
	})
}

// SetUnattendedUninstall sets the "unattended_uninstall" field.
func (u *ManagedPackageUpsertOne) SetUnattendedUninstall(v bool) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetUnattendedUninstall(v)
	})
}

// UpdateUnattendedUninstall sets the "unattended_uninstall" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateUnattendedUninstall() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateUnattendedUninstall()
	})
}

// ClearUnattendedUninstall clears the value of the "unattended_uninstall" field.
func (u *ManagedPackageUpsertOne) ClearUnattendedUninstall() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearUnattendedUninstall()
	})
}

// SetStatus sets the "status" field.
func (u *ManagedPackageUpsertOne) SetStatus(v managedpackage.Status) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateStatus() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *ManagedPackageUpsertOne) ClearStatus() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearStatus()
	})
}

// SetSource sets the "source" field.
func (u *ManagedPackageUpsertOne) SetSource(v managedpackage.Source) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateSource() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateSource()
	})
}

// ClearSource clears the value of the "source" field.
func (u *ManagedPackageUpsertOne) ClearSource() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearSource()
	})
}

// SetCreated sets the "created" field.
func (u *ManagedPackageUpsertOne) SetCreated(v time.Time) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetCreated(v)
	})
}

// UpdateCreated sets the "created" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateCreated() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateCreated()
	})
}

// ClearCreated clears the value of the "created" field.
func (u *ManagedPackageUpsertOne) ClearCreated() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearCreated()
	})
}

// SetModified sets the "modified" field.
func (u *ManagedPackageUpsertOne) SetModified(v time.Time) *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetModified(v)
	})
}

// UpdateModified sets the "modified" field to the value that was provided on create.
func (u *ManagedPackageUpsertOne) UpdateModified() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateModified()
	})
}

// ClearModified clears the value of the "modified" field.
func (u *ManagedPackageUpsertOne) ClearModified() *ManagedPackageUpsertOne {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearModified()
	})
}

// Exec executes the query.
func (u *ManagedPackageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ManagedPackageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ManagedPackageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ManagedPackageUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ManagedPackageUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ManagedPackageCreateBulk is the builder for creating many ManagedPackage entities in bulk.
type ManagedPackageCreateBulk struct {
	config
	err      error
	builders []*ManagedPackageCreate
	conflict []sql.ConflictOption
}

// Save creates the ManagedPackage entities in the database.
func (mpcb *ManagedPackageCreateBulk) Save(ctx context.Context) ([]*ManagedPackage, error) {
	if mpcb.err != nil {
		return nil, mpcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mpcb.builders))
	nodes := make([]*ManagedPackage, len(mpcb.builders))
	mutators := make([]Mutator, len(mpcb.builders))
	for i := range mpcb.builders {
		func(i int, root context.Context) {
			builder := mpcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ManagedPackageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = mpcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mpcb *ManagedPackageCreateBulk) SaveX(ctx context.Context) []*ManagedPackage {
	v, err := mpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mpcb *ManagedPackageCreateBulk) Exec(ctx context.Context) error {
	_, err := mpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpcb *ManagedPackageCreateBulk) ExecX(ctx context.Context) {
	if err := mpcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ManagedPackage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ManagedPackageUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (mpcb *ManagedPackageCreateBulk) OnConflict(opts ...sql.ConflictOption) *ManagedPackageUpsertBulk {
	mpcb.conflict = opts
	return &ManagedPackageUpsertBulk{
		create: mpcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ManagedPackage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mpcb *ManagedPackageCreateBulk) OnConflictColumns(columns ...string) *ManagedPackageUpsertBulk {
	mpcb.conflict = append(mpcb.conflict, sql.ConflictColumns(columns...))
	return &ManagedPackageUpsertBulk{
		create: mpcb,
	}
}

// ManagedPackageUpsertBulk is the builder for "upsert"-ing
// a bulk of ManagedPackage nodes.
type ManagedPackageUpsertBulk struct {
	create *ManagedPackageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ManagedPackage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ManagedPackageUpsertBulk) UpdateNewValues() *ManagedPackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ManagedPackage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ManagedPackageUpsertBulk) Ignore() *ManagedPackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ManagedPackageUpsertBulk) DoNothing() *ManagedPackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ManagedPackageCreateBulk.OnConflict
// documentation for more info.
func (u *ManagedPackageUpsertBulk) Update(set func(*ManagedPackageUpsert)) *ManagedPackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ManagedPackageUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ManagedPackageUpsertBulk) SetName(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateName() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateName()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *ManagedPackageUpsertBulk) SetDisplayName(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateDisplayName() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateDisplayName()
	})
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *ManagedPackageUpsertBulk) ClearDisplayName() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearDisplayName()
	})
}

// SetVersion sets the "version" field.
func (u *ManagedPackageUpsertBulk) SetVersion(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateVersion() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateVersion()
	})
}

// SetPlatform sets the "platform" field.
func (u *ManagedPackageUpsertBulk) SetPlatform(v managedpackage.Platform) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdatePlatform() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdatePlatform()
	})
}

// SetInstallerPath sets the "installer_path" field.
func (u *ManagedPackageUpsertBulk) SetInstallerPath(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetInstallerPath(v)
	})
}

// UpdateInstallerPath sets the "installer_path" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateInstallerPath() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateInstallerPath()
	})
}

// SetChecksumSha256 sets the "checksum_sha256" field.
func (u *ManagedPackageUpsertBulk) SetChecksumSha256(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetChecksumSha256(v)
	})
}

// UpdateChecksumSha256 sets the "checksum_sha256" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateChecksumSha256() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateChecksumSha256()
	})
}

// ClearChecksumSha256 clears the value of the "checksum_sha256" field.
func (u *ManagedPackageUpsertBulk) ClearChecksumSha256() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearChecksumSha256()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *ManagedPackageUpsertBulk) SetSizeBytes(v int64) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *ManagedPackageUpsertBulk) AddSizeBytes(v int64) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateSizeBytes() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateSizeBytes()
	})
}

// ClearSizeBytes clears the value of the "size_bytes" field.
func (u *ManagedPackageUpsertBulk) ClearSizeBytes() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearSizeBytes()
	})
}

// SetIconName sets the "icon_name" field.
func (u *ManagedPackageUpsertBulk) SetIconName(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetIconName(v)
	})
}

// UpdateIconName sets the "icon_name" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateIconName() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateIconName()
	})
}

// ClearIconName clears the value of the "icon_name" field.
func (u *ManagedPackageUpsertBulk) ClearIconName() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearIconName()
	})
}

// SetDescription sets the "description" field.
func (u *ManagedPackageUpsertBulk) SetDescription(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateDescription() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ManagedPackageUpsertBulk) ClearDescription() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearDescription()
	})
}

// SetCategory sets the "category" field.
func (u *ManagedPackageUpsertBulk) SetCategory(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateCategory() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateCategory()
	})
}

// ClearCategory clears the value of the "category" field.
func (u *ManagedPackageUpsertBulk) ClearCategory() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearCategory()
	})
}

// SetDeveloper sets the "developer" field.
func (u *ManagedPackageUpsertBulk) SetDeveloper(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetDeveloper(v)
	})
}

// UpdateDeveloper sets the "developer" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateDeveloper() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateDeveloper()
	})
}

// ClearDeveloper clears the value of the "developer" field.
func (u *ManagedPackageUpsertBulk) ClearDeveloper() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearDeveloper()
	})
}

// SetPkginfoData sets the "pkginfo_data" field.
func (u *ManagedPackageUpsertBulk) SetPkginfoData(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetPkginfoData(v)
	})
}

// UpdatePkginfoData sets the "pkginfo_data" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdatePkginfoData() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdatePkginfoData()
	})
}

// ClearPkginfoData clears the value of the "pkginfo_data" field.
func (u *ManagedPackageUpsertBulk) ClearPkginfoData() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearPkginfoData()
	})
}

// SetPreInstallScript sets the "pre_install_script" field.
func (u *ManagedPackageUpsertBulk) SetPreInstallScript(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetPreInstallScript(v)
	})
}

// UpdatePreInstallScript sets the "pre_install_script" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdatePreInstallScript() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdatePreInstallScript()
	})
}

// ClearPreInstallScript clears the value of the "pre_install_script" field.
func (u *ManagedPackageUpsertBulk) ClearPreInstallScript() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearPreInstallScript()
	})
}

// SetPostInstallScript sets the "post_install_script" field.
func (u *ManagedPackageUpsertBulk) SetPostInstallScript(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetPostInstallScript(v)
	})
}

// UpdatePostInstallScript sets the "post_install_script" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdatePostInstallScript() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdatePostInstallScript()
	})
}

// ClearPostInstallScript clears the value of the "post_install_script" field.
func (u *ManagedPackageUpsertBulk) ClearPostInstallScript() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearPostInstallScript()
	})
}

// SetUninstallMethod sets the "uninstall_method" field.
func (u *ManagedPackageUpsertBulk) SetUninstallMethod(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetUninstallMethod(v)
	})
}

// UpdateUninstallMethod sets the "uninstall_method" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateUninstallMethod() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateUninstallMethod()
	})
}

// ClearUninstallMethod clears the value of the "uninstall_method" field.
func (u *ManagedPackageUpsertBulk) ClearUninstallMethod() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearUninstallMethod()
	})
}

// SetInstallsItems sets the "installs_items" field.
func (u *ManagedPackageUpsertBulk) SetInstallsItems(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetInstallsItems(v)
	})
}

// UpdateInstallsItems sets the "installs_items" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateInstallsItems() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateInstallsItems()
	})
}

// ClearInstallsItems clears the value of the "installs_items" field.
func (u *ManagedPackageUpsertBulk) ClearInstallsItems() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearInstallsItems()
	})
}

// SetReceipts sets the "receipts" field.
func (u *ManagedPackageUpsertBulk) SetReceipts(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetReceipts(v)
	})
}

// UpdateReceipts sets the "receipts" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateReceipts() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateReceipts()
	})
}

// ClearReceipts clears the value of the "receipts" field.
func (u *ManagedPackageUpsertBulk) ClearReceipts() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearReceipts()
	})
}

// SetBlockingApps sets the "blocking_apps" field.
func (u *ManagedPackageUpsertBulk) SetBlockingApps(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetBlockingApps(v)
	})
}

// UpdateBlockingApps sets the "blocking_apps" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateBlockingApps() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateBlockingApps()
	})
}

// ClearBlockingApps clears the value of the "blocking_apps" field.
func (u *ManagedPackageUpsertBulk) ClearBlockingApps() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearBlockingApps()
	})
}

// SetRestartAction sets the "restart_action" field.
func (u *ManagedPackageUpsertBulk) SetRestartAction(v managedpackage.RestartAction) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetRestartAction(v)
	})
}

// UpdateRestartAction sets the "restart_action" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateRestartAction() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateRestartAction()
	})
}

// ClearRestartAction clears the value of the "restart_action" field.
func (u *ManagedPackageUpsertBulk) ClearRestartAction() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearRestartAction()
	})
}

// SetMinOsVersion sets the "min_os_version" field.
func (u *ManagedPackageUpsertBulk) SetMinOsVersion(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetMinOsVersion(v)
	})
}

// UpdateMinOsVersion sets the "min_os_version" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateMinOsVersion() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateMinOsVersion()
	})
}

// ClearMinOsVersion clears the value of the "min_os_version" field.
func (u *ManagedPackageUpsertBulk) ClearMinOsVersion() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearMinOsVersion()
	})
}

// SetMaxOsVersion sets the "max_os_version" field.
func (u *ManagedPackageUpsertBulk) SetMaxOsVersion(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetMaxOsVersion(v)
	})
}

// UpdateMaxOsVersion sets the "max_os_version" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateMaxOsVersion() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateMaxOsVersion()
	})
}

// ClearMaxOsVersion clears the value of the "max_os_version" field.
func (u *ManagedPackageUpsertBulk) ClearMaxOsVersion() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearMaxOsVersion()
	})
}

// SetSupportedArchitectures sets the "supported_architectures" field.
func (u *ManagedPackageUpsertBulk) SetSupportedArchitectures(v string) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetSupportedArchitectures(v)
	})
}

// UpdateSupportedArchitectures sets the "supported_architectures" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateSupportedArchitectures() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateSupportedArchitectures()
	})
}

// ClearSupportedArchitectures clears the value of the "supported_architectures" field.
func (u *ManagedPackageUpsertBulk) ClearSupportedArchitectures() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearSupportedArchitectures()
	})
}

// SetForceInstallDate sets the "force_install_date" field.
func (u *ManagedPackageUpsertBulk) SetForceInstallDate(v time.Time) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetForceInstallDate(v)
	})
}

// UpdateForceInstallDate sets the "force_install_date" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateForceInstallDate() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateForceInstallDate()
	})
}

// ClearForceInstallDate clears the value of the "force_install_date" field.
func (u *ManagedPackageUpsertBulk) ClearForceInstallDate() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearForceInstallDate()
	})
}

// SetUnattendedInstall sets the "unattended_install" field.
func (u *ManagedPackageUpsertBulk) SetUnattendedInstall(v bool) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetUnattendedInstall(v)
	})
}

// UpdateUnattendedInstall sets the "unattended_install" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateUnattendedInstall() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateUnattendedInstall()
	})
}

// ClearUnattendedInstall clears the value of the "unattended_install" field.
func (u *ManagedPackageUpsertBulk) ClearUnattendedInstall() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearUnattendedInstall()
	})
}

// SetUnattendedUninstall sets the "unattended_uninstall" field.
func (u *ManagedPackageUpsertBulk) SetUnattendedUninstall(v bool) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetUnattendedUninstall(v)
	})
}

// UpdateUnattendedUninstall sets the "unattended_uninstall" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateUnattendedUninstall() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateUnattendedUninstall()
	})
}

// ClearUnattendedUninstall clears the value of the "unattended_uninstall" field.
func (u *ManagedPackageUpsertBulk) ClearUnattendedUninstall() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearUnattendedUninstall()
	})
}

// SetStatus sets the "status" field.
func (u *ManagedPackageUpsertBulk) SetStatus(v managedpackage.Status) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateStatus() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *ManagedPackageUpsertBulk) ClearStatus() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearStatus()
	})
}

// SetSource sets the "source" field.
func (u *ManagedPackageUpsertBulk) SetSource(v managedpackage.Source) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateSource() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateSource()
	})
}

// ClearSource clears the value of the "source" field.
func (u *ManagedPackageUpsertBulk) ClearSource() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearSource()
	})
}

// SetCreated sets the "created" field.
func (u *ManagedPackageUpsertBulk) SetCreated(v time.Time) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetCreated(v)
	})
}

// UpdateCreated sets the "created" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateCreated() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateCreated()
	})
}

// ClearCreated clears the value of the "created" field.
func (u *ManagedPackageUpsertBulk) ClearCreated() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearCreated()
	})
}

// SetModified sets the "modified" field.
func (u *ManagedPackageUpsertBulk) SetModified(v time.Time) *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.SetModified(v)
	})
}

// UpdateModified sets the "modified" field to the value that was provided on create.
func (u *ManagedPackageUpsertBulk) UpdateModified() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.UpdateModified()
	})
}

// ClearModified clears the value of the "modified" field.
func (u *ManagedPackageUpsertBulk) ClearModified() *ManagedPackageUpsertBulk {
	return u.Update(func(s *ManagedPackageUpsert) {
		s.ClearModified()
	})
}

// Exec executes the query.
func (u *ManagedPackageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ManagedPackageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ManagedPackageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ManagedPackageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
