// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/agent"
	"github.com/open-uem/ent/nanohubinfo"
	"github.com/open-uem/ent/predicate"
)

// NanoHubInfoQuery is the builder for querying NanoHubInfo entities.
type NanoHubInfoQuery struct {
	config
	ctx        *QueryContext
	order      []nanohubinfo.OrderOption
	inters     []Interceptor
	predicates []predicate.NanoHubInfo
	withOwner  *AgentQuery
	withFKs    bool
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NanoHubInfoQuery builder.
func (nhiq *NanoHubInfoQuery) Where(ps ...predicate.NanoHubInfo) *NanoHubInfoQuery {
	nhiq.predicates = append(nhiq.predicates, ps...)
	return nhiq
}

// Limit the number of records to be returned by this query.
func (nhiq *NanoHubInfoQuery) Limit(limit int) *NanoHubInfoQuery {
	nhiq.ctx.Limit = &limit
	return nhiq
}

// Offset to start from.
func (nhiq *NanoHubInfoQuery) Offset(offset int) *NanoHubInfoQuery {
	nhiq.ctx.Offset = &offset
	return nhiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (nhiq *NanoHubInfoQuery) Unique(unique bool) *NanoHubInfoQuery {
	nhiq.ctx.Unique = &unique
	return nhiq
}

// Order specifies how the records should be ordered.
func (nhiq *NanoHubInfoQuery) Order(o ...nanohubinfo.OrderOption) *NanoHubInfoQuery {
	nhiq.order = append(nhiq.order, o...)
	return nhiq
}

// QueryOwner chains the current query on the "owner" edge.
func (nhiq *NanoHubInfoQuery) QueryOwner() *AgentQuery {
	query := (&AgentClient{config: nhiq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := nhiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := nhiq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(nanohubinfo.Table, nanohubinfo.FieldID, selector),
			sqlgraph.To(agent.Table, agent.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, nanohubinfo.OwnerTable, nanohubinfo.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(nhiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first NanoHubInfo entity from the query.
// Returns a *NotFoundError when no NanoHubInfo was found.
func (nhiq *NanoHubInfoQuery) First(ctx context.Context) (*NanoHubInfo, error) {
	nodes, err := nhiq.Limit(1).All(setContextOp(ctx, nhiq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{nanohubinfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (nhiq *NanoHubInfoQuery) FirstX(ctx context.Context) *NanoHubInfo {
	node, err := nhiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NanoHubInfo ID from the query.
// Returns a *NotFoundError when no NanoHubInfo ID was found.
func (nhiq *NanoHubInfoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nhiq.Limit(1).IDs(setContextOp(ctx, nhiq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{nanohubinfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (nhiq *NanoHubInfoQuery) FirstIDX(ctx context.Context) int {
	id, err := nhiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NanoHubInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NanoHubInfo entity is found.
// Returns a *NotFoundError when no NanoHubInfo entities are found.
func (nhiq *NanoHubInfoQuery) Only(ctx context.Context) (*NanoHubInfo, error) {
	nodes, err := nhiq.Limit(2).All(setContextOp(ctx, nhiq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{nanohubinfo.Label}
	default:
		return nil, &NotSingularError{nanohubinfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (nhiq *NanoHubInfoQuery) OnlyX(ctx context.Context) *NanoHubInfo {
	node, err := nhiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NanoHubInfo ID in the query.
// Returns a *NotSingularError when more than one NanoHubInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (nhiq *NanoHubInfoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nhiq.Limit(2).IDs(setContextOp(ctx, nhiq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{nanohubinfo.Label}
	default:
		err = &NotSingularError{nanohubinfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (nhiq *NanoHubInfoQuery) OnlyIDX(ctx context.Context) int {
	id, err := nhiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NanoHubInfos.
func (nhiq *NanoHubInfoQuery) All(ctx context.Context) ([]*NanoHubInfo, error) {
	ctx = setContextOp(ctx, nhiq.ctx, ent.OpQueryAll)
	if err := nhiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*NanoHubInfo, *NanoHubInfoQuery]()
	return withInterceptors[[]*NanoHubInfo](ctx, nhiq, qr, nhiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (nhiq *NanoHubInfoQuery) AllX(ctx context.Context) []*NanoHubInfo {
	nodes, err := nhiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NanoHubInfo IDs.
func (nhiq *NanoHubInfoQuery) IDs(ctx context.Context) (ids []int, err error) {
	if nhiq.ctx.Unique == nil && nhiq.path != nil {
		nhiq.Unique(true)
	}
	ctx = setContextOp(ctx, nhiq.ctx, ent.OpQueryIDs)
	if err = nhiq.Select(nanohubinfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (nhiq *NanoHubInfoQuery) IDsX(ctx context.Context) []int {
	ids, err := nhiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (nhiq *NanoHubInfoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, nhiq.ctx, ent.OpQueryCount)
	if err := nhiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, nhiq, querierCount[*NanoHubInfoQuery](), nhiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (nhiq *NanoHubInfoQuery) CountX(ctx context.Context) int {
	count, err := nhiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (nhiq *NanoHubInfoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, nhiq.ctx, ent.OpQueryExist)
	switch _, err := nhiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (nhiq *NanoHubInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := nhiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NanoHubInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (nhiq *NanoHubInfoQuery) Clone() *NanoHubInfoQuery {
	if nhiq == nil {
		return nil
	}
	return &NanoHubInfoQuery{
		config:     nhiq.config,
		ctx:        nhiq.ctx.Clone(),
		order:      append([]nanohubinfo.OrderOption{}, nhiq.order...),
		inters:     append([]Interceptor{}, nhiq.inters...),
		predicates: append([]predicate.NanoHubInfo{}, nhiq.predicates...),
		withOwner:  nhiq.withOwner.Clone(),
		// clone intermediate query.
		sql:       nhiq.sql.Clone(),
		path:      nhiq.path,
		modifiers: append([]func(*sql.Selector){}, nhiq.modifiers...),
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (nhiq *NanoHubInfoQuery) WithOwner(opts ...func(*AgentQuery)) *NanoHubInfoQuery {
	query := (&AgentClient{config: nhiq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	nhiq.withOwner = query
	return nhiq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AvailableDeviceCapacity float64 `json:"available_device_capacity,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NanoHubInfo.Query().
//		GroupBy(nanohubinfo.FieldAvailableDeviceCapacity).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (nhiq *NanoHubInfoQuery) GroupBy(field string, fields ...string) *NanoHubInfoGroupBy {
	nhiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NanoHubInfoGroupBy{build: nhiq}
	grbuild.flds = &nhiq.ctx.Fields
	grbuild.label = nanohubinfo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AvailableDeviceCapacity float64 `json:"available_device_capacity,omitempty"`
//	}
//
//	client.NanoHubInfo.Query().
//		Select(nanohubinfo.FieldAvailableDeviceCapacity).
//		Scan(ctx, &v)
func (nhiq *NanoHubInfoQuery) Select(fields ...string) *NanoHubInfoSelect {
	nhiq.ctx.Fields = append(nhiq.ctx.Fields, fields...)
	sbuild := &NanoHubInfoSelect{NanoHubInfoQuery: nhiq}
	sbuild.label = nanohubinfo.Label
	sbuild.flds, sbuild.scan = &nhiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NanoHubInfoSelect configured with the given aggregations.
func (nhiq *NanoHubInfoQuery) Aggregate(fns ...AggregateFunc) *NanoHubInfoSelect {
	return nhiq.Select().Aggregate(fns...)
}

func (nhiq *NanoHubInfoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range nhiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, nhiq); err != nil {
				return err
			}
		}
	}
	for _, f := range nhiq.ctx.Fields {
		if !nanohubinfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if nhiq.path != nil {
		prev, err := nhiq.path(ctx)
		if err != nil {
			return err
		}
		nhiq.sql = prev
	}
	return nil
}

func (nhiq *NanoHubInfoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NanoHubInfo, error) {
	var (
		nodes       = []*NanoHubInfo{}
		withFKs     = nhiq.withFKs
		_spec       = nhiq.querySpec()
		loadedTypes = [1]bool{
			nhiq.withOwner != nil,
		}
	)
	if nhiq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, nanohubinfo.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*NanoHubInfo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &NanoHubInfo{config: nhiq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(nhiq.modifiers) > 0 {
		_spec.Modifiers = nhiq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, nhiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := nhiq.withOwner; query != nil {
		if err := nhiq.loadOwner(ctx, query, nodes, nil,
			func(n *NanoHubInfo, e *Agent) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (nhiq *NanoHubInfoQuery) loadOwner(ctx context.Context, query *AgentQuery, nodes []*NanoHubInfo, init func(*NanoHubInfo), assign func(*NanoHubInfo, *Agent)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*NanoHubInfo)
	for i := range nodes {
		if nodes[i].agent_nanohubinfo == nil {
			continue
		}
		fk := *nodes[i].agent_nanohubinfo
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(agent.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "agent_nanohubinfo" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (nhiq *NanoHubInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := nhiq.querySpec()
	if len(nhiq.modifiers) > 0 {
		_spec.Modifiers = nhiq.modifiers
	}
	_spec.Node.Columns = nhiq.ctx.Fields
	if len(nhiq.ctx.Fields) > 0 {
		_spec.Unique = nhiq.ctx.Unique != nil && *nhiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, nhiq.driver, _spec)
}

func (nhiq *NanoHubInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(nanohubinfo.Table, nanohubinfo.Columns, sqlgraph.NewFieldSpec(nanohubinfo.FieldID, field.TypeInt))
	_spec.From = nhiq.sql
	if unique := nhiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if nhiq.path != nil {
		_spec.Unique = true
	}
	if fields := nhiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nanohubinfo.FieldID)
		for i := range fields {
			if fields[i] != nanohubinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := nhiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := nhiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := nhiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := nhiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (nhiq *NanoHubInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(nhiq.driver.Dialect())
	t1 := builder.Table(nanohubinfo.Table)
	columns := nhiq.ctx.Fields
	if len(columns) == 0 {
		columns = nanohubinfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if nhiq.sql != nil {
		selector = nhiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if nhiq.ctx.Unique != nil && *nhiq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range nhiq.modifiers {
		m(selector)
	}
	for _, p := range nhiq.predicates {
		p(selector)
	}
	for _, p := range nhiq.order {
		p(selector)
	}
	if offset := nhiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := nhiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (nhiq *NanoHubInfoQuery) Modify(modifiers ...func(s *sql.Selector)) *NanoHubInfoSelect {
	nhiq.modifiers = append(nhiq.modifiers, modifiers...)
	return nhiq.Select()
}

// NanoHubInfoGroupBy is the group-by builder for NanoHubInfo entities.
type NanoHubInfoGroupBy struct {
	selector
	build *NanoHubInfoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (nhigb *NanoHubInfoGroupBy) Aggregate(fns ...AggregateFunc) *NanoHubInfoGroupBy {
	nhigb.fns = append(nhigb.fns, fns...)
	return nhigb
}

// Scan applies the selector query and scans the result into the given value.
func (nhigb *NanoHubInfoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nhigb.build.ctx, ent.OpQueryGroupBy)
	if err := nhigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NanoHubInfoQuery, *NanoHubInfoGroupBy](ctx, nhigb.build, nhigb, nhigb.build.inters, v)
}

func (nhigb *NanoHubInfoGroupBy) sqlScan(ctx context.Context, root *NanoHubInfoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(nhigb.fns))
	for _, fn := range nhigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*nhigb.flds)+len(nhigb.fns))
		for _, f := range *nhigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*nhigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nhigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NanoHubInfoSelect is the builder for selecting fields of NanoHubInfo entities.
type NanoHubInfoSelect struct {
	*NanoHubInfoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (nhis *NanoHubInfoSelect) Aggregate(fns ...AggregateFunc) *NanoHubInfoSelect {
	nhis.fns = append(nhis.fns, fns...)
	return nhis
}

// Scan applies the selector query and scans the result into the given value.
func (nhis *NanoHubInfoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nhis.ctx, ent.OpQuerySelect)
	if err := nhis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NanoHubInfoQuery, *NanoHubInfoSelect](ctx, nhis.NanoHubInfoQuery, nhis, nhis.inters, v)
}

func (nhis *NanoHubInfoSelect) sqlScan(ctx context.Context, root *NanoHubInfoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(nhis.fns))
	for _, fn := range nhis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*nhis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nhis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (nhis *NanoHubInfoSelect) Modify(modifiers ...func(s *sql.Selector)) *NanoHubInfoSelect {
	nhis.modifiers = append(nhis.modifiers, modifiers...)
	return nhis
}
