// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/nanohubsettings"
	"github.com/open-uem/ent/predicate"
)

// NanoHubSettingsQuery is the builder for querying NanoHubSettings entities.
type NanoHubSettingsQuery struct {
	config
	ctx        *QueryContext
	order      []nanohubsettings.OrderOption
	inters     []Interceptor
	predicates []predicate.NanoHubSettings
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NanoHubSettingsQuery builder.
func (nhsq *NanoHubSettingsQuery) Where(ps ...predicate.NanoHubSettings) *NanoHubSettingsQuery {
	nhsq.predicates = append(nhsq.predicates, ps...)
	return nhsq
}

// Limit the number of records to be returned by this query.
func (nhsq *NanoHubSettingsQuery) Limit(limit int) *NanoHubSettingsQuery {
	nhsq.ctx.Limit = &limit
	return nhsq
}

// Offset to start from.
func (nhsq *NanoHubSettingsQuery) Offset(offset int) *NanoHubSettingsQuery {
	nhsq.ctx.Offset = &offset
	return nhsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (nhsq *NanoHubSettingsQuery) Unique(unique bool) *NanoHubSettingsQuery {
	nhsq.ctx.Unique = &unique
	return nhsq
}

// Order specifies how the records should be ordered.
func (nhsq *NanoHubSettingsQuery) Order(o ...nanohubsettings.OrderOption) *NanoHubSettingsQuery {
	nhsq.order = append(nhsq.order, o...)
	return nhsq
}

// First returns the first NanoHubSettings entity from the query.
// Returns a *NotFoundError when no NanoHubSettings was found.
func (nhsq *NanoHubSettingsQuery) First(ctx context.Context) (*NanoHubSettings, error) {
	nodes, err := nhsq.Limit(1).All(setContextOp(ctx, nhsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{nanohubsettings.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (nhsq *NanoHubSettingsQuery) FirstX(ctx context.Context) *NanoHubSettings {
	node, err := nhsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NanoHubSettings ID from the query.
// Returns a *NotFoundError when no NanoHubSettings ID was found.
func (nhsq *NanoHubSettingsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nhsq.Limit(1).IDs(setContextOp(ctx, nhsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{nanohubsettings.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (nhsq *NanoHubSettingsQuery) FirstIDX(ctx context.Context) int {
	id, err := nhsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NanoHubSettings entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NanoHubSettings entity is found.
// Returns a *NotFoundError when no NanoHubSettings entities are found.
func (nhsq *NanoHubSettingsQuery) Only(ctx context.Context) (*NanoHubSettings, error) {
	nodes, err := nhsq.Limit(2).All(setContextOp(ctx, nhsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{nanohubsettings.Label}
	default:
		return nil, &NotSingularError{nanohubsettings.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (nhsq *NanoHubSettingsQuery) OnlyX(ctx context.Context) *NanoHubSettings {
	node, err := nhsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NanoHubSettings ID in the query.
// Returns a *NotSingularError when more than one NanoHubSettings ID is found.
// Returns a *NotFoundError when no entities are found.
func (nhsq *NanoHubSettingsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nhsq.Limit(2).IDs(setContextOp(ctx, nhsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{nanohubsettings.Label}
	default:
		err = &NotSingularError{nanohubsettings.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (nhsq *NanoHubSettingsQuery) OnlyIDX(ctx context.Context) int {
	id, err := nhsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NanoHubSettingsSlice.
func (nhsq *NanoHubSettingsQuery) All(ctx context.Context) ([]*NanoHubSettings, error) {
	ctx = setContextOp(ctx, nhsq.ctx, ent.OpQueryAll)
	if err := nhsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*NanoHubSettings, *NanoHubSettingsQuery]()
	return withInterceptors[[]*NanoHubSettings](ctx, nhsq, qr, nhsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (nhsq *NanoHubSettingsQuery) AllX(ctx context.Context) []*NanoHubSettings {
	nodes, err := nhsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NanoHubSettings IDs.
func (nhsq *NanoHubSettingsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if nhsq.ctx.Unique == nil && nhsq.path != nil {
		nhsq.Unique(true)
	}
	ctx = setContextOp(ctx, nhsq.ctx, ent.OpQueryIDs)
	if err = nhsq.Select(nanohubsettings.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (nhsq *NanoHubSettingsQuery) IDsX(ctx context.Context) []int {
	ids, err := nhsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (nhsq *NanoHubSettingsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, nhsq.ctx, ent.OpQueryCount)
	if err := nhsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, nhsq, querierCount[*NanoHubSettingsQuery](), nhsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (nhsq *NanoHubSettingsQuery) CountX(ctx context.Context) int {
	count, err := nhsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (nhsq *NanoHubSettingsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, nhsq.ctx, ent.OpQueryExist)
	switch _, err := nhsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (nhsq *NanoHubSettingsQuery) ExistX(ctx context.Context) bool {
	exist, err := nhsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NanoHubSettingsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (nhsq *NanoHubSettingsQuery) Clone() *NanoHubSettingsQuery {
	if nhsq == nil {
		return nil
	}
	return &NanoHubSettingsQuery{
		config:     nhsq.config,
		ctx:        nhsq.ctx.Clone(),
		order:      append([]nanohubsettings.OrderOption{}, nhsq.order...),
		inters:     append([]Interceptor{}, nhsq.inters...),
		predicates: append([]predicate.NanoHubSettings{}, nhsq.predicates...),
		// clone intermediate query.
		sql:       nhsq.sql.Clone(),
		path:      nhsq.path,
		modifiers: append([]func(*sql.Selector){}, nhsq.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ServerURL string `json:"server_url,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NanoHubSettings.Query().
//		GroupBy(nanohubsettings.FieldServerURL).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (nhsq *NanoHubSettingsQuery) GroupBy(field string, fields ...string) *NanoHubSettingsGroupBy {
	nhsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NanoHubSettingsGroupBy{build: nhsq}
	grbuild.flds = &nhsq.ctx.Fields
	grbuild.label = nanohubsettings.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ServerURL string `json:"server_url,omitempty"`
//	}
//
//	client.NanoHubSettings.Query().
//		Select(nanohubsettings.FieldServerURL).
//		Scan(ctx, &v)
func (nhsq *NanoHubSettingsQuery) Select(fields ...string) *NanoHubSettingsSelect {
	nhsq.ctx.Fields = append(nhsq.ctx.Fields, fields...)
	sbuild := &NanoHubSettingsSelect{NanoHubSettingsQuery: nhsq}
	sbuild.label = nanohubsettings.Label
	sbuild.flds, sbuild.scan = &nhsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NanoHubSettingsSelect configured with the given aggregations.
func (nhsq *NanoHubSettingsQuery) Aggregate(fns ...AggregateFunc) *NanoHubSettingsSelect {
	return nhsq.Select().Aggregate(fns...)
}

func (nhsq *NanoHubSettingsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range nhsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, nhsq); err != nil {
				return err
			}
		}
	}
	for _, f := range nhsq.ctx.Fields {
		if !nanohubsettings.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if nhsq.path != nil {
		prev, err := nhsq.path(ctx)
		if err != nil {
			return err
		}
		nhsq.sql = prev
	}
	return nil
}

func (nhsq *NanoHubSettingsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NanoHubSettings, error) {
	var (
		nodes = []*NanoHubSettings{}
		_spec = nhsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*NanoHubSettings).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &NanoHubSettings{config: nhsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(nhsq.modifiers) > 0 {
		_spec.Modifiers = nhsq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, nhsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (nhsq *NanoHubSettingsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := nhsq.querySpec()
	if len(nhsq.modifiers) > 0 {
		_spec.Modifiers = nhsq.modifiers
	}
	_spec.Node.Columns = nhsq.ctx.Fields
	if len(nhsq.ctx.Fields) > 0 {
		_spec.Unique = nhsq.ctx.Unique != nil && *nhsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, nhsq.driver, _spec)
}

func (nhsq *NanoHubSettingsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(nanohubsettings.Table, nanohubsettings.Columns, sqlgraph.NewFieldSpec(nanohubsettings.FieldID, field.TypeInt))
	_spec.From = nhsq.sql
	if unique := nhsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if nhsq.path != nil {
		_spec.Unique = true
	}
	if fields := nhsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nanohubsettings.FieldID)
		for i := range fields {
			if fields[i] != nanohubsettings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := nhsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := nhsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := nhsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := nhsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (nhsq *NanoHubSettingsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(nhsq.driver.Dialect())
	t1 := builder.Table(nanohubsettings.Table)
	columns := nhsq.ctx.Fields
	if len(columns) == 0 {
		columns = nanohubsettings.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if nhsq.sql != nil {
		selector = nhsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if nhsq.ctx.Unique != nil && *nhsq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range nhsq.modifiers {
		m(selector)
	}
	for _, p := range nhsq.predicates {
		p(selector)
	}
	for _, p := range nhsq.order {
		p(selector)
	}
	if offset := nhsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := nhsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (nhsq *NanoHubSettingsQuery) Modify(modifiers ...func(s *sql.Selector)) *NanoHubSettingsSelect {
	nhsq.modifiers = append(nhsq.modifiers, modifiers...)
	return nhsq.Select()
}

// NanoHubSettingsGroupBy is the group-by builder for NanoHubSettings entities.
type NanoHubSettingsGroupBy struct {
	selector
	build *NanoHubSettingsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (nhsgb *NanoHubSettingsGroupBy) Aggregate(fns ...AggregateFunc) *NanoHubSettingsGroupBy {
	nhsgb.fns = append(nhsgb.fns, fns...)
	return nhsgb
}

// Scan applies the selector query and scans the result into the given value.
func (nhsgb *NanoHubSettingsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nhsgb.build.ctx, ent.OpQueryGroupBy)
	if err := nhsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NanoHubSettingsQuery, *NanoHubSettingsGroupBy](ctx, nhsgb.build, nhsgb, nhsgb.build.inters, v)
}

func (nhsgb *NanoHubSettingsGroupBy) sqlScan(ctx context.Context, root *NanoHubSettingsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(nhsgb.fns))
	for _, fn := range nhsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*nhsgb.flds)+len(nhsgb.fns))
		for _, f := range *nhsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*nhsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nhsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NanoHubSettingsSelect is the builder for selecting fields of NanoHubSettings entities.
type NanoHubSettingsSelect struct {
	*NanoHubSettingsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (nhss *NanoHubSettingsSelect) Aggregate(fns ...AggregateFunc) *NanoHubSettingsSelect {
	nhss.fns = append(nhss.fns, fns...)
	return nhss
}

// Scan applies the selector query and scans the result into the given value.
func (nhss *NanoHubSettingsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nhss.ctx, ent.OpQuerySelect)
	if err := nhss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NanoHubSettingsQuery, *NanoHubSettingsSelect](ctx, nhss.NanoHubSettingsQuery, nhss, nhss.inters, v)
}

func (nhss *NanoHubSettingsSelect) sqlScan(ctx context.Context, root *NanoHubSettingsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(nhss.fns))
	for _, fn := range nhss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*nhss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nhss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (nhss *NanoHubSettingsSelect) Modify(modifiers ...func(s *sql.Selector)) *NanoHubSettingsSelect {
	nhss.modifiers = append(nhss.modifiers, modifiers...)
	return nhss
}
