// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/nanohubpushcertificate"
	"github.com/open-uem/ent/predicate"
)

// NanoHubPushCertificateDelete is the builder for deleting a NanoHubPushCertificate entity.
type NanoHubPushCertificateDelete struct {
	config
	hooks    []Hook
	mutation *NanoHubPushCertificateMutation
}

// Where appends a list predicates to the NanoHubPushCertificateDelete builder.
func (nhpcd *NanoHubPushCertificateDelete) Where(ps ...predicate.NanoHubPushCertificate) *NanoHubPushCertificateDelete {
	nhpcd.mutation.Where(ps...)
	return nhpcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (nhpcd *NanoHubPushCertificateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, nhpcd.sqlExec, nhpcd.mutation, nhpcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (nhpcd *NanoHubPushCertificateDelete) ExecX(ctx context.Context) int {
	n, err := nhpcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (nhpcd *NanoHubPushCertificateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(nanohubpushcertificate.Table, sqlgraph.NewFieldSpec(nanohubpushcertificate.FieldID, field.TypeInt))
	if ps := nhpcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, nhpcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	nhpcd.mutation.done = true
	return affected, err
}

// NanoHubPushCertificateDeleteOne is the builder for deleting a single NanoHubPushCertificate entity.
type NanoHubPushCertificateDeleteOne struct {
	nhpcd *NanoHubPushCertificateDelete
}

// Where appends a list predicates to the NanoHubPushCertificateDelete builder.
func (nhpcdo *NanoHubPushCertificateDeleteOne) Where(ps ...predicate.NanoHubPushCertificate) *NanoHubPushCertificateDeleteOne {
	nhpcdo.nhpcd.mutation.Where(ps...)
	return nhpcdo
}

// Exec executes the deletion query.
func (nhpcdo *NanoHubPushCertificateDeleteOne) Exec(ctx context.Context) error {
	n, err := nhpcdo.nhpcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{nanohubpushcertificate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (nhpcdo *NanoHubPushCertificateDeleteOne) ExecX(ctx context.Context) {
	if err := nhpcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
