// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/open-uem/ent/softwarepackage"
	"github.com/open-uem/ent/softwarerepo"
	"github.com/open-uem/ent/tenant"
)

// SoftwarePackage is the model entity for the SoftwarePackage schema.
type SoftwarePackage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform softwarepackage.Platform `json:"platform,omitempty"`
	// Path within the S3 bucket, e.g. darwin/Firefox-130.0.pkg
	InstallerPath string `json:"installer_path,omitempty"`
	// ChecksumSha256 holds the value of the "checksum_sha256" field.
	ChecksumSha256 string `json:"checksum_sha256,omitempty"`
	// SizeBytes holds the value of the "size_bytes" field.
	SizeBytes int64 `json:"size_bytes,omitempty"`
	// IconName holds the value of the "icon_name" field.
	IconName string `json:"icon_name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// Developer holds the value of the "developer" field.
	Developer string `json:"developer,omitempty"`
	// Full pkgsinfo as JSON for Munki/CIMIAN compatibility
	PkginfoData string `json:"pkginfo_data,omitempty"`
	// PreInstallScript holds the value of the "pre_install_script" field.
	PreInstallScript string `json:"pre_install_script,omitempty"`
	// PostInstallScript holds the value of the "post_install_script" field.
	PostInstallScript string `json:"post_install_script,omitempty"`
	// UninstallMethod holds the value of the "uninstall_method" field.
	UninstallMethod string `json:"uninstall_method,omitempty"`
	// JSON array of items to check for installation status
	InstallsItems string `json:"installs_items,omitempty"`
	// JSON array of receipts to check
	Receipts string `json:"receipts,omitempty"`
	// JSON array of apps that block installation
	BlockingApps string `json:"blocking_apps,omitempty"`
	// RestartAction holds the value of the "restart_action" field.
	RestartAction softwarepackage.RestartAction `json:"restart_action,omitempty"`
	// MinOsVersion holds the value of the "min_os_version" field.
	MinOsVersion string `json:"min_os_version,omitempty"`
	// MaxOsVersion holds the value of the "max_os_version" field.
	MaxOsVersion string `json:"max_os_version,omitempty"`
	// JSON array, e.g. ["x86_64", "arm64"]
	SupportedArchitectures string `json:"supported_architectures,omitempty"`
	// ForceInstallDate holds the value of the "force_install_date" field.
	ForceInstallDate *time.Time `json:"force_install_date,omitempty"`
	// UnattendedInstall holds the value of the "unattended_install" field.
	UnattendedInstall bool `json:"unattended_install,omitempty"`
	// UnattendedUninstall holds the value of the "unattended_uninstall" field.
	UnattendedUninstall bool `json:"unattended_uninstall,omitempty"`
	// Upload status: uploading = S3 transfer in progress, ready = available, error = upload failed
	Status softwarepackage.Status `json:"status,omitempty"`
	// upload = own package, global = legacy import copy, global_subscription = subscribed to global package
	Source softwarepackage.Source `json:"source,omitempty"`
	// Created holds the value of the "created" field.
	Created time.Time `json:"created,omitempty"`
	// Modified holds the value of the "modified" field.
	Modified time.Time `json:"modified,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SoftwarePackageQuery when eager-loading is set.
	Edges                        SoftwarePackageEdges `json:"edges"`
	software_package_subscribers *int
	software_repo_packages       *int
	tenant_software_packages     *int
	selectValues                 sql.SelectValues
}

// SoftwarePackageEdges holds the relations/edges for other nodes in the graph.
type SoftwarePackageEdges struct {
	// Repo holds the value of the repo edge.
	Repo *SoftwareRepo `json:"repo,omitempty"`
	// Catalogs holds the value of the catalogs edge.
	Catalogs []*SoftwareCatalog `json:"catalogs,omitempty"`
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// InstallLogs holds the value of the install_logs edge.
	InstallLogs []*SoftwareInstallLog `json:"install_logs,omitempty"`
	// Dependencies: packages that must be installed first
	Requires []*SoftwarePackage `json:"requires,omitempty"`
	// This package is an update for the referenced packages
	UpdateFor []*SoftwarePackage `json:"update_for,omitempty"`
	// Reference to the global package this subscription points to
	GlobalRef *SoftwarePackage `json:"global_ref,omitempty"`
	// Subscribers holds the value of the subscribers edge.
	Subscribers []*SoftwarePackage `json:"subscribers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [8]bool
}

// RepoOrErr returns the Repo value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SoftwarePackageEdges) RepoOrErr() (*SoftwareRepo, error) {
	if e.Repo != nil {
		return e.Repo, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: softwarerepo.Label}
	}
	return nil, &NotLoadedError{edge: "repo"}
}

// CatalogsOrErr returns the Catalogs value or an error if the edge
// was not loaded in eager-loading.
func (e SoftwarePackageEdges) CatalogsOrErr() ([]*SoftwareCatalog, error) {
	if e.loadedTypes[1] {
		return e.Catalogs, nil
	}
	return nil, &NotLoadedError{edge: "catalogs"}
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SoftwarePackageEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// InstallLogsOrErr returns the InstallLogs value or an error if the edge
// was not loaded in eager-loading.
func (e SoftwarePackageEdges) InstallLogsOrErr() ([]*SoftwareInstallLog, error) {
	if e.loadedTypes[3] {
		return e.InstallLogs, nil
	}
	return nil, &NotLoadedError{edge: "install_logs"}
}

// RequiresOrErr returns the Requires value or an error if the edge
// was not loaded in eager-loading.
func (e SoftwarePackageEdges) RequiresOrErr() ([]*SoftwarePackage, error) {
	if e.loadedTypes[4] {
		return e.Requires, nil
	}
	return nil, &NotLoadedError{edge: "requires"}
}

// UpdateForOrErr returns the UpdateFor value or an error if the edge
// was not loaded in eager-loading.
func (e SoftwarePackageEdges) UpdateForOrErr() ([]*SoftwarePackage, error) {
	if e.loadedTypes[5] {
		return e.UpdateFor, nil
	}
	return nil, &NotLoadedError{edge: "update_for"}
}

// GlobalRefOrErr returns the GlobalRef value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SoftwarePackageEdges) GlobalRefOrErr() (*SoftwarePackage, error) {
	if e.GlobalRef != nil {
		return e.GlobalRef, nil
	} else if e.loadedTypes[6] {
		return nil, &NotFoundError{label: softwarepackage.Label}
	}
	return nil, &NotLoadedError{edge: "global_ref"}
}

// SubscribersOrErr returns the Subscribers value or an error if the edge
// was not loaded in eager-loading.
func (e SoftwarePackageEdges) SubscribersOrErr() ([]*SoftwarePackage, error) {
	if e.loadedTypes[7] {
		return e.Subscribers, nil
	}
	return nil, &NotLoadedError{edge: "subscribers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SoftwarePackage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case softwarepackage.FieldUnattendedInstall, softwarepackage.FieldUnattendedUninstall:
			values[i] = new(sql.NullBool)
		case softwarepackage.FieldID, softwarepackage.FieldSizeBytes:
			values[i] = new(sql.NullInt64)
		case softwarepackage.FieldName, softwarepackage.FieldDisplayName, softwarepackage.FieldVersion, softwarepackage.FieldPlatform, softwarepackage.FieldInstallerPath, softwarepackage.FieldChecksumSha256, softwarepackage.FieldIconName, softwarepackage.FieldDescription, softwarepackage.FieldCategory, softwarepackage.FieldDeveloper, softwarepackage.FieldPkginfoData, softwarepackage.FieldPreInstallScript, softwarepackage.FieldPostInstallScript, softwarepackage.FieldUninstallMethod, softwarepackage.FieldInstallsItems, softwarepackage.FieldReceipts, softwarepackage.FieldBlockingApps, softwarepackage.FieldRestartAction, softwarepackage.FieldMinOsVersion, softwarepackage.FieldMaxOsVersion, softwarepackage.FieldSupportedArchitectures, softwarepackage.FieldStatus, softwarepackage.FieldSource:
			values[i] = new(sql.NullString)
		case softwarepackage.FieldForceInstallDate, softwarepackage.FieldCreated, softwarepackage.FieldModified:
			values[i] = new(sql.NullTime)
		case softwarepackage.ForeignKeys[0]: // software_package_subscribers
			values[i] = new(sql.NullInt64)
		case softwarepackage.ForeignKeys[1]: // software_repo_packages
			values[i] = new(sql.NullInt64)
		case softwarepackage.ForeignKeys[2]: // tenant_software_packages
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SoftwarePackage fields.
func (sp *SoftwarePackage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case softwarepackage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sp.ID = int(value.Int64)
		case softwarepackage.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				sp.Name = value.String
			}
		case softwarepackage.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				sp.DisplayName = value.String
			}
		case softwarepackage.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				sp.Version = value.String
			}
		case softwarepackage.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				sp.Platform = softwarepackage.Platform(value.String)
			}
		case softwarepackage.FieldInstallerPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field installer_path", values[i])
			} else if value.Valid {
				sp.InstallerPath = value.String
			}
		case softwarepackage.FieldChecksumSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checksum_sha256", values[i])
			} else if value.Valid {
				sp.ChecksumSha256 = value.String
			}
		case softwarepackage.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value.Valid {
				sp.SizeBytes = value.Int64
			}
		case softwarepackage.FieldIconName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon_name", values[i])
			} else if value.Valid {
				sp.IconName = value.String
			}
		case softwarepackage.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				sp.Description = value.String
			}
		case softwarepackage.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				sp.Category = value.String
			}
		case softwarepackage.FieldDeveloper:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field developer", values[i])
			} else if value.Valid {
				sp.Developer = value.String
			}
		case softwarepackage.FieldPkginfoData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pkginfo_data", values[i])
			} else if value.Valid {
				sp.PkginfoData = value.String
			}
		case softwarepackage.FieldPreInstallScript:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pre_install_script", values[i])
			} else if value.Valid {
				sp.PreInstallScript = value.String
			}
		case softwarepackage.FieldPostInstallScript:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field post_install_script", values[i])
			} else if value.Valid {
				sp.PostInstallScript = value.String
			}
		case softwarepackage.FieldUninstallMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uninstall_method", values[i])
			} else if value.Valid {
				sp.UninstallMethod = value.String
			}
		case softwarepackage.FieldInstallsItems:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field installs_items", values[i])
			} else if value.Valid {
				sp.InstallsItems = value.String
			}
		case softwarepackage.FieldReceipts:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field receipts", values[i])
			} else if value.Valid {
				sp.Receipts = value.String
			}
		case softwarepackage.FieldBlockingApps:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field blocking_apps", values[i])
			} else if value.Valid {
				sp.BlockingApps = value.String
			}
		case softwarepackage.FieldRestartAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field restart_action", values[i])
			} else if value.Valid {
				sp.RestartAction = softwarepackage.RestartAction(value.String)
			}
		case softwarepackage.FieldMinOsVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field min_os_version", values[i])
			} else if value.Valid {
				sp.MinOsVersion = value.String
			}
		case softwarepackage.FieldMaxOsVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field max_os_version", values[i])
			} else if value.Valid {
				sp.MaxOsVersion = value.String
			}
		case softwarepackage.FieldSupportedArchitectures:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field supported_architectures", values[i])
			} else if value.Valid {
				sp.SupportedArchitectures = value.String
			}
		case softwarepackage.FieldForceInstallDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field force_install_date", values[i])
			} else if value.Valid {
				sp.ForceInstallDate = new(time.Time)
				*sp.ForceInstallDate = value.Time
			}
		case softwarepackage.FieldUnattendedInstall:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field unattended_install", values[i])
			} else if value.Valid {
				sp.UnattendedInstall = value.Bool
			}
		case softwarepackage.FieldUnattendedUninstall:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field unattended_uninstall", values[i])
			} else if value.Valid {
				sp.UnattendedUninstall = value.Bool
			}
		case softwarepackage.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				sp.Status = softwarepackage.Status(value.String)
			}
		case softwarepackage.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				sp.Source = softwarepackage.Source(value.String)
			}
		case softwarepackage.FieldCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created", values[i])
			} else if value.Valid {
				sp.Created = value.Time
			}
		case softwarepackage.FieldModified:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field modified", values[i])
			} else if value.Valid {
				sp.Modified = value.Time
			}
		case softwarepackage.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field software_package_subscribers", value)
			} else if value.Valid {
				sp.software_package_subscribers = new(int)
				*sp.software_package_subscribers = int(value.Int64)
			}
		case softwarepackage.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field software_repo_packages", value)
			} else if value.Valid {
				sp.software_repo_packages = new(int)
				*sp.software_repo_packages = int(value.Int64)
			}
		case softwarepackage.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field tenant_software_packages", value)
			} else if value.Valid {
				sp.tenant_software_packages = new(int)
				*sp.tenant_software_packages = int(value.Int64)
			}
		default:
			sp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SoftwarePackage.
// This includes values selected through modifiers, order, etc.
func (sp *SoftwarePackage) Value(name string) (ent.Value, error) {
	return sp.selectValues.Get(name)
}

// QueryRepo queries the "repo" edge of the SoftwarePackage entity.
func (sp *SoftwarePackage) QueryRepo() *SoftwareRepoQuery {
	return NewSoftwarePackageClient(sp.config).QueryRepo(sp)
}

// QueryCatalogs queries the "catalogs" edge of the SoftwarePackage entity.
func (sp *SoftwarePackage) QueryCatalogs() *SoftwareCatalogQuery {
	return NewSoftwarePackageClient(sp.config).QueryCatalogs(sp)
}

// QueryTenant queries the "tenant" edge of the SoftwarePackage entity.
func (sp *SoftwarePackage) QueryTenant() *TenantQuery {
	return NewSoftwarePackageClient(sp.config).QueryTenant(sp)
}

// QueryInstallLogs queries the "install_logs" edge of the SoftwarePackage entity.
func (sp *SoftwarePackage) QueryInstallLogs() *SoftwareInstallLogQuery {
	return NewSoftwarePackageClient(sp.config).QueryInstallLogs(sp)
}

// QueryRequires queries the "requires" edge of the SoftwarePackage entity.
func (sp *SoftwarePackage) QueryRequires() *SoftwarePackageQuery {
	return NewSoftwarePackageClient(sp.config).QueryRequires(sp)
}

// QueryUpdateFor queries the "update_for" edge of the SoftwarePackage entity.
func (sp *SoftwarePackage) QueryUpdateFor() *SoftwarePackageQuery {
	return NewSoftwarePackageClient(sp.config).QueryUpdateFor(sp)
}

// QueryGlobalRef queries the "global_ref" edge of the SoftwarePackage entity.
func (sp *SoftwarePackage) QueryGlobalRef() *SoftwarePackageQuery {
	return NewSoftwarePackageClient(sp.config).QueryGlobalRef(sp)
}

// QuerySubscribers queries the "subscribers" edge of the SoftwarePackage entity.
func (sp *SoftwarePackage) QuerySubscribers() *SoftwarePackageQuery {
	return NewSoftwarePackageClient(sp.config).QuerySubscribers(sp)
}

// Update returns a builder for updating this SoftwarePackage.
// Note that you need to call SoftwarePackage.Unwrap() before calling this method if this SoftwarePackage
// was returned from a transaction, and the transaction was committed or rolled back.
func (sp *SoftwarePackage) Update() *SoftwarePackageUpdateOne {
	return NewSoftwarePackageClient(sp.config).UpdateOne(sp)
}

// Unwrap unwraps the SoftwarePackage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sp *SoftwarePackage) Unwrap() *SoftwarePackage {
	_tx, ok := sp.config.driver.(*txDriver)
	if !ok {
		panic("ent: SoftwarePackage is not a transactional entity")
	}
	sp.config.driver = _tx.drv
	return sp
}

// String implements the fmt.Stringer.
func (sp *SoftwarePackage) String() string {
	var builder strings.Builder
	builder.WriteString("SoftwarePackage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sp.ID))
	builder.WriteString("name=")
	builder.WriteString(sp.Name)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(sp.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(sp.Version)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(fmt.Sprintf("%v", sp.Platform))
	builder.WriteString(", ")
	builder.WriteString("installer_path=")
	builder.WriteString(sp.InstallerPath)
	builder.WriteString(", ")
	builder.WriteString("checksum_sha256=")
	builder.WriteString(sp.ChecksumSha256)
	builder.WriteString(", ")
	builder.WriteString("size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", sp.SizeBytes))
	builder.WriteString(", ")
	builder.WriteString("icon_name=")
	builder.WriteString(sp.IconName)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(sp.Description)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(sp.Category)
	builder.WriteString(", ")
	builder.WriteString("developer=")
	builder.WriteString(sp.Developer)
	builder.WriteString(", ")
	builder.WriteString("pkginfo_data=")
	builder.WriteString(sp.PkginfoData)
	builder.WriteString(", ")
	builder.WriteString("pre_install_script=")
	builder.WriteString(sp.PreInstallScript)
	builder.WriteString(", ")
	builder.WriteString("post_install_script=")
	builder.WriteString(sp.PostInstallScript)
	builder.WriteString(", ")
	builder.WriteString("uninstall_method=")
	builder.WriteString(sp.UninstallMethod)
	builder.WriteString(", ")
	builder.WriteString("installs_items=")
	builder.WriteString(sp.InstallsItems)
	builder.WriteString(", ")
	builder.WriteString("receipts=")
	builder.WriteString(sp.Receipts)
	builder.WriteString(", ")
	builder.WriteString("blocking_apps=")
	builder.WriteString(sp.BlockingApps)
	builder.WriteString(", ")
	builder.WriteString("restart_action=")
	builder.WriteString(fmt.Sprintf("%v", sp.RestartAction))
	builder.WriteString(", ")
	builder.WriteString("min_os_version=")
	builder.WriteString(sp.MinOsVersion)
	builder.WriteString(", ")
	builder.WriteString("max_os_version=")
	builder.WriteString(sp.MaxOsVersion)
	builder.WriteString(", ")
	builder.WriteString("supported_architectures=")
	builder.WriteString(sp.SupportedArchitectures)
	builder.WriteString(", ")
	if v := sp.ForceInstallDate; v != nil {
		builder.WriteString("force_install_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("unattended_install=")
	builder.WriteString(fmt.Sprintf("%v", sp.UnattendedInstall))
	builder.WriteString(", ")
	builder.WriteString("unattended_uninstall=")
	builder.WriteString(fmt.Sprintf("%v", sp.UnattendedUninstall))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", sp.Status))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", sp.Source))
	builder.WriteString(", ")
	builder.WriteString("created=")
	builder.WriteString(sp.Created.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("modified=")
	builder.WriteString(sp.Modified.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SoftwarePackages is a parsable slice of SoftwarePackage.
type SoftwarePackages []*SoftwarePackage
