// Code generated by ent, DO NOT EDIT.

package nanohubsettings

import (
	"entgo.io/ent/dialect/sql"
	"github.com/open-uem/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLTE(FieldID, id))
}

// ServerURL applies equality check predicate on the "server_url" field. It's identical to ServerURLEQ.
func ServerURL(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldServerURL, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldUsername, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldPassword, v))
}

// CaCerFile applies equality check predicate on the "ca_cer_file" field. It's identical to CaCerFileEQ.
func CaCerFile(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldCaCerFile, v))
}

// ScepURL applies equality check predicate on the "scep_url" field. It's identical to ScepURLEQ.
func ScepURL(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldScepURL, v))
}

// ScepChallenge applies equality check predicate on the "scep_challenge" field. It's identical to ScepChallengeEQ.
func ScepChallenge(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldScepChallenge, v))
}

// MdmURL applies equality check predicate on the "mdm_url" field. It's identical to MdmURLEQ.
func MdmURL(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldMdmURL, v))
}

// VendorPrivateKeyPem applies equality check predicate on the "vendor_private_key_pem" field. It's identical to VendorPrivateKeyPemEQ.
func VendorPrivateKeyPem(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldVendorPrivateKeyPem, v))
}

// VendorCertPem applies equality check predicate on the "vendor_cert_pem" field. It's identical to VendorCertPemEQ.
func VendorCertPem(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldVendorCertPem, v))
}

// EnrollmentProfileID applies equality check predicate on the "enrollment_profile_id" field. It's identical to EnrollmentProfileIDEQ.
func EnrollmentProfileID(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldEnrollmentProfileID, v))
}

// ServerURLEQ applies the EQ predicate on the "server_url" field.
func ServerURLEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldServerURL, v))
}

// ServerURLNEQ applies the NEQ predicate on the "server_url" field.
func ServerURLNEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNEQ(FieldServerURL, v))
}

// ServerURLIn applies the In predicate on the "server_url" field.
func ServerURLIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIn(FieldServerURL, vs...))
}

// ServerURLNotIn applies the NotIn predicate on the "server_url" field.
func ServerURLNotIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotIn(FieldServerURL, vs...))
}

// ServerURLGT applies the GT predicate on the "server_url" field.
func ServerURLGT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGT(FieldServerURL, v))
}

// ServerURLGTE applies the GTE predicate on the "server_url" field.
func ServerURLGTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGTE(FieldServerURL, v))
}

// ServerURLLT applies the LT predicate on the "server_url" field.
func ServerURLLT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLT(FieldServerURL, v))
}

// ServerURLLTE applies the LTE predicate on the "server_url" field.
func ServerURLLTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLTE(FieldServerURL, v))
}

// ServerURLContains applies the Contains predicate on the "server_url" field.
func ServerURLContains(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContains(FieldServerURL, v))
}

// ServerURLHasPrefix applies the HasPrefix predicate on the "server_url" field.
func ServerURLHasPrefix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasPrefix(FieldServerURL, v))
}

// ServerURLHasSuffix applies the HasSuffix predicate on the "server_url" field.
func ServerURLHasSuffix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasSuffix(FieldServerURL, v))
}

// ServerURLIsNil applies the IsNil predicate on the "server_url" field.
func ServerURLIsNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIsNull(FieldServerURL))
}

// ServerURLNotNil applies the NotNil predicate on the "server_url" field.
func ServerURLNotNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotNull(FieldServerURL))
}

// ServerURLEqualFold applies the EqualFold predicate on the "server_url" field.
func ServerURLEqualFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEqualFold(FieldServerURL, v))
}

// ServerURLContainsFold applies the ContainsFold predicate on the "server_url" field.
func ServerURLContainsFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContainsFold(FieldServerURL, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameIsNil applies the IsNil predicate on the "username" field.
func UsernameIsNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIsNull(FieldUsername))
}

// UsernameNotNil applies the NotNil predicate on the "username" field.
func UsernameNotNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotNull(FieldUsername))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContainsFold(FieldUsername, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordIsNil applies the IsNil predicate on the "password" field.
func PasswordIsNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIsNull(FieldPassword))
}

// PasswordNotNil applies the NotNil predicate on the "password" field.
func PasswordNotNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotNull(FieldPassword))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContainsFold(FieldPassword, v))
}

// CaCerFileEQ applies the EQ predicate on the "ca_cer_file" field.
func CaCerFileEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldCaCerFile, v))
}

// CaCerFileNEQ applies the NEQ predicate on the "ca_cer_file" field.
func CaCerFileNEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNEQ(FieldCaCerFile, v))
}

// CaCerFileIn applies the In predicate on the "ca_cer_file" field.
func CaCerFileIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIn(FieldCaCerFile, vs...))
}

// CaCerFileNotIn applies the NotIn predicate on the "ca_cer_file" field.
func CaCerFileNotIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotIn(FieldCaCerFile, vs...))
}

// CaCerFileGT applies the GT predicate on the "ca_cer_file" field.
func CaCerFileGT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGT(FieldCaCerFile, v))
}

// CaCerFileGTE applies the GTE predicate on the "ca_cer_file" field.
func CaCerFileGTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGTE(FieldCaCerFile, v))
}

// CaCerFileLT applies the LT predicate on the "ca_cer_file" field.
func CaCerFileLT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLT(FieldCaCerFile, v))
}

// CaCerFileLTE applies the LTE predicate on the "ca_cer_file" field.
func CaCerFileLTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLTE(FieldCaCerFile, v))
}

// CaCerFileContains applies the Contains predicate on the "ca_cer_file" field.
func CaCerFileContains(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContains(FieldCaCerFile, v))
}

// CaCerFileHasPrefix applies the HasPrefix predicate on the "ca_cer_file" field.
func CaCerFileHasPrefix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasPrefix(FieldCaCerFile, v))
}

// CaCerFileHasSuffix applies the HasSuffix predicate on the "ca_cer_file" field.
func CaCerFileHasSuffix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasSuffix(FieldCaCerFile, v))
}

// CaCerFileIsNil applies the IsNil predicate on the "ca_cer_file" field.
func CaCerFileIsNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIsNull(FieldCaCerFile))
}

// CaCerFileNotNil applies the NotNil predicate on the "ca_cer_file" field.
func CaCerFileNotNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotNull(FieldCaCerFile))
}

// CaCerFileEqualFold applies the EqualFold predicate on the "ca_cer_file" field.
func CaCerFileEqualFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEqualFold(FieldCaCerFile, v))
}

// CaCerFileContainsFold applies the ContainsFold predicate on the "ca_cer_file" field.
func CaCerFileContainsFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContainsFold(FieldCaCerFile, v))
}

// ScepURLEQ applies the EQ predicate on the "scep_url" field.
func ScepURLEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldScepURL, v))
}

// ScepURLNEQ applies the NEQ predicate on the "scep_url" field.
func ScepURLNEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNEQ(FieldScepURL, v))
}

// ScepURLIn applies the In predicate on the "scep_url" field.
func ScepURLIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIn(FieldScepURL, vs...))
}

// ScepURLNotIn applies the NotIn predicate on the "scep_url" field.
func ScepURLNotIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotIn(FieldScepURL, vs...))
}

// ScepURLGT applies the GT predicate on the "scep_url" field.
func ScepURLGT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGT(FieldScepURL, v))
}

// ScepURLGTE applies the GTE predicate on the "scep_url" field.
func ScepURLGTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGTE(FieldScepURL, v))
}

// ScepURLLT applies the LT predicate on the "scep_url" field.
func ScepURLLT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLT(FieldScepURL, v))
}

// ScepURLLTE applies the LTE predicate on the "scep_url" field.
func ScepURLLTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLTE(FieldScepURL, v))
}

// ScepURLContains applies the Contains predicate on the "scep_url" field.
func ScepURLContains(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContains(FieldScepURL, v))
}

// ScepURLHasPrefix applies the HasPrefix predicate on the "scep_url" field.
func ScepURLHasPrefix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasPrefix(FieldScepURL, v))
}

// ScepURLHasSuffix applies the HasSuffix predicate on the "scep_url" field.
func ScepURLHasSuffix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasSuffix(FieldScepURL, v))
}

// ScepURLIsNil applies the IsNil predicate on the "scep_url" field.
func ScepURLIsNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIsNull(FieldScepURL))
}

// ScepURLNotNil applies the NotNil predicate on the "scep_url" field.
func ScepURLNotNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotNull(FieldScepURL))
}

// ScepURLEqualFold applies the EqualFold predicate on the "scep_url" field.
func ScepURLEqualFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEqualFold(FieldScepURL, v))
}

// ScepURLContainsFold applies the ContainsFold predicate on the "scep_url" field.
func ScepURLContainsFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContainsFold(FieldScepURL, v))
}

// ScepChallengeEQ applies the EQ predicate on the "scep_challenge" field.
func ScepChallengeEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldScepChallenge, v))
}

// ScepChallengeNEQ applies the NEQ predicate on the "scep_challenge" field.
func ScepChallengeNEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNEQ(FieldScepChallenge, v))
}

// ScepChallengeIn applies the In predicate on the "scep_challenge" field.
func ScepChallengeIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIn(FieldScepChallenge, vs...))
}

// ScepChallengeNotIn applies the NotIn predicate on the "scep_challenge" field.
func ScepChallengeNotIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotIn(FieldScepChallenge, vs...))
}

// ScepChallengeGT applies the GT predicate on the "scep_challenge" field.
func ScepChallengeGT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGT(FieldScepChallenge, v))
}

// ScepChallengeGTE applies the GTE predicate on the "scep_challenge" field.
func ScepChallengeGTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGTE(FieldScepChallenge, v))
}

// ScepChallengeLT applies the LT predicate on the "scep_challenge" field.
func ScepChallengeLT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLT(FieldScepChallenge, v))
}

// ScepChallengeLTE applies the LTE predicate on the "scep_challenge" field.
func ScepChallengeLTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLTE(FieldScepChallenge, v))
}

// ScepChallengeContains applies the Contains predicate on the "scep_challenge" field.
func ScepChallengeContains(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContains(FieldScepChallenge, v))
}

// ScepChallengeHasPrefix applies the HasPrefix predicate on the "scep_challenge" field.
func ScepChallengeHasPrefix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasPrefix(FieldScepChallenge, v))
}

// ScepChallengeHasSuffix applies the HasSuffix predicate on the "scep_challenge" field.
func ScepChallengeHasSuffix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasSuffix(FieldScepChallenge, v))
}

// ScepChallengeIsNil applies the IsNil predicate on the "scep_challenge" field.
func ScepChallengeIsNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIsNull(FieldScepChallenge))
}

// ScepChallengeNotNil applies the NotNil predicate on the "scep_challenge" field.
func ScepChallengeNotNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotNull(FieldScepChallenge))
}

// ScepChallengeEqualFold applies the EqualFold predicate on the "scep_challenge" field.
func ScepChallengeEqualFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEqualFold(FieldScepChallenge, v))
}

// ScepChallengeContainsFold applies the ContainsFold predicate on the "scep_challenge" field.
func ScepChallengeContainsFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContainsFold(FieldScepChallenge, v))
}

// MdmURLEQ applies the EQ predicate on the "mdm_url" field.
func MdmURLEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldMdmURL, v))
}

// MdmURLNEQ applies the NEQ predicate on the "mdm_url" field.
func MdmURLNEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNEQ(FieldMdmURL, v))
}

// MdmURLIn applies the In predicate on the "mdm_url" field.
func MdmURLIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIn(FieldMdmURL, vs...))
}

// MdmURLNotIn applies the NotIn predicate on the "mdm_url" field.
func MdmURLNotIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotIn(FieldMdmURL, vs...))
}

// MdmURLGT applies the GT predicate on the "mdm_url" field.
func MdmURLGT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGT(FieldMdmURL, v))
}

// MdmURLGTE applies the GTE predicate on the "mdm_url" field.
func MdmURLGTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGTE(FieldMdmURL, v))
}

// MdmURLLT applies the LT predicate on the "mdm_url" field.
func MdmURLLT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLT(FieldMdmURL, v))
}

// MdmURLLTE applies the LTE predicate on the "mdm_url" field.
func MdmURLLTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLTE(FieldMdmURL, v))
}

// MdmURLContains applies the Contains predicate on the "mdm_url" field.
func MdmURLContains(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContains(FieldMdmURL, v))
}

// MdmURLHasPrefix applies the HasPrefix predicate on the "mdm_url" field.
func MdmURLHasPrefix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasPrefix(FieldMdmURL, v))
}

// MdmURLHasSuffix applies the HasSuffix predicate on the "mdm_url" field.
func MdmURLHasSuffix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasSuffix(FieldMdmURL, v))
}

// MdmURLIsNil applies the IsNil predicate on the "mdm_url" field.
func MdmURLIsNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIsNull(FieldMdmURL))
}

// MdmURLNotNil applies the NotNil predicate on the "mdm_url" field.
func MdmURLNotNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotNull(FieldMdmURL))
}

// MdmURLEqualFold applies the EqualFold predicate on the "mdm_url" field.
func MdmURLEqualFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEqualFold(FieldMdmURL, v))
}

// MdmURLContainsFold applies the ContainsFold predicate on the "mdm_url" field.
func MdmURLContainsFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContainsFold(FieldMdmURL, v))
}

// VendorPrivateKeyPemEQ applies the EQ predicate on the "vendor_private_key_pem" field.
func VendorPrivateKeyPemEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldVendorPrivateKeyPem, v))
}

// VendorPrivateKeyPemNEQ applies the NEQ predicate on the "vendor_private_key_pem" field.
func VendorPrivateKeyPemNEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNEQ(FieldVendorPrivateKeyPem, v))
}

// VendorPrivateKeyPemIn applies the In predicate on the "vendor_private_key_pem" field.
func VendorPrivateKeyPemIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIn(FieldVendorPrivateKeyPem, vs...))
}

// VendorPrivateKeyPemNotIn applies the NotIn predicate on the "vendor_private_key_pem" field.
func VendorPrivateKeyPemNotIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotIn(FieldVendorPrivateKeyPem, vs...))
}

// VendorPrivateKeyPemGT applies the GT predicate on the "vendor_private_key_pem" field.
func VendorPrivateKeyPemGT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGT(FieldVendorPrivateKeyPem, v))
}

// VendorPrivateKeyPemGTE applies the GTE predicate on the "vendor_private_key_pem" field.
func VendorPrivateKeyPemGTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGTE(FieldVendorPrivateKeyPem, v))
}

// VendorPrivateKeyPemLT applies the LT predicate on the "vendor_private_key_pem" field.
func VendorPrivateKeyPemLT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLT(FieldVendorPrivateKeyPem, v))
}

// VendorPrivateKeyPemLTE applies the LTE predicate on the "vendor_private_key_pem" field.
func VendorPrivateKeyPemLTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLTE(FieldVendorPrivateKeyPem, v))
}

// VendorPrivateKeyPemContains applies the Contains predicate on the "vendor_private_key_pem" field.
func VendorPrivateKeyPemContains(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContains(FieldVendorPrivateKeyPem, v))
}

// VendorPrivateKeyPemHasPrefix applies the HasPrefix predicate on the "vendor_private_key_pem" field.
func VendorPrivateKeyPemHasPrefix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasPrefix(FieldVendorPrivateKeyPem, v))
}

// VendorPrivateKeyPemHasSuffix applies the HasSuffix predicate on the "vendor_private_key_pem" field.
func VendorPrivateKeyPemHasSuffix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasSuffix(FieldVendorPrivateKeyPem, v))
}

// VendorPrivateKeyPemIsNil applies the IsNil predicate on the "vendor_private_key_pem" field.
func VendorPrivateKeyPemIsNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIsNull(FieldVendorPrivateKeyPem))
}

// VendorPrivateKeyPemNotNil applies the NotNil predicate on the "vendor_private_key_pem" field.
func VendorPrivateKeyPemNotNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotNull(FieldVendorPrivateKeyPem))
}

// VendorPrivateKeyPemEqualFold applies the EqualFold predicate on the "vendor_private_key_pem" field.
func VendorPrivateKeyPemEqualFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEqualFold(FieldVendorPrivateKeyPem, v))
}

// VendorPrivateKeyPemContainsFold applies the ContainsFold predicate on the "vendor_private_key_pem" field.
func VendorPrivateKeyPemContainsFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContainsFold(FieldVendorPrivateKeyPem, v))
}

// VendorCertPemEQ applies the EQ predicate on the "vendor_cert_pem" field.
func VendorCertPemEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldVendorCertPem, v))
}

// VendorCertPemNEQ applies the NEQ predicate on the "vendor_cert_pem" field.
func VendorCertPemNEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNEQ(FieldVendorCertPem, v))
}

// VendorCertPemIn applies the In predicate on the "vendor_cert_pem" field.
func VendorCertPemIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIn(FieldVendorCertPem, vs...))
}

// VendorCertPemNotIn applies the NotIn predicate on the "vendor_cert_pem" field.
func VendorCertPemNotIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotIn(FieldVendorCertPem, vs...))
}

// VendorCertPemGT applies the GT predicate on the "vendor_cert_pem" field.
func VendorCertPemGT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGT(FieldVendorCertPem, v))
}

// VendorCertPemGTE applies the GTE predicate on the "vendor_cert_pem" field.
func VendorCertPemGTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGTE(FieldVendorCertPem, v))
}

// VendorCertPemLT applies the LT predicate on the "vendor_cert_pem" field.
func VendorCertPemLT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLT(FieldVendorCertPem, v))
}

// VendorCertPemLTE applies the LTE predicate on the "vendor_cert_pem" field.
func VendorCertPemLTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLTE(FieldVendorCertPem, v))
}

// VendorCertPemContains applies the Contains predicate on the "vendor_cert_pem" field.
func VendorCertPemContains(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContains(FieldVendorCertPem, v))
}

// VendorCertPemHasPrefix applies the HasPrefix predicate on the "vendor_cert_pem" field.
func VendorCertPemHasPrefix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasPrefix(FieldVendorCertPem, v))
}

// VendorCertPemHasSuffix applies the HasSuffix predicate on the "vendor_cert_pem" field.
func VendorCertPemHasSuffix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasSuffix(FieldVendorCertPem, v))
}

// VendorCertPemIsNil applies the IsNil predicate on the "vendor_cert_pem" field.
func VendorCertPemIsNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIsNull(FieldVendorCertPem))
}

// VendorCertPemNotNil applies the NotNil predicate on the "vendor_cert_pem" field.
func VendorCertPemNotNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotNull(FieldVendorCertPem))
}

// VendorCertPemEqualFold applies the EqualFold predicate on the "vendor_cert_pem" field.
func VendorCertPemEqualFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEqualFold(FieldVendorCertPem, v))
}

// VendorCertPemContainsFold applies the ContainsFold predicate on the "vendor_cert_pem" field.
func VendorCertPemContainsFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContainsFold(FieldVendorCertPem, v))
}

// EnrollmentProfileIDEQ applies the EQ predicate on the "enrollment_profile_id" field.
func EnrollmentProfileIDEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEQ(FieldEnrollmentProfileID, v))
}

// EnrollmentProfileIDNEQ applies the NEQ predicate on the "enrollment_profile_id" field.
func EnrollmentProfileIDNEQ(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNEQ(FieldEnrollmentProfileID, v))
}

// EnrollmentProfileIDIn applies the In predicate on the "enrollment_profile_id" field.
func EnrollmentProfileIDIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIn(FieldEnrollmentProfileID, vs...))
}

// EnrollmentProfileIDNotIn applies the NotIn predicate on the "enrollment_profile_id" field.
func EnrollmentProfileIDNotIn(vs ...string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotIn(FieldEnrollmentProfileID, vs...))
}

// EnrollmentProfileIDGT applies the GT predicate on the "enrollment_profile_id" field.
func EnrollmentProfileIDGT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGT(FieldEnrollmentProfileID, v))
}

// EnrollmentProfileIDGTE applies the GTE predicate on the "enrollment_profile_id" field.
func EnrollmentProfileIDGTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldGTE(FieldEnrollmentProfileID, v))
}

// EnrollmentProfileIDLT applies the LT predicate on the "enrollment_profile_id" field.
func EnrollmentProfileIDLT(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLT(FieldEnrollmentProfileID, v))
}

// EnrollmentProfileIDLTE applies the LTE predicate on the "enrollment_profile_id" field.
func EnrollmentProfileIDLTE(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldLTE(FieldEnrollmentProfileID, v))
}

// EnrollmentProfileIDContains applies the Contains predicate on the "enrollment_profile_id" field.
func EnrollmentProfileIDContains(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContains(FieldEnrollmentProfileID, v))
}

// EnrollmentProfileIDHasPrefix applies the HasPrefix predicate on the "enrollment_profile_id" field.
func EnrollmentProfileIDHasPrefix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasPrefix(FieldEnrollmentProfileID, v))
}

// EnrollmentProfileIDHasSuffix applies the HasSuffix predicate on the "enrollment_profile_id" field.
func EnrollmentProfileIDHasSuffix(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldHasSuffix(FieldEnrollmentProfileID, v))
}

// EnrollmentProfileIDIsNil applies the IsNil predicate on the "enrollment_profile_id" field.
func EnrollmentProfileIDIsNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldIsNull(FieldEnrollmentProfileID))
}

// EnrollmentProfileIDNotNil applies the NotNil predicate on the "enrollment_profile_id" field.
func EnrollmentProfileIDNotNil() predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldNotNull(FieldEnrollmentProfileID))
}

// EnrollmentProfileIDEqualFold applies the EqualFold predicate on the "enrollment_profile_id" field.
func EnrollmentProfileIDEqualFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldEqualFold(FieldEnrollmentProfileID, v))
}

// EnrollmentProfileIDContainsFold applies the ContainsFold predicate on the "enrollment_profile_id" field.
func EnrollmentProfileIDContainsFold(v string) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.FieldContainsFold(FieldEnrollmentProfileID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NanoHubSettings) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NanoHubSettings) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NanoHubSettings) predicate.NanoHubSettings {
	return predicate.NanoHubSettings(sql.NotPredicates(p))
}
