// Code generated by ent, DO NOT EDIT.

package managedpackage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/EigerCode/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldName, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldDisplayName, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldVersion, v))
}

// InstallerPath applies equality check predicate on the "installer_path" field. It's identical to InstallerPathEQ.
func InstallerPath(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldInstallerPath, v))
}

// ChecksumSha256 applies equality check predicate on the "checksum_sha256" field. It's identical to ChecksumSha256EQ.
func ChecksumSha256(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldChecksumSha256, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldSizeBytes, v))
}

// IconName applies equality check predicate on the "icon_name" field. It's identical to IconNameEQ.
func IconName(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldIconName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldDescription, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldCategory, v))
}

// Developer applies equality check predicate on the "developer" field. It's identical to DeveloperEQ.
func Developer(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldDeveloper, v))
}

// PkginfoData applies equality check predicate on the "pkginfo_data" field. It's identical to PkginfoDataEQ.
func PkginfoData(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldPkginfoData, v))
}

// PreInstallScript applies equality check predicate on the "pre_install_script" field. It's identical to PreInstallScriptEQ.
func PreInstallScript(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldPreInstallScript, v))
}

// PostInstallScript applies equality check predicate on the "post_install_script" field. It's identical to PostInstallScriptEQ.
func PostInstallScript(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldPostInstallScript, v))
}

// UninstallMethod applies equality check predicate on the "uninstall_method" field. It's identical to UninstallMethodEQ.
func UninstallMethod(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldUninstallMethod, v))
}

// InstallsItems applies equality check predicate on the "installs_items" field. It's identical to InstallsItemsEQ.
func InstallsItems(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldInstallsItems, v))
}

// Receipts applies equality check predicate on the "receipts" field. It's identical to ReceiptsEQ.
func Receipts(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldReceipts, v))
}

// BlockingApps applies equality check predicate on the "blocking_apps" field. It's identical to BlockingAppsEQ.
func BlockingApps(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldBlockingApps, v))
}

// MinOsVersion applies equality check predicate on the "min_os_version" field. It's identical to MinOsVersionEQ.
func MinOsVersion(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldMinOsVersion, v))
}

// MaxOsVersion applies equality check predicate on the "max_os_version" field. It's identical to MaxOsVersionEQ.
func MaxOsVersion(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldMaxOsVersion, v))
}

// SupportedArchitectures applies equality check predicate on the "supported_architectures" field. It's identical to SupportedArchitecturesEQ.
func SupportedArchitectures(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldSupportedArchitectures, v))
}

// ForceInstallDate applies equality check predicate on the "force_install_date" field. It's identical to ForceInstallDateEQ.
func ForceInstallDate(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldForceInstallDate, v))
}

// UnattendedInstall applies equality check predicate on the "unattended_install" field. It's identical to UnattendedInstallEQ.
func UnattendedInstall(v bool) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldUnattendedInstall, v))
}

// UnattendedUninstall applies equality check predicate on the "unattended_uninstall" field. It's identical to UnattendedUninstallEQ.
func UnattendedUninstall(v bool) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldUnattendedUninstall, v))
}

// Created applies equality check predicate on the "created" field. It's identical to CreatedEQ.
func Created(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldCreated, v))
}

// Modified applies equality check predicate on the "modified" field. It's identical to ModifiedEQ.
func Modified(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldModified, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldName, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameIsNil applies the IsNil predicate on the "display_name" field.
func DisplayNameIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldDisplayName))
}

// DisplayNameNotNil applies the NotNil predicate on the "display_name" field.
func DisplayNameNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldDisplayName))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldDisplayName, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldVersion, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v Platform) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v Platform) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...Platform) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...Platform) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldPlatform, vs...))
}

// InstallerPathEQ applies the EQ predicate on the "installer_path" field.
func InstallerPathEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldInstallerPath, v))
}

// InstallerPathNEQ applies the NEQ predicate on the "installer_path" field.
func InstallerPathNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldInstallerPath, v))
}

// InstallerPathIn applies the In predicate on the "installer_path" field.
func InstallerPathIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldInstallerPath, vs...))
}

// InstallerPathNotIn applies the NotIn predicate on the "installer_path" field.
func InstallerPathNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldInstallerPath, vs...))
}

// InstallerPathGT applies the GT predicate on the "installer_path" field.
func InstallerPathGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldInstallerPath, v))
}

// InstallerPathGTE applies the GTE predicate on the "installer_path" field.
func InstallerPathGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldInstallerPath, v))
}

// InstallerPathLT applies the LT predicate on the "installer_path" field.
func InstallerPathLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldInstallerPath, v))
}

// InstallerPathLTE applies the LTE predicate on the "installer_path" field.
func InstallerPathLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldInstallerPath, v))
}

// InstallerPathContains applies the Contains predicate on the "installer_path" field.
func InstallerPathContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldInstallerPath, v))
}

// InstallerPathHasPrefix applies the HasPrefix predicate on the "installer_path" field.
func InstallerPathHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldInstallerPath, v))
}

// InstallerPathHasSuffix applies the HasSuffix predicate on the "installer_path" field.
func InstallerPathHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldInstallerPath, v))
}

// InstallerPathEqualFold applies the EqualFold predicate on the "installer_path" field.
func InstallerPathEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldInstallerPath, v))
}

// InstallerPathContainsFold applies the ContainsFold predicate on the "installer_path" field.
func InstallerPathContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldInstallerPath, v))
}

// ChecksumSha256EQ applies the EQ predicate on the "checksum_sha256" field.
func ChecksumSha256EQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldChecksumSha256, v))
}

// ChecksumSha256NEQ applies the NEQ predicate on the "checksum_sha256" field.
func ChecksumSha256NEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldChecksumSha256, v))
}

// ChecksumSha256In applies the In predicate on the "checksum_sha256" field.
func ChecksumSha256In(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldChecksumSha256, vs...))
}

// ChecksumSha256NotIn applies the NotIn predicate on the "checksum_sha256" field.
func ChecksumSha256NotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldChecksumSha256, vs...))
}

// ChecksumSha256GT applies the GT predicate on the "checksum_sha256" field.
func ChecksumSha256GT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldChecksumSha256, v))
}

// ChecksumSha256GTE applies the GTE predicate on the "checksum_sha256" field.
func ChecksumSha256GTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldChecksumSha256, v))
}

// ChecksumSha256LT applies the LT predicate on the "checksum_sha256" field.
func ChecksumSha256LT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldChecksumSha256, v))
}

// ChecksumSha256LTE applies the LTE predicate on the "checksum_sha256" field.
func ChecksumSha256LTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldChecksumSha256, v))
}

// ChecksumSha256Contains applies the Contains predicate on the "checksum_sha256" field.
func ChecksumSha256Contains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldChecksumSha256, v))
}

// ChecksumSha256HasPrefix applies the HasPrefix predicate on the "checksum_sha256" field.
func ChecksumSha256HasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldChecksumSha256, v))
}

// ChecksumSha256HasSuffix applies the HasSuffix predicate on the "checksum_sha256" field.
func ChecksumSha256HasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldChecksumSha256, v))
}

// ChecksumSha256IsNil applies the IsNil predicate on the "checksum_sha256" field.
func ChecksumSha256IsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldChecksumSha256))
}

// ChecksumSha256NotNil applies the NotNil predicate on the "checksum_sha256" field.
func ChecksumSha256NotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldChecksumSha256))
}

// ChecksumSha256EqualFold applies the EqualFold predicate on the "checksum_sha256" field.
func ChecksumSha256EqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldChecksumSha256, v))
}

// ChecksumSha256ContainsFold applies the ContainsFold predicate on the "checksum_sha256" field.
func ChecksumSha256ContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldChecksumSha256, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldSizeBytes, v))
}

// SizeBytesIsNil applies the IsNil predicate on the "size_bytes" field.
func SizeBytesIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldSizeBytes))
}

// SizeBytesNotNil applies the NotNil predicate on the "size_bytes" field.
func SizeBytesNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldSizeBytes))
}

// IconNameEQ applies the EQ predicate on the "icon_name" field.
func IconNameEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldIconName, v))
}

// IconNameNEQ applies the NEQ predicate on the "icon_name" field.
func IconNameNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldIconName, v))
}

// IconNameIn applies the In predicate on the "icon_name" field.
func IconNameIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldIconName, vs...))
}

// IconNameNotIn applies the NotIn predicate on the "icon_name" field.
func IconNameNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldIconName, vs...))
}

// IconNameGT applies the GT predicate on the "icon_name" field.
func IconNameGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldIconName, v))
}

// IconNameGTE applies the GTE predicate on the "icon_name" field.
func IconNameGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldIconName, v))
}

// IconNameLT applies the LT predicate on the "icon_name" field.
func IconNameLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldIconName, v))
}

// IconNameLTE applies the LTE predicate on the "icon_name" field.
func IconNameLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldIconName, v))
}

// IconNameContains applies the Contains predicate on the "icon_name" field.
func IconNameContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldIconName, v))
}

// IconNameHasPrefix applies the HasPrefix predicate on the "icon_name" field.
func IconNameHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldIconName, v))
}

// IconNameHasSuffix applies the HasSuffix predicate on the "icon_name" field.
func IconNameHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldIconName, v))
}

// IconNameIsNil applies the IsNil predicate on the "icon_name" field.
func IconNameIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldIconName))
}

// IconNameNotNil applies the NotNil predicate on the "icon_name" field.
func IconNameNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldIconName))
}

// IconNameEqualFold applies the EqualFold predicate on the "icon_name" field.
func IconNameEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldIconName, v))
}

// IconNameContainsFold applies the ContainsFold predicate on the "icon_name" field.
func IconNameContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldIconName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldDescription, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryIsNil applies the IsNil predicate on the "category" field.
func CategoryIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldCategory))
}

// CategoryNotNil applies the NotNil predicate on the "category" field.
func CategoryNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldCategory))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldCategory, v))
}

// DeveloperEQ applies the EQ predicate on the "developer" field.
func DeveloperEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldDeveloper, v))
}

// DeveloperNEQ applies the NEQ predicate on the "developer" field.
func DeveloperNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldDeveloper, v))
}

// DeveloperIn applies the In predicate on the "developer" field.
func DeveloperIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldDeveloper, vs...))
}

// DeveloperNotIn applies the NotIn predicate on the "developer" field.
func DeveloperNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldDeveloper, vs...))
}

// DeveloperGT applies the GT predicate on the "developer" field.
func DeveloperGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldDeveloper, v))
}

// DeveloperGTE applies the GTE predicate on the "developer" field.
func DeveloperGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldDeveloper, v))
}

// DeveloperLT applies the LT predicate on the "developer" field.
func DeveloperLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldDeveloper, v))
}

// DeveloperLTE applies the LTE predicate on the "developer" field.
func DeveloperLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldDeveloper, v))
}

// DeveloperContains applies the Contains predicate on the "developer" field.
func DeveloperContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldDeveloper, v))
}

// DeveloperHasPrefix applies the HasPrefix predicate on the "developer" field.
func DeveloperHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldDeveloper, v))
}

// DeveloperHasSuffix applies the HasSuffix predicate on the "developer" field.
func DeveloperHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldDeveloper, v))
}

// DeveloperIsNil applies the IsNil predicate on the "developer" field.
func DeveloperIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldDeveloper))
}

// DeveloperNotNil applies the NotNil predicate on the "developer" field.
func DeveloperNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldDeveloper))
}

// DeveloperEqualFold applies the EqualFold predicate on the "developer" field.
func DeveloperEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldDeveloper, v))
}

// DeveloperContainsFold applies the ContainsFold predicate on the "developer" field.
func DeveloperContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldDeveloper, v))
}

// PkginfoDataEQ applies the EQ predicate on the "pkginfo_data" field.
func PkginfoDataEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldPkginfoData, v))
}

// PkginfoDataNEQ applies the NEQ predicate on the "pkginfo_data" field.
func PkginfoDataNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldPkginfoData, v))
}

// PkginfoDataIn applies the In predicate on the "pkginfo_data" field.
func PkginfoDataIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldPkginfoData, vs...))
}

// PkginfoDataNotIn applies the NotIn predicate on the "pkginfo_data" field.
func PkginfoDataNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldPkginfoData, vs...))
}

// PkginfoDataGT applies the GT predicate on the "pkginfo_data" field.
func PkginfoDataGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldPkginfoData, v))
}

// PkginfoDataGTE applies the GTE predicate on the "pkginfo_data" field.
func PkginfoDataGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldPkginfoData, v))
}

// PkginfoDataLT applies the LT predicate on the "pkginfo_data" field.
func PkginfoDataLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldPkginfoData, v))
}

// PkginfoDataLTE applies the LTE predicate on the "pkginfo_data" field.
func PkginfoDataLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldPkginfoData, v))
}

// PkginfoDataContains applies the Contains predicate on the "pkginfo_data" field.
func PkginfoDataContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldPkginfoData, v))
}

// PkginfoDataHasPrefix applies the HasPrefix predicate on the "pkginfo_data" field.
func PkginfoDataHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldPkginfoData, v))
}

// PkginfoDataHasSuffix applies the HasSuffix predicate on the "pkginfo_data" field.
func PkginfoDataHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldPkginfoData, v))
}

// PkginfoDataIsNil applies the IsNil predicate on the "pkginfo_data" field.
func PkginfoDataIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldPkginfoData))
}

// PkginfoDataNotNil applies the NotNil predicate on the "pkginfo_data" field.
func PkginfoDataNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldPkginfoData))
}

// PkginfoDataEqualFold applies the EqualFold predicate on the "pkginfo_data" field.
func PkginfoDataEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldPkginfoData, v))
}

// PkginfoDataContainsFold applies the ContainsFold predicate on the "pkginfo_data" field.
func PkginfoDataContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldPkginfoData, v))
}

// PreInstallScriptEQ applies the EQ predicate on the "pre_install_script" field.
func PreInstallScriptEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldPreInstallScript, v))
}

// PreInstallScriptNEQ applies the NEQ predicate on the "pre_install_script" field.
func PreInstallScriptNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldPreInstallScript, v))
}

// PreInstallScriptIn applies the In predicate on the "pre_install_script" field.
func PreInstallScriptIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldPreInstallScript, vs...))
}

// PreInstallScriptNotIn applies the NotIn predicate on the "pre_install_script" field.
func PreInstallScriptNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldPreInstallScript, vs...))
}

// PreInstallScriptGT applies the GT predicate on the "pre_install_script" field.
func PreInstallScriptGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldPreInstallScript, v))
}

// PreInstallScriptGTE applies the GTE predicate on the "pre_install_script" field.
func PreInstallScriptGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldPreInstallScript, v))
}

// PreInstallScriptLT applies the LT predicate on the "pre_install_script" field.
func PreInstallScriptLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldPreInstallScript, v))
}

// PreInstallScriptLTE applies the LTE predicate on the "pre_install_script" field.
func PreInstallScriptLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldPreInstallScript, v))
}

// PreInstallScriptContains applies the Contains predicate on the "pre_install_script" field.
func PreInstallScriptContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldPreInstallScript, v))
}

// PreInstallScriptHasPrefix applies the HasPrefix predicate on the "pre_install_script" field.
func PreInstallScriptHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldPreInstallScript, v))
}

// PreInstallScriptHasSuffix applies the HasSuffix predicate on the "pre_install_script" field.
func PreInstallScriptHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldPreInstallScript, v))
}

// PreInstallScriptIsNil applies the IsNil predicate on the "pre_install_script" field.
func PreInstallScriptIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldPreInstallScript))
}

// PreInstallScriptNotNil applies the NotNil predicate on the "pre_install_script" field.
func PreInstallScriptNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldPreInstallScript))
}

// PreInstallScriptEqualFold applies the EqualFold predicate on the "pre_install_script" field.
func PreInstallScriptEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldPreInstallScript, v))
}

// PreInstallScriptContainsFold applies the ContainsFold predicate on the "pre_install_script" field.
func PreInstallScriptContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldPreInstallScript, v))
}

// PostInstallScriptEQ applies the EQ predicate on the "post_install_script" field.
func PostInstallScriptEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldPostInstallScript, v))
}

// PostInstallScriptNEQ applies the NEQ predicate on the "post_install_script" field.
func PostInstallScriptNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldPostInstallScript, v))
}

// PostInstallScriptIn applies the In predicate on the "post_install_script" field.
func PostInstallScriptIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldPostInstallScript, vs...))
}

// PostInstallScriptNotIn applies the NotIn predicate on the "post_install_script" field.
func PostInstallScriptNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldPostInstallScript, vs...))
}

// PostInstallScriptGT applies the GT predicate on the "post_install_script" field.
func PostInstallScriptGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldPostInstallScript, v))
}

// PostInstallScriptGTE applies the GTE predicate on the "post_install_script" field.
func PostInstallScriptGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldPostInstallScript, v))
}

// PostInstallScriptLT applies the LT predicate on the "post_install_script" field.
func PostInstallScriptLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldPostInstallScript, v))
}

// PostInstallScriptLTE applies the LTE predicate on the "post_install_script" field.
func PostInstallScriptLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldPostInstallScript, v))
}

// PostInstallScriptContains applies the Contains predicate on the "post_install_script" field.
func PostInstallScriptContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldPostInstallScript, v))
}

// PostInstallScriptHasPrefix applies the HasPrefix predicate on the "post_install_script" field.
func PostInstallScriptHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldPostInstallScript, v))
}

// PostInstallScriptHasSuffix applies the HasSuffix predicate on the "post_install_script" field.
func PostInstallScriptHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldPostInstallScript, v))
}

// PostInstallScriptIsNil applies the IsNil predicate on the "post_install_script" field.
func PostInstallScriptIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldPostInstallScript))
}

// PostInstallScriptNotNil applies the NotNil predicate on the "post_install_script" field.
func PostInstallScriptNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldPostInstallScript))
}

// PostInstallScriptEqualFold applies the EqualFold predicate on the "post_install_script" field.
func PostInstallScriptEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldPostInstallScript, v))
}

// PostInstallScriptContainsFold applies the ContainsFold predicate on the "post_install_script" field.
func PostInstallScriptContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldPostInstallScript, v))
}

// UninstallMethodEQ applies the EQ predicate on the "uninstall_method" field.
func UninstallMethodEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldUninstallMethod, v))
}

// UninstallMethodNEQ applies the NEQ predicate on the "uninstall_method" field.
func UninstallMethodNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldUninstallMethod, v))
}

// UninstallMethodIn applies the In predicate on the "uninstall_method" field.
func UninstallMethodIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldUninstallMethod, vs...))
}

// UninstallMethodNotIn applies the NotIn predicate on the "uninstall_method" field.
func UninstallMethodNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldUninstallMethod, vs...))
}

// UninstallMethodGT applies the GT predicate on the "uninstall_method" field.
func UninstallMethodGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldUninstallMethod, v))
}

// UninstallMethodGTE applies the GTE predicate on the "uninstall_method" field.
func UninstallMethodGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldUninstallMethod, v))
}

// UninstallMethodLT applies the LT predicate on the "uninstall_method" field.
func UninstallMethodLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldUninstallMethod, v))
}

// UninstallMethodLTE applies the LTE predicate on the "uninstall_method" field.
func UninstallMethodLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldUninstallMethod, v))
}

// UninstallMethodContains applies the Contains predicate on the "uninstall_method" field.
func UninstallMethodContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldUninstallMethod, v))
}

// UninstallMethodHasPrefix applies the HasPrefix predicate on the "uninstall_method" field.
func UninstallMethodHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldUninstallMethod, v))
}

// UninstallMethodHasSuffix applies the HasSuffix predicate on the "uninstall_method" field.
func UninstallMethodHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldUninstallMethod, v))
}

// UninstallMethodIsNil applies the IsNil predicate on the "uninstall_method" field.
func UninstallMethodIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldUninstallMethod))
}

// UninstallMethodNotNil applies the NotNil predicate on the "uninstall_method" field.
func UninstallMethodNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldUninstallMethod))
}

// UninstallMethodEqualFold applies the EqualFold predicate on the "uninstall_method" field.
func UninstallMethodEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldUninstallMethod, v))
}

// UninstallMethodContainsFold applies the ContainsFold predicate on the "uninstall_method" field.
func UninstallMethodContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldUninstallMethod, v))
}

// InstallsItemsEQ applies the EQ predicate on the "installs_items" field.
func InstallsItemsEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldInstallsItems, v))
}

// InstallsItemsNEQ applies the NEQ predicate on the "installs_items" field.
func InstallsItemsNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldInstallsItems, v))
}

// InstallsItemsIn applies the In predicate on the "installs_items" field.
func InstallsItemsIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldInstallsItems, vs...))
}

// InstallsItemsNotIn applies the NotIn predicate on the "installs_items" field.
func InstallsItemsNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldInstallsItems, vs...))
}

// InstallsItemsGT applies the GT predicate on the "installs_items" field.
func InstallsItemsGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldInstallsItems, v))
}

// InstallsItemsGTE applies the GTE predicate on the "installs_items" field.
func InstallsItemsGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldInstallsItems, v))
}

// InstallsItemsLT applies the LT predicate on the "installs_items" field.
func InstallsItemsLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldInstallsItems, v))
}

// InstallsItemsLTE applies the LTE predicate on the "installs_items" field.
func InstallsItemsLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldInstallsItems, v))
}

// InstallsItemsContains applies the Contains predicate on the "installs_items" field.
func InstallsItemsContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldInstallsItems, v))
}

// InstallsItemsHasPrefix applies the HasPrefix predicate on the "installs_items" field.
func InstallsItemsHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldInstallsItems, v))
}

// InstallsItemsHasSuffix applies the HasSuffix predicate on the "installs_items" field.
func InstallsItemsHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldInstallsItems, v))
}

// InstallsItemsIsNil applies the IsNil predicate on the "installs_items" field.
func InstallsItemsIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldInstallsItems))
}

// InstallsItemsNotNil applies the NotNil predicate on the "installs_items" field.
func InstallsItemsNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldInstallsItems))
}

// InstallsItemsEqualFold applies the EqualFold predicate on the "installs_items" field.
func InstallsItemsEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldInstallsItems, v))
}

// InstallsItemsContainsFold applies the ContainsFold predicate on the "installs_items" field.
func InstallsItemsContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldInstallsItems, v))
}

// ReceiptsEQ applies the EQ predicate on the "receipts" field.
func ReceiptsEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldReceipts, v))
}

// ReceiptsNEQ applies the NEQ predicate on the "receipts" field.
func ReceiptsNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldReceipts, v))
}

// ReceiptsIn applies the In predicate on the "receipts" field.
func ReceiptsIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldReceipts, vs...))
}

// ReceiptsNotIn applies the NotIn predicate on the "receipts" field.
func ReceiptsNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldReceipts, vs...))
}

// ReceiptsGT applies the GT predicate on the "receipts" field.
func ReceiptsGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldReceipts, v))
}

// ReceiptsGTE applies the GTE predicate on the "receipts" field.
func ReceiptsGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldReceipts, v))
}

// ReceiptsLT applies the LT predicate on the "receipts" field.
func ReceiptsLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldReceipts, v))
}

// ReceiptsLTE applies the LTE predicate on the "receipts" field.
func ReceiptsLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldReceipts, v))
}

// ReceiptsContains applies the Contains predicate on the "receipts" field.
func ReceiptsContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldReceipts, v))
}

// ReceiptsHasPrefix applies the HasPrefix predicate on the "receipts" field.
func ReceiptsHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldReceipts, v))
}

// ReceiptsHasSuffix applies the HasSuffix predicate on the "receipts" field.
func ReceiptsHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldReceipts, v))
}

// ReceiptsIsNil applies the IsNil predicate on the "receipts" field.
func ReceiptsIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldReceipts))
}

// ReceiptsNotNil applies the NotNil predicate on the "receipts" field.
func ReceiptsNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldReceipts))
}

// ReceiptsEqualFold applies the EqualFold predicate on the "receipts" field.
func ReceiptsEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldReceipts, v))
}

// ReceiptsContainsFold applies the ContainsFold predicate on the "receipts" field.
func ReceiptsContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldReceipts, v))
}

// BlockingAppsEQ applies the EQ predicate on the "blocking_apps" field.
func BlockingAppsEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldBlockingApps, v))
}

// BlockingAppsNEQ applies the NEQ predicate on the "blocking_apps" field.
func BlockingAppsNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldBlockingApps, v))
}

// BlockingAppsIn applies the In predicate on the "blocking_apps" field.
func BlockingAppsIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldBlockingApps, vs...))
}

// BlockingAppsNotIn applies the NotIn predicate on the "blocking_apps" field.
func BlockingAppsNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldBlockingApps, vs...))
}

// BlockingAppsGT applies the GT predicate on the "blocking_apps" field.
func BlockingAppsGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldBlockingApps, v))
}

// BlockingAppsGTE applies the GTE predicate on the "blocking_apps" field.
func BlockingAppsGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldBlockingApps, v))
}

// BlockingAppsLT applies the LT predicate on the "blocking_apps" field.
func BlockingAppsLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldBlockingApps, v))
}

// BlockingAppsLTE applies the LTE predicate on the "blocking_apps" field.
func BlockingAppsLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldBlockingApps, v))
}

// BlockingAppsContains applies the Contains predicate on the "blocking_apps" field.
func BlockingAppsContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldBlockingApps, v))
}

// BlockingAppsHasPrefix applies the HasPrefix predicate on the "blocking_apps" field.
func BlockingAppsHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldBlockingApps, v))
}

// BlockingAppsHasSuffix applies the HasSuffix predicate on the "blocking_apps" field.
func BlockingAppsHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldBlockingApps, v))
}

// BlockingAppsIsNil applies the IsNil predicate on the "blocking_apps" field.
func BlockingAppsIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldBlockingApps))
}

// BlockingAppsNotNil applies the NotNil predicate on the "blocking_apps" field.
func BlockingAppsNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldBlockingApps))
}

// BlockingAppsEqualFold applies the EqualFold predicate on the "blocking_apps" field.
func BlockingAppsEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldBlockingApps, v))
}

// BlockingAppsContainsFold applies the ContainsFold predicate on the "blocking_apps" field.
func BlockingAppsContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldBlockingApps, v))
}

// RestartActionEQ applies the EQ predicate on the "restart_action" field.
func RestartActionEQ(v RestartAction) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldRestartAction, v))
}

// RestartActionNEQ applies the NEQ predicate on the "restart_action" field.
func RestartActionNEQ(v RestartAction) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldRestartAction, v))
}

// RestartActionIn applies the In predicate on the "restart_action" field.
func RestartActionIn(vs ...RestartAction) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldRestartAction, vs...))
}

// RestartActionNotIn applies the NotIn predicate on the "restart_action" field.
func RestartActionNotIn(vs ...RestartAction) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldRestartAction, vs...))
}

// RestartActionIsNil applies the IsNil predicate on the "restart_action" field.
func RestartActionIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldRestartAction))
}

// RestartActionNotNil applies the NotNil predicate on the "restart_action" field.
func RestartActionNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldRestartAction))
}

// MinOsVersionEQ applies the EQ predicate on the "min_os_version" field.
func MinOsVersionEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldMinOsVersion, v))
}

// MinOsVersionNEQ applies the NEQ predicate on the "min_os_version" field.
func MinOsVersionNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldMinOsVersion, v))
}

// MinOsVersionIn applies the In predicate on the "min_os_version" field.
func MinOsVersionIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldMinOsVersion, vs...))
}

// MinOsVersionNotIn applies the NotIn predicate on the "min_os_version" field.
func MinOsVersionNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldMinOsVersion, vs...))
}

// MinOsVersionGT applies the GT predicate on the "min_os_version" field.
func MinOsVersionGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldMinOsVersion, v))
}

// MinOsVersionGTE applies the GTE predicate on the "min_os_version" field.
func MinOsVersionGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldMinOsVersion, v))
}

// MinOsVersionLT applies the LT predicate on the "min_os_version" field.
func MinOsVersionLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldMinOsVersion, v))
}

// MinOsVersionLTE applies the LTE predicate on the "min_os_version" field.
func MinOsVersionLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldMinOsVersion, v))
}

// MinOsVersionContains applies the Contains predicate on the "min_os_version" field.
func MinOsVersionContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldMinOsVersion, v))
}

// MinOsVersionHasPrefix applies the HasPrefix predicate on the "min_os_version" field.
func MinOsVersionHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldMinOsVersion, v))
}

// MinOsVersionHasSuffix applies the HasSuffix predicate on the "min_os_version" field.
func MinOsVersionHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldMinOsVersion, v))
}

// MinOsVersionIsNil applies the IsNil predicate on the "min_os_version" field.
func MinOsVersionIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldMinOsVersion))
}

// MinOsVersionNotNil applies the NotNil predicate on the "min_os_version" field.
func MinOsVersionNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldMinOsVersion))
}

// MinOsVersionEqualFold applies the EqualFold predicate on the "min_os_version" field.
func MinOsVersionEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldMinOsVersion, v))
}

// MinOsVersionContainsFold applies the ContainsFold predicate on the "min_os_version" field.
func MinOsVersionContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldMinOsVersion, v))
}

// MaxOsVersionEQ applies the EQ predicate on the "max_os_version" field.
func MaxOsVersionEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldMaxOsVersion, v))
}

// MaxOsVersionNEQ applies the NEQ predicate on the "max_os_version" field.
func MaxOsVersionNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldMaxOsVersion, v))
}

// MaxOsVersionIn applies the In predicate on the "max_os_version" field.
func MaxOsVersionIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldMaxOsVersion, vs...))
}

// MaxOsVersionNotIn applies the NotIn predicate on the "max_os_version" field.
func MaxOsVersionNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldMaxOsVersion, vs...))
}

// MaxOsVersionGT applies the GT predicate on the "max_os_version" field.
func MaxOsVersionGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldMaxOsVersion, v))
}

// MaxOsVersionGTE applies the GTE predicate on the "max_os_version" field.
func MaxOsVersionGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldMaxOsVersion, v))
}

// MaxOsVersionLT applies the LT predicate on the "max_os_version" field.
func MaxOsVersionLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldMaxOsVersion, v))
}

// MaxOsVersionLTE applies the LTE predicate on the "max_os_version" field.
func MaxOsVersionLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldMaxOsVersion, v))
}

// MaxOsVersionContains applies the Contains predicate on the "max_os_version" field.
func MaxOsVersionContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldMaxOsVersion, v))
}

// MaxOsVersionHasPrefix applies the HasPrefix predicate on the "max_os_version" field.
func MaxOsVersionHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldMaxOsVersion, v))
}

// MaxOsVersionHasSuffix applies the HasSuffix predicate on the "max_os_version" field.
func MaxOsVersionHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldMaxOsVersion, v))
}

// MaxOsVersionIsNil applies the IsNil predicate on the "max_os_version" field.
func MaxOsVersionIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldMaxOsVersion))
}

// MaxOsVersionNotNil applies the NotNil predicate on the "max_os_version" field.
func MaxOsVersionNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldMaxOsVersion))
}

// MaxOsVersionEqualFold applies the EqualFold predicate on the "max_os_version" field.
func MaxOsVersionEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldMaxOsVersion, v))
}

// MaxOsVersionContainsFold applies the ContainsFold predicate on the "max_os_version" field.
func MaxOsVersionContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldMaxOsVersion, v))
}

// SupportedArchitecturesEQ applies the EQ predicate on the "supported_architectures" field.
func SupportedArchitecturesEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldSupportedArchitectures, v))
}

// SupportedArchitecturesNEQ applies the NEQ predicate on the "supported_architectures" field.
func SupportedArchitecturesNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldSupportedArchitectures, v))
}

// SupportedArchitecturesIn applies the In predicate on the "supported_architectures" field.
func SupportedArchitecturesIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldSupportedArchitectures, vs...))
}

// SupportedArchitecturesNotIn applies the NotIn predicate on the "supported_architectures" field.
func SupportedArchitecturesNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldSupportedArchitectures, vs...))
}

// SupportedArchitecturesGT applies the GT predicate on the "supported_architectures" field.
func SupportedArchitecturesGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldSupportedArchitectures, v))
}

// SupportedArchitecturesGTE applies the GTE predicate on the "supported_architectures" field.
func SupportedArchitecturesGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldSupportedArchitectures, v))
}

// SupportedArchitecturesLT applies the LT predicate on the "supported_architectures" field.
func SupportedArchitecturesLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldSupportedArchitectures, v))
}

// SupportedArchitecturesLTE applies the LTE predicate on the "supported_architectures" field.
func SupportedArchitecturesLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldSupportedArchitectures, v))
}

// SupportedArchitecturesContains applies the Contains predicate on the "supported_architectures" field.
func SupportedArchitecturesContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldSupportedArchitectures, v))
}

// SupportedArchitecturesHasPrefix applies the HasPrefix predicate on the "supported_architectures" field.
func SupportedArchitecturesHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldSupportedArchitectures, v))
}

// SupportedArchitecturesHasSuffix applies the HasSuffix predicate on the "supported_architectures" field.
func SupportedArchitecturesHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldSupportedArchitectures, v))
}

// SupportedArchitecturesIsNil applies the IsNil predicate on the "supported_architectures" field.
func SupportedArchitecturesIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldSupportedArchitectures))
}

// SupportedArchitecturesNotNil applies the NotNil predicate on the "supported_architectures" field.
func SupportedArchitecturesNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldSupportedArchitectures))
}

// SupportedArchitecturesEqualFold applies the EqualFold predicate on the "supported_architectures" field.
func SupportedArchitecturesEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldSupportedArchitectures, v))
}

// SupportedArchitecturesContainsFold applies the ContainsFold predicate on the "supported_architectures" field.
func SupportedArchitecturesContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldSupportedArchitectures, v))
}

// ForceInstallDateEQ applies the EQ predicate on the "force_install_date" field.
func ForceInstallDateEQ(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldForceInstallDate, v))
}

// ForceInstallDateNEQ applies the NEQ predicate on the "force_install_date" field.
func ForceInstallDateNEQ(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldForceInstallDate, v))
}

// ForceInstallDateIn applies the In predicate on the "force_install_date" field.
func ForceInstallDateIn(vs ...time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldForceInstallDate, vs...))
}

// ForceInstallDateNotIn applies the NotIn predicate on the "force_install_date" field.
func ForceInstallDateNotIn(vs ...time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldForceInstallDate, vs...))
}

// ForceInstallDateGT applies the GT predicate on the "force_install_date" field.
func ForceInstallDateGT(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldForceInstallDate, v))
}

// ForceInstallDateGTE applies the GTE predicate on the "force_install_date" field.
func ForceInstallDateGTE(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldForceInstallDate, v))
}

// ForceInstallDateLT applies the LT predicate on the "force_install_date" field.
func ForceInstallDateLT(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldForceInstallDate, v))
}

// ForceInstallDateLTE applies the LTE predicate on the "force_install_date" field.
func ForceInstallDateLTE(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldForceInstallDate, v))
}

// ForceInstallDateIsNil applies the IsNil predicate on the "force_install_date" field.
func ForceInstallDateIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldForceInstallDate))
}

// ForceInstallDateNotNil applies the NotNil predicate on the "force_install_date" field.
func ForceInstallDateNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldForceInstallDate))
}

// UnattendedInstallEQ applies the EQ predicate on the "unattended_install" field.
func UnattendedInstallEQ(v bool) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldUnattendedInstall, v))
}

// UnattendedInstallNEQ applies the NEQ predicate on the "unattended_install" field.
func UnattendedInstallNEQ(v bool) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldUnattendedInstall, v))
}

// UnattendedInstallIsNil applies the IsNil predicate on the "unattended_install" field.
func UnattendedInstallIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldUnattendedInstall))
}

// UnattendedInstallNotNil applies the NotNil predicate on the "unattended_install" field.
func UnattendedInstallNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldUnattendedInstall))
}

// UnattendedUninstallEQ applies the EQ predicate on the "unattended_uninstall" field.
func UnattendedUninstallEQ(v bool) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldUnattendedUninstall, v))
}

// UnattendedUninstallNEQ applies the NEQ predicate on the "unattended_uninstall" field.
func UnattendedUninstallNEQ(v bool) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldUnattendedUninstall, v))
}

// UnattendedUninstallIsNil applies the IsNil predicate on the "unattended_uninstall" field.
func UnattendedUninstallIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldUnattendedUninstall))
}

// UnattendedUninstallNotNil applies the NotNil predicate on the "unattended_uninstall" field.
func UnattendedUninstallNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldUnattendedUninstall))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldStatus))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldSource, vs...))
}

// SourceIsNil applies the IsNil predicate on the "source" field.
func SourceIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldSource))
}

// SourceNotNil applies the NotNil predicate on the "source" field.
func SourceNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldSource))
}

// CreatedEQ applies the EQ predicate on the "created" field.
func CreatedEQ(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldCreated, v))
}

// CreatedNEQ applies the NEQ predicate on the "created" field.
func CreatedNEQ(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldCreated, v))
}

// CreatedIn applies the In predicate on the "created" field.
func CreatedIn(vs ...time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldCreated, vs...))
}

// CreatedNotIn applies the NotIn predicate on the "created" field.
func CreatedNotIn(vs ...time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldCreated, vs...))
}

// CreatedGT applies the GT predicate on the "created" field.
func CreatedGT(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldCreated, v))
}

// CreatedGTE applies the GTE predicate on the "created" field.
func CreatedGTE(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldCreated, v))
}

// CreatedLT applies the LT predicate on the "created" field.
func CreatedLT(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldCreated, v))
}

// CreatedLTE applies the LTE predicate on the "created" field.
func CreatedLTE(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldCreated, v))
}

// CreatedIsNil applies the IsNil predicate on the "created" field.
func CreatedIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldCreated))
}

// CreatedNotNil applies the NotNil predicate on the "created" field.
func CreatedNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldCreated))
}

// ModifiedEQ applies the EQ predicate on the "modified" field.
func ModifiedEQ(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldModified, v))
}

// ModifiedNEQ applies the NEQ predicate on the "modified" field.
func ModifiedNEQ(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldModified, v))
}

// ModifiedIn applies the In predicate on the "modified" field.
func ModifiedIn(vs ...time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldModified, vs...))
}

// ModifiedNotIn applies the NotIn predicate on the "modified" field.
func ModifiedNotIn(vs ...time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldModified, vs...))
}

// ModifiedGT applies the GT predicate on the "modified" field.
func ModifiedGT(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldModified, v))
}

// ModifiedGTE applies the GTE predicate on the "modified" field.
func ModifiedGTE(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldModified, v))
}

// ModifiedLT applies the LT predicate on the "modified" field.
func ModifiedLT(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldModified, v))
}

// ModifiedLTE applies the LTE predicate on the "modified" field.
func ModifiedLTE(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldModified, v))
}

// ModifiedIsNil applies the IsNil predicate on the "modified" field.
func ModifiedIsNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIsNull(FieldModified))
}

// ModifiedNotNil applies the NotNil predicate on the "modified" field.
func ModifiedNotNil() predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotNull(FieldModified))
}

// HasRepo applies the HasEdge predicate on the "repo" edge.
func HasRepo() predicate.ManagedPackage {
	return predicate.ManagedPackage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RepoTable, RepoColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRepoWith applies the HasEdge predicate on the "repo" edge with a given conditions (other predicates).
func HasRepoWith(preds ...predicate.SoftwareRepo) predicate.ManagedPackage {
	return predicate.ManagedPackage(func(s *sql.Selector) {
		step := newRepoStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCatalogs applies the HasEdge predicate on the "catalogs" edge.
func HasCatalogs() predicate.ManagedPackage {
	return predicate.ManagedPackage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, CatalogsTable, CatalogsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCatalogsWith applies the HasEdge predicate on the "catalogs" edge with a given conditions (other predicates).
func HasCatalogsWith(preds ...predicate.SoftwareCatalog) predicate.ManagedPackage {
	return predicate.ManagedPackage(func(s *sql.Selector) {
		step := newCatalogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.ManagedPackage {
	return predicate.ManagedPackage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.ManagedPackage {
	return predicate.ManagedPackage(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInstallLogs applies the HasEdge predicate on the "install_logs" edge.
func HasInstallLogs() predicate.ManagedPackage {
	return predicate.ManagedPackage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InstallLogsTable, InstallLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInstallLogsWith applies the HasEdge predicate on the "install_logs" edge with a given conditions (other predicates).
func HasInstallLogsWith(preds ...predicate.SoftwareInstallLog) predicate.ManagedPackage {
	return predicate.ManagedPackage(func(s *sql.Selector) {
		step := newInstallLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRequires applies the HasEdge predicate on the "requires" edge.
func HasRequires() predicate.ManagedPackage {
	return predicate.ManagedPackage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, RequiresTable, RequiresPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRequiresWith applies the HasEdge predicate on the "requires" edge with a given conditions (other predicates).
func HasRequiresWith(preds ...predicate.ManagedPackage) predicate.ManagedPackage {
	return predicate.ManagedPackage(func(s *sql.Selector) {
		step := newRequiresStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUpdateFor applies the HasEdge predicate on the "update_for" edge.
func HasUpdateFor() predicate.ManagedPackage {
	return predicate.ManagedPackage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, UpdateForTable, UpdateForPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUpdateForWith applies the HasEdge predicate on the "update_for" edge with a given conditions (other predicates).
func HasUpdateForWith(preds ...predicate.ManagedPackage) predicate.ManagedPackage {
	return predicate.ManagedPackage(func(s *sql.Selector) {
		step := newUpdateForStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGlobalRef applies the HasEdge predicate on the "global_ref" edge.
func HasGlobalRef() predicate.ManagedPackage {
	return predicate.ManagedPackage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GlobalRefTable, GlobalRefColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGlobalRefWith applies the HasEdge predicate on the "global_ref" edge with a given conditions (other predicates).
func HasGlobalRefWith(preds ...predicate.ManagedPackage) predicate.ManagedPackage {
	return predicate.ManagedPackage(func(s *sql.Selector) {
		step := newGlobalRefStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubscribers applies the HasEdge predicate on the "subscribers" edge.
func HasSubscribers() predicate.ManagedPackage {
	return predicate.ManagedPackage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SubscribersTable, SubscribersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscribersWith applies the HasEdge predicate on the "subscribers" edge with a given conditions (other predicates).
func HasSubscribersWith(preds ...predicate.ManagedPackage) predicate.ManagedPackage {
	return predicate.ManagedPackage(func(s *sql.Selector) {
		step := newSubscribersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ManagedPackage) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ManagedPackage) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ManagedPackage) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.NotPredicates(p))
}
