// Code generated by ent, DO NOT EDIT.

package softwarecatalog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/EigerCode/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldEQ(FieldDescription, v))
}

// RingOrder applies equality check predicate on the "ring_order" field. It's identical to RingOrderEQ.
func RingOrder(v int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldEQ(FieldRingOrder, v))
}

// IsDefault applies equality check predicate on the "is_default" field. It's identical to IsDefaultEQ.
func IsDefault(v bool) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldEQ(FieldIsDefault, v))
}

// Created applies equality check predicate on the "created" field. It's identical to CreatedEQ.
func Created(v time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldEQ(FieldCreated, v))
}

// Modified applies equality check predicate on the "modified" field. It's identical to ModifiedEQ.
func Modified(v time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldEQ(FieldModified, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldContainsFold(FieldDescription, v))
}

// RingOrderEQ applies the EQ predicate on the "ring_order" field.
func RingOrderEQ(v int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldEQ(FieldRingOrder, v))
}

// RingOrderNEQ applies the NEQ predicate on the "ring_order" field.
func RingOrderNEQ(v int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldNEQ(FieldRingOrder, v))
}

// RingOrderIn applies the In predicate on the "ring_order" field.
func RingOrderIn(vs ...int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldIn(FieldRingOrder, vs...))
}

// RingOrderNotIn applies the NotIn predicate on the "ring_order" field.
func RingOrderNotIn(vs ...int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldNotIn(FieldRingOrder, vs...))
}

// RingOrderGT applies the GT predicate on the "ring_order" field.
func RingOrderGT(v int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldGT(FieldRingOrder, v))
}

// RingOrderGTE applies the GTE predicate on the "ring_order" field.
func RingOrderGTE(v int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldGTE(FieldRingOrder, v))
}

// RingOrderLT applies the LT predicate on the "ring_order" field.
func RingOrderLT(v int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldLT(FieldRingOrder, v))
}

// RingOrderLTE applies the LTE predicate on the "ring_order" field.
func RingOrderLTE(v int) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldLTE(FieldRingOrder, v))
}

// IsDefaultEQ applies the EQ predicate on the "is_default" field.
func IsDefaultEQ(v bool) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldEQ(FieldIsDefault, v))
}

// IsDefaultNEQ applies the NEQ predicate on the "is_default" field.
func IsDefaultNEQ(v bool) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldNEQ(FieldIsDefault, v))
}

// IsDefaultIsNil applies the IsNil predicate on the "is_default" field.
func IsDefaultIsNil() predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldIsNull(FieldIsDefault))
}

// IsDefaultNotNil applies the NotNil predicate on the "is_default" field.
func IsDefaultNotNil() predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldNotNull(FieldIsDefault))
}

// CreatedEQ applies the EQ predicate on the "created" field.
func CreatedEQ(v time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldEQ(FieldCreated, v))
}

// CreatedNEQ applies the NEQ predicate on the "created" field.
func CreatedNEQ(v time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldNEQ(FieldCreated, v))
}

// CreatedIn applies the In predicate on the "created" field.
func CreatedIn(vs ...time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldIn(FieldCreated, vs...))
}

// CreatedNotIn applies the NotIn predicate on the "created" field.
func CreatedNotIn(vs ...time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldNotIn(FieldCreated, vs...))
}

// CreatedGT applies the GT predicate on the "created" field.
func CreatedGT(v time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldGT(FieldCreated, v))
}

// CreatedGTE applies the GTE predicate on the "created" field.
func CreatedGTE(v time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldGTE(FieldCreated, v))
}

// CreatedLT applies the LT predicate on the "created" field.
func CreatedLT(v time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldLT(FieldCreated, v))
}

// CreatedLTE applies the LTE predicate on the "created" field.
func CreatedLTE(v time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldLTE(FieldCreated, v))
}

// CreatedIsNil applies the IsNil predicate on the "created" field.
func CreatedIsNil() predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldIsNull(FieldCreated))
}

// CreatedNotNil applies the NotNil predicate on the "created" field.
func CreatedNotNil() predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldNotNull(FieldCreated))
}

// ModifiedEQ applies the EQ predicate on the "modified" field.
func ModifiedEQ(v time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldEQ(FieldModified, v))
}

// ModifiedNEQ applies the NEQ predicate on the "modified" field.
func ModifiedNEQ(v time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldNEQ(FieldModified, v))
}

// ModifiedIn applies the In predicate on the "modified" field.
func ModifiedIn(vs ...time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldIn(FieldModified, vs...))
}

// ModifiedNotIn applies the NotIn predicate on the "modified" field.
func ModifiedNotIn(vs ...time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldNotIn(FieldModified, vs...))
}

// ModifiedGT applies the GT predicate on the "modified" field.
func ModifiedGT(v time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldGT(FieldModified, v))
}

// ModifiedGTE applies the GTE predicate on the "modified" field.
func ModifiedGTE(v time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldGTE(FieldModified, v))
}

// ModifiedLT applies the LT predicate on the "modified" field.
func ModifiedLT(v time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldLT(FieldModified, v))
}

// ModifiedLTE applies the LTE predicate on the "modified" field.
func ModifiedLTE(v time.Time) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldLTE(FieldModified, v))
}

// ModifiedIsNil applies the IsNil predicate on the "modified" field.
func ModifiedIsNil() predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldIsNull(FieldModified))
}

// ModifiedNotNil applies the NotNil predicate on the "modified" field.
func ModifiedNotNil() predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.FieldNotNull(FieldModified))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPackages applies the HasEdge predicate on the "packages" edge.
func HasPackages() predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, PackagesTable, PackagesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPackagesWith applies the HasEdge predicate on the "packages" edge with a given conditions (other predicates).
func HasPackagesWith(preds ...predicate.SoftwarePackage) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(func(s *sql.Selector) {
		step := newPackagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SoftwareCatalog) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SoftwareCatalog) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SoftwareCatalog) predicate.SoftwareCatalog {
	return predicate.SoftwareCatalog(sql.NotPredicates(p))
}
