// Code generated by ent, DO NOT EDIT.

package nanohubpushcertificate

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the nanohubpushcertificate type in the database.
	Label = "nano_hub_push_certificate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrivateKeyPem holds the string denoting the private_key_pem field in the database.
	FieldPrivateKeyPem = "private_key_pem"
	// FieldCsrPem holds the string denoting the csr_pem field in the database.
	FieldCsrPem = "csr_pem"
	// FieldCertificatePem holds the string denoting the certificate_pem field in the database.
	FieldCertificatePem = "certificate_pem"
	// FieldApnsTopic holds the string denoting the apns_topic field in the database.
	FieldApnsTopic = "apns_topic"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldUploadedAt holds the string denoting the uploaded_at field in the database.
	FieldUploadedAt = "uploaded_at"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// Table holds the table name of the nanohubpushcertificate in the database.
	Table = "nano_hub_push_certificates"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "tenants"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_nanohub_push"
)

// Columns holds all SQL columns for nanohubpushcertificate fields.
var Columns = []string{
	FieldID,
	FieldPrivateKeyPem,
	FieldCsrPem,
	FieldCertificatePem,
	FieldApnsTopic,
	FieldExpiresAt,
	FieldUploadedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPrivateKeyPem holds the default value on creation for the "private_key_pem" field.
	DefaultPrivateKeyPem string
	// DefaultCsrPem holds the default value on creation for the "csr_pem" field.
	DefaultCsrPem string
	// DefaultCertificatePem holds the default value on creation for the "certificate_pem" field.
	DefaultCertificatePem string
	// DefaultApnsTopic holds the default value on creation for the "apns_topic" field.
	DefaultApnsTopic string
)

// OrderOption defines the ordering options for the NanoHubPushCertificate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPrivateKeyPem orders the results by the private_key_pem field.
func ByPrivateKeyPem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrivateKeyPem, opts...).ToFunc()
}

// ByCsrPem orders the results by the csr_pem field.
func ByCsrPem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCsrPem, opts...).ToFunc()
}

// ByCertificatePem orders the results by the certificate_pem field.
func ByCertificatePem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCertificatePem, opts...).ToFunc()
}

// ByApnsTopic orders the results by the apns_topic field.
func ByApnsTopic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApnsTopic, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByUploadedAt orders the results by the uploaded_at field.
func ByUploadedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploadedAt, opts...).ToFunc()
}

// ByTenantCount orders the results by tenant count.
func ByTenantCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTenantStep(), opts...)
	}
}

// ByTenant orders the results by tenant terms.
func ByTenant(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TenantTable, TenantColumn),
	)
}
