// Code generated by ent, DO NOT EDIT.

package nanohubpushcertificate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/open-uem/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldLTE(FieldID, id))
}

// PrivateKeyPem applies equality check predicate on the "private_key_pem" field. It's identical to PrivateKeyPemEQ.
func PrivateKeyPem(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEQ(FieldPrivateKeyPem, v))
}

// CsrPem applies equality check predicate on the "csr_pem" field. It's identical to CsrPemEQ.
func CsrPem(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEQ(FieldCsrPem, v))
}

// CertificatePem applies equality check predicate on the "certificate_pem" field. It's identical to CertificatePemEQ.
func CertificatePem(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEQ(FieldCertificatePem, v))
}

// ApnsTopic applies equality check predicate on the "apns_topic" field. It's identical to ApnsTopicEQ.
func ApnsTopic(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEQ(FieldApnsTopic, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEQ(FieldExpiresAt, v))
}

// UploadedAt applies equality check predicate on the "uploaded_at" field. It's identical to UploadedAtEQ.
func UploadedAt(v time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEQ(FieldUploadedAt, v))
}

// PrivateKeyPemEQ applies the EQ predicate on the "private_key_pem" field.
func PrivateKeyPemEQ(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEQ(FieldPrivateKeyPem, v))
}

// PrivateKeyPemNEQ applies the NEQ predicate on the "private_key_pem" field.
func PrivateKeyPemNEQ(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNEQ(FieldPrivateKeyPem, v))
}

// PrivateKeyPemIn applies the In predicate on the "private_key_pem" field.
func PrivateKeyPemIn(vs ...string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldIn(FieldPrivateKeyPem, vs...))
}

// PrivateKeyPemNotIn applies the NotIn predicate on the "private_key_pem" field.
func PrivateKeyPemNotIn(vs ...string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNotIn(FieldPrivateKeyPem, vs...))
}

// PrivateKeyPemGT applies the GT predicate on the "private_key_pem" field.
func PrivateKeyPemGT(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldGT(FieldPrivateKeyPem, v))
}

// PrivateKeyPemGTE applies the GTE predicate on the "private_key_pem" field.
func PrivateKeyPemGTE(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldGTE(FieldPrivateKeyPem, v))
}

// PrivateKeyPemLT applies the LT predicate on the "private_key_pem" field.
func PrivateKeyPemLT(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldLT(FieldPrivateKeyPem, v))
}

// PrivateKeyPemLTE applies the LTE predicate on the "private_key_pem" field.
func PrivateKeyPemLTE(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldLTE(FieldPrivateKeyPem, v))
}

// PrivateKeyPemContains applies the Contains predicate on the "private_key_pem" field.
func PrivateKeyPemContains(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldContains(FieldPrivateKeyPem, v))
}

// PrivateKeyPemHasPrefix applies the HasPrefix predicate on the "private_key_pem" field.
func PrivateKeyPemHasPrefix(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldHasPrefix(FieldPrivateKeyPem, v))
}

// PrivateKeyPemHasSuffix applies the HasSuffix predicate on the "private_key_pem" field.
func PrivateKeyPemHasSuffix(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldHasSuffix(FieldPrivateKeyPem, v))
}

// PrivateKeyPemIsNil applies the IsNil predicate on the "private_key_pem" field.
func PrivateKeyPemIsNil() predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldIsNull(FieldPrivateKeyPem))
}

// PrivateKeyPemNotNil applies the NotNil predicate on the "private_key_pem" field.
func PrivateKeyPemNotNil() predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNotNull(FieldPrivateKeyPem))
}

// PrivateKeyPemEqualFold applies the EqualFold predicate on the "private_key_pem" field.
func PrivateKeyPemEqualFold(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEqualFold(FieldPrivateKeyPem, v))
}

// PrivateKeyPemContainsFold applies the ContainsFold predicate on the "private_key_pem" field.
func PrivateKeyPemContainsFold(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldContainsFold(FieldPrivateKeyPem, v))
}

// CsrPemEQ applies the EQ predicate on the "csr_pem" field.
func CsrPemEQ(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEQ(FieldCsrPem, v))
}

// CsrPemNEQ applies the NEQ predicate on the "csr_pem" field.
func CsrPemNEQ(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNEQ(FieldCsrPem, v))
}

// CsrPemIn applies the In predicate on the "csr_pem" field.
func CsrPemIn(vs ...string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldIn(FieldCsrPem, vs...))
}

// CsrPemNotIn applies the NotIn predicate on the "csr_pem" field.
func CsrPemNotIn(vs ...string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNotIn(FieldCsrPem, vs...))
}

// CsrPemGT applies the GT predicate on the "csr_pem" field.
func CsrPemGT(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldGT(FieldCsrPem, v))
}

// CsrPemGTE applies the GTE predicate on the "csr_pem" field.
func CsrPemGTE(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldGTE(FieldCsrPem, v))
}

// CsrPemLT applies the LT predicate on the "csr_pem" field.
func CsrPemLT(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldLT(FieldCsrPem, v))
}

// CsrPemLTE applies the LTE predicate on the "csr_pem" field.
func CsrPemLTE(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldLTE(FieldCsrPem, v))
}

// CsrPemContains applies the Contains predicate on the "csr_pem" field.
func CsrPemContains(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldContains(FieldCsrPem, v))
}

// CsrPemHasPrefix applies the HasPrefix predicate on the "csr_pem" field.
func CsrPemHasPrefix(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldHasPrefix(FieldCsrPem, v))
}

// CsrPemHasSuffix applies the HasSuffix predicate on the "csr_pem" field.
func CsrPemHasSuffix(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldHasSuffix(FieldCsrPem, v))
}

// CsrPemIsNil applies the IsNil predicate on the "csr_pem" field.
func CsrPemIsNil() predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldIsNull(FieldCsrPem))
}

// CsrPemNotNil applies the NotNil predicate on the "csr_pem" field.
func CsrPemNotNil() predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNotNull(FieldCsrPem))
}

// CsrPemEqualFold applies the EqualFold predicate on the "csr_pem" field.
func CsrPemEqualFold(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEqualFold(FieldCsrPem, v))
}

// CsrPemContainsFold applies the ContainsFold predicate on the "csr_pem" field.
func CsrPemContainsFold(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldContainsFold(FieldCsrPem, v))
}

// CertificatePemEQ applies the EQ predicate on the "certificate_pem" field.
func CertificatePemEQ(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEQ(FieldCertificatePem, v))
}

// CertificatePemNEQ applies the NEQ predicate on the "certificate_pem" field.
func CertificatePemNEQ(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNEQ(FieldCertificatePem, v))
}

// CertificatePemIn applies the In predicate on the "certificate_pem" field.
func CertificatePemIn(vs ...string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldIn(FieldCertificatePem, vs...))
}

// CertificatePemNotIn applies the NotIn predicate on the "certificate_pem" field.
func CertificatePemNotIn(vs ...string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNotIn(FieldCertificatePem, vs...))
}

// CertificatePemGT applies the GT predicate on the "certificate_pem" field.
func CertificatePemGT(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldGT(FieldCertificatePem, v))
}

// CertificatePemGTE applies the GTE predicate on the "certificate_pem" field.
func CertificatePemGTE(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldGTE(FieldCertificatePem, v))
}

// CertificatePemLT applies the LT predicate on the "certificate_pem" field.
func CertificatePemLT(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldLT(FieldCertificatePem, v))
}

// CertificatePemLTE applies the LTE predicate on the "certificate_pem" field.
func CertificatePemLTE(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldLTE(FieldCertificatePem, v))
}

// CertificatePemContains applies the Contains predicate on the "certificate_pem" field.
func CertificatePemContains(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldContains(FieldCertificatePem, v))
}

// CertificatePemHasPrefix applies the HasPrefix predicate on the "certificate_pem" field.
func CertificatePemHasPrefix(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldHasPrefix(FieldCertificatePem, v))
}

// CertificatePemHasSuffix applies the HasSuffix predicate on the "certificate_pem" field.
func CertificatePemHasSuffix(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldHasSuffix(FieldCertificatePem, v))
}

// CertificatePemIsNil applies the IsNil predicate on the "certificate_pem" field.
func CertificatePemIsNil() predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldIsNull(FieldCertificatePem))
}

// CertificatePemNotNil applies the NotNil predicate on the "certificate_pem" field.
func CertificatePemNotNil() predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNotNull(FieldCertificatePem))
}

// CertificatePemEqualFold applies the EqualFold predicate on the "certificate_pem" field.
func CertificatePemEqualFold(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEqualFold(FieldCertificatePem, v))
}

// CertificatePemContainsFold applies the ContainsFold predicate on the "certificate_pem" field.
func CertificatePemContainsFold(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldContainsFold(FieldCertificatePem, v))
}

// ApnsTopicEQ applies the EQ predicate on the "apns_topic" field.
func ApnsTopicEQ(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEQ(FieldApnsTopic, v))
}

// ApnsTopicNEQ applies the NEQ predicate on the "apns_topic" field.
func ApnsTopicNEQ(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNEQ(FieldApnsTopic, v))
}

// ApnsTopicIn applies the In predicate on the "apns_topic" field.
func ApnsTopicIn(vs ...string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldIn(FieldApnsTopic, vs...))
}

// ApnsTopicNotIn applies the NotIn predicate on the "apns_topic" field.
func ApnsTopicNotIn(vs ...string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNotIn(FieldApnsTopic, vs...))
}

// ApnsTopicGT applies the GT predicate on the "apns_topic" field.
func ApnsTopicGT(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldGT(FieldApnsTopic, v))
}

// ApnsTopicGTE applies the GTE predicate on the "apns_topic" field.
func ApnsTopicGTE(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldGTE(FieldApnsTopic, v))
}

// ApnsTopicLT applies the LT predicate on the "apns_topic" field.
func ApnsTopicLT(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldLT(FieldApnsTopic, v))
}

// ApnsTopicLTE applies the LTE predicate on the "apns_topic" field.
func ApnsTopicLTE(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldLTE(FieldApnsTopic, v))
}

// ApnsTopicContains applies the Contains predicate on the "apns_topic" field.
func ApnsTopicContains(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldContains(FieldApnsTopic, v))
}

// ApnsTopicHasPrefix applies the HasPrefix predicate on the "apns_topic" field.
func ApnsTopicHasPrefix(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldHasPrefix(FieldApnsTopic, v))
}

// ApnsTopicHasSuffix applies the HasSuffix predicate on the "apns_topic" field.
func ApnsTopicHasSuffix(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldHasSuffix(FieldApnsTopic, v))
}

// ApnsTopicIsNil applies the IsNil predicate on the "apns_topic" field.
func ApnsTopicIsNil() predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldIsNull(FieldApnsTopic))
}

// ApnsTopicNotNil applies the NotNil predicate on the "apns_topic" field.
func ApnsTopicNotNil() predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNotNull(FieldApnsTopic))
}

// ApnsTopicEqualFold applies the EqualFold predicate on the "apns_topic" field.
func ApnsTopicEqualFold(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEqualFold(FieldApnsTopic, v))
}

// ApnsTopicContainsFold applies the ContainsFold predicate on the "apns_topic" field.
func ApnsTopicContainsFold(v string) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldContainsFold(FieldApnsTopic, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNotNull(FieldExpiresAt))
}

// UploadedAtEQ applies the EQ predicate on the "uploaded_at" field.
func UploadedAtEQ(v time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldEQ(FieldUploadedAt, v))
}

// UploadedAtNEQ applies the NEQ predicate on the "uploaded_at" field.
func UploadedAtNEQ(v time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNEQ(FieldUploadedAt, v))
}

// UploadedAtIn applies the In predicate on the "uploaded_at" field.
func UploadedAtIn(vs ...time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldIn(FieldUploadedAt, vs...))
}

// UploadedAtNotIn applies the NotIn predicate on the "uploaded_at" field.
func UploadedAtNotIn(vs ...time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNotIn(FieldUploadedAt, vs...))
}

// UploadedAtGT applies the GT predicate on the "uploaded_at" field.
func UploadedAtGT(v time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldGT(FieldUploadedAt, v))
}

// UploadedAtGTE applies the GTE predicate on the "uploaded_at" field.
func UploadedAtGTE(v time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldGTE(FieldUploadedAt, v))
}

// UploadedAtLT applies the LT predicate on the "uploaded_at" field.
func UploadedAtLT(v time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldLT(FieldUploadedAt, v))
}

// UploadedAtLTE applies the LTE predicate on the "uploaded_at" field.
func UploadedAtLTE(v time.Time) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldLTE(FieldUploadedAt, v))
}

// UploadedAtIsNil applies the IsNil predicate on the "uploaded_at" field.
func UploadedAtIsNil() predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldIsNull(FieldUploadedAt))
}

// UploadedAtNotNil applies the NotNil predicate on the "uploaded_at" field.
func UploadedAtNotNil() predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.FieldNotNull(FieldUploadedAt))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NanoHubPushCertificate) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NanoHubPushCertificate) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NanoHubPushCertificate) predicate.NanoHubPushCertificate {
	return predicate.NanoHubPushCertificate(sql.NotPredicates(p))
}
